### PR TITLE
Revert to using ES5 transpiliation in production

### PR DESCRIPTION
**Pull request by jordanh**

### CODE REVIEW

**Comment by jordanh** [comment]
@mattkrick how about this?

**Comment by mattkrick** [comment]
that'll revert our dev env, too.
lemme fix that up real quick

**Comment by mattkrick** [comment]
doh! nevermind, i thought i was looking at the .babelrc. still early. 😴

**Comment by mattkrick** [comment]
how were you testing this? I just blindly made a commit & it seems to work, but i'm not sure.

anyways, instead of being webpack specific, i put envs in the babelrc. i did this because the server config will need that, too.

i'm also using stage-3 instead of stage-0 because if we're using stage-0 stuff, i wanna know about it & have it scream at me.

**Comment by jordanh** [comment]
I can get behind this approach, except it looks like the build is failing. Looking into it...

**Comment by jordanh** [comment]
Ok, I've looked at: https://babeljs.io/docs/plugins/preset-stage-3/

And now have a list of plugins to include. Commit forthcoming...

**Comment by mattkrick** [comment]
at least some of those are in the es2015 preset, right?

**Comment by jordanh** [comment]
Only:
   * transform-object-rest-spread
   * transform-async-generator-functions

Surprisingly!

**Pull request merged**
