### PR TITLE
Fix for strikethrough shortcut

### PR DESCRIPTION
**Pull request by p-parafiniuk**
Added fix for strikethrough when user press _shift + command + x_

### CODE REVIEW

**Comment by mattkrick** [comment]
this still isn't working for me (Chrome 64 on unbuntu 16.04).
i dug in a little bit, it looks "strikethrough" gets applied, but the style does not

**Comment by jordanh** [comment]
I just tested this, it works for me!

**Comment by mattkrick** [comment]
@jordanh can you confirm that it isn't working for you on prod? i think this may be browser/OS thing

**Comment by jordanh** [comment]
It isn't working on prod; wasn't working on dev. After applying @p-parafiniuk's PR it worked fine. Might still be a gap on Linux.

**Comment by mattkrick** [comment]
oh well that is weiiird! ah well, who uses linux, anyways? :smile:

**Pull request merged**
