### PR TITLE
support page events for non-users

### PR DESCRIPTION
**Pull request by mattkrick**
this lets us capture page events for folks using the demo without being logged in

TEST
- [ ] check out the demo with the segment.io debugger in another tab, as you progress, make sure events are being captured

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick what is the segment.io debugger?

**Comment by mattkrick** [comment]
oh gosh, a url woulda been good: https://app.segment.com/parabol-jordan/sources/actiondevelopment/debugger

if you use the dev key, that'll show you the events we are sending out in real time

**Comment by ackernaut** [comment]
Ok, I’ll try looking at that…

**Comment by ackernaut** [comment]
### Test No. 1
- [x] check out the demo with the segment.io debugger in another tab, as you progress, make sure events are being captured
screenshot 2018-12-05 09 38 12

**Pull request merged**
