### PR TITLE
Improve accessibility of dropdown menu component

### LINKED ISSUE #1625: Add project button inaccessible to screen reader users
## Issue - Bug

The add project button at the top of the project column is a `<span>` with `aria-hidden="true"` making it impossible to navigate to for users with assistive technology.

It's best to replace the `<span>` with a `<button>`, possibly using the `PlainButton` component.

### Acceptance Criteria
- Replace the <span> with a properly-labelled <button>

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1625 and #1624

Modifies the interaction of the dropdown menu component to work better for users with disabilities (and have better keyboard shortcuts!)

- The triggering element, in the case of the `AddProjectButton`, is now keyboard accessible (focusable, in the tab index, and responds to space/enter)
- Adds the proper roles and states to the various pieces of the menu widget
  - The triggering element has an `aria-haspopup` property to indicate that it opens a popup with a `menu` role
  - The dropdown menu has a `menu` role
  - The dropdown menu items have `menuitem` roles
- Adds proper keyboard interactions to the popup menu
  - When the dropdown menu is open, the up/down arrows move focus between the various items
  - Hitting tab or escape when the menu is open closes the menu and brings focus back to where it previously was.

### CODE REVIEW

**Comment by ackernaut** [comment]
Ideally, how soon would you like this reviewed @dan-f ?

**Comment by dan-f** [comment]
Thanks for asking! No rush, I ran into this while working on adding more end-to-end tests.

**Comment by ackernaut** [comment]
Giving this PR a gander.

**Comment by ackernaut** [comment]
This is what I’m seeing so far:

### Hotness

- I can tab to and trigger a menu toggle by pressing enter.
- When the menu opens I can press down and up to cycle through options.
- When I press escape the focus returns to the original trigger element.
- If I tap to open a menu I also have the affordance of pressing up and down. It also escapes to focus on the toggle.
- These keyboard behaviors work as expected on the user hub, dashboard filter (by team, owner), and menu that appears when having to choose a team when adding a new task to the dashboard column.

### Sadness

- These keyboard behaviors are not wired up to the menus at the footer of each card. For example, I can tab through the card content to the vertical ellipsis menu toggle and press enter. The card status menu appears. I cannot use up and down. I realize this may not have been in scope of this PR.
- The dashboard filter (by team or owner) has a layout issue: 
screenshot 2018-01-12 17 06 46

- When I try to add a task and have to pick a team I get this error message:
```RelayObservable.js:605 RelayObservable: Unhandled Error 
{_error: "Variable "$newProject" got invalid value {"status"…rder":0}.↵In field "teamMemberId": Unknown field."}
_error
:
"Variable "$newProject" got invalid value {"status":"active","teamMemberId":"auth0|5a593c183cb9392840bfff24::rkgc7338EG","sortOrder":0}.↵In field "teamMemberId": Unknown field."
__proto__
:
Object```

**Comment by dan-f** [comment]
@ackernaut thanks for the review! 🙏

The **sadness** points are great. I was hoping that uses of the `<Menu />` that I overlooked would bubble up.

As for the error - I believe that was fixed in a separate PR.

**Comment by ackernaut** [comment]
@dan-f not sure if and when I need to look at this again.

**Comment by dan-f** [comment]
Hey @ackernaut, thanks for circling back. I will let you know when I want another look. Since this isn't in the sprint, I've been putting in time every now and then when I've got a few min to burn, so progress will be slow.

**Comment by ackernaut** [comment]
Makes sense to me @dan-f thanks for the update. :)

**Comment by ackernaut** [comment]
@dan-f should we close this one and refer back to it later?

**Comment by dan-f** [comment]
😢 yes, deal 😃

**Comment by dan-f** [comment]
(Closing for now because this functionality was delivered for the assignment UI, and there are a ton of conflicts. Also other work has priority at the moment.)

**Pull request closed without merging**
