### PR TITLE
Mono

### PR DESCRIPTION
**Pull request by mattkrick**
today, the client & server share everything. same pacakge.json, same tsconfig, everything.
this is not great for a few reasons:
- server can't have a different version of a dependency than the client
- slower builds when only building a client or server
- not easy when we need another server (like action-chronos)
- same tsconfig means i have to tell the server & the client that both the DOM & the node environment are available to everyone, which is a lie
- future contexts like service workers have a Worker context, but can't get it without its own tsconfig
- way too easy to accidentally include a server dependency in the client & make the payload huge

this fixes it by giving each their own project, but kept in the same repo for easy deploying.
this also includes the upgrade to emotion v10

TEST
- [ ] `yarn build` works
- [ ] `yarn build && yarn start` works
- [ ] keyframe animations work (eg anonymous reflection chits, bouncing arrow saying move forward, etc)

i tried to keep all the commands the same. the only difference is to bump the version, you'll wanna call `lerna version` to bump all the versions at once.

### CODE REVIEW

**Comment by ackernaut** [comment]
Looking at this now

**Comment by ackernaut** [comment]
Does this require `lerna` other than bumping the version on packages?

**Comment by ackernaut** [comment]
@mattkrick not sure if I’m missing something but I’m seeing this when trying to run `yard build`
```
$ yarn build
yarn run v1.15.2
$ yarn workspace parabol-server build
$ yarn build:relay && yarn build:client
$ yarn update-schema && yarn build:relay-unsafe
$ node utils/updateSchema.babel.js && yarn tsgen

/Users/terryacker/code/parabolinc/action/node_modules/auth0/src/management/index.js:99
    throw new ArgumentError('Must provide a domain');
```
Does the `.env` file change any?

**Comment by mattkrick** [comment]
@ackernaut 
- nah, lerna is just for package bumps
- yep, just move your `.env` to `packages/server` and you're good to go. forgot about that one! i'll fix up the circleci test because it probably breaks there, too

**Comment by ackernaut** [comment]
Thanks for the tip re: `.env` — I moved that over. I’m stuck running `yarn build && yarn start` and see this in the browser console `Cannot read property 'WHOLE_PAGE' of undefined`. However, I can run `yarn dev`!

**Comment by mattkrick** [comment]
closing this in favor of `service-worker-for-real` since the fix already exists in it

**Pull request closed without merging**
