### PR TITLE
Hotfix update task [base: service-worker-for-real]

### PR DESCRIPTION
**Pull request by mattkrick**
Added in 3 safety checks:
- [ ] the server now has better (but not 100%) draft-js validation
- [ ] NullableCard gracefully fails if it can't parse the card content
- [ ] DraggableTask gracefully fails if the underlying card results in an error

TEST
- [ ] try updating a card, it works

EXTRA CREDIT
- [ ] go to a team dash with 2+ cards in a column. look up the ID for 1 of the cards (query the DB for tasks by team or click in the card & sniff the ID on the editTask event)
- [ ] go in the DB & make the card content invalid: 
```
r.db('actionDevelopment').table('Task')
  .get('EDiJQdzStc')
  .update({content: '{"blocks":[],"entityMap":{}}'})
```
- [ ] refresh the page, see the card is now empty & your cursor is in it
- [ ] comment out  L33,L35-37 in NullableTask, refresh & repeat the same steps. Now instead of a card, you see an error

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test No. 1

Added in 3 safety checks:
- [ ] the server now has better (but not 100%) draft-js validation
- [ ] NullableCard gracefully fails if it can't parse the card content
- [ ] DraggableTask gracefully fails if the underlying card results in an error


TEST
- [ ] try updating a card, it works

EXTRA CREDIT
- [ ] go to a team dash with 2+ cards in a column. look up the ID for 1 of the cards (query the DB for tasks by team or click in the card & sniff the ID on the editTask event)
- [ ] go in the DB & make the card content invalid: 
```
r.db('actionDevelopment').table('Task')
  .get('EDiJQdzStc')
  .update({content: '{"blocks":[],"entityMap":{}}'})
```
- [ ] refresh the page, see the card is now empty & your cursor is in it
- [ ] comment out  L33,L35-37 in NullableTask, refresh & repeat the same steps. Now instead of a card, you see an error

**Comment by ackernaut** [comment]
@mattkrick on the last checklist item, I still see an empty card with my cursor in it, but it says I should see an error. What kind of error? In the UI? client? server?

**Comment by mattkrick** [comment]
try this:
- [ ] create a new card, type "Foo"
- [ ] get ID of card
- [ ] go into database & run that update function on that card ID
- [ ] comment out those lines
- [ ] now hit refresh. there should be error text where a card should be

**Comment by ackernaut** [comment]
@mattkrick those are the steps I was using, and tried again, I still see an empty card instead of an error

**Comment by mattkrick** [comment]
eh, let's just merge it, the only thing it does is test the error boundary

**Pull request merged**
