### PR TITLE
Scroll to active agenda item

### LINKED ISSUE #1365: Scroll to active agenda item during meeting
When the agenda list gets long, it could be nice to scroll the active agenda item to the top of the list.

----

Updated acceptance criteria (thanks to @ackernaut and @jordanh)

## Acceptance criteria:
A user sees:
- [ ] the “Add Agenda Topic” input control at the end of the list (not above the list)
- [ ] once overflow happens, the active agenda item is obvious to the user (list is scrolled to bottom)
- [ ] once overflow happens, the input control is pinned to the bottom
- [ ] explore: visual affordance for overflow top and/or overflown bottom (perhaps a subtle box shadow shows at either end only when that end of the list is overflow)
- [ ] extra credit: input gains focus when users submit an item so that they can write out many without having to manually focus again

## Concepts:

agenda scroll concept

screenshot 2018-01-30 11 54 55

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1365 

## Test:
- [ ] Agenda Item Input placeholder/label now says "Add Agenda Topic..."
- [ ] Agenda Item Input sits below Agenda List
- [ ] As agenda items are added, Agenda List grows to a point and then overflows
- [ ] When overflow happens, the Agenda Item Input stays in-view no matter the scroll position
- [ ] When the list is overflown to the top, there's a drop shadow at the top of the list indicating additional content
- [ ] When the list is overflown to the bottom, there's a drop shadow at the bottom of the list indicating additional content
- [ ] extra credit: input gains focus when users submit an item so that they can write out many without having to manually focus again
- [ ] extra credit: when the list is overflown and you continue to add agenda items, the list scrolls to show the items you've just added.

### CODE REVIEW

**Comment by dan-f** [comment]
Heya @ackernaut, mind giving this a review? I'm real interested in any thoughts you have as to styling improvements. I think all the interactions are supported, except for the input re-focusing, which I will look at next.

**Comment by dan-f** [comment]
Hey @ackernaut thanks for your help with the styling! Looking good in chrome and FF now 🌟 

The only things left are:
  - [ ] scrolling to the end of the list when it overflows 'cause you're adding to it
  - [ ] re-focusing the input after submit

**Comment by ackernaut** [comment]
Dan, this is looking really, really good…
Hotness:
- I noticed that when I added an item to an overflown list from the First Call view, then proceeded with the meeting as a Facilitator, the auto-scroll worked like a charm. It had scrolled to show me what I submitted, then it scrolled to go to item number 1.
Sadness:
- Yeah, not having the auto-focus work after adding the first item is a bummer.
- I noticed that on Last Call view, when I add 1 new item, the item doesn’t really scroll into view (there is a slight change in scroll position but the item isn’t visible). But if I add a 2nd new item, then they both scroll into view.

I’d be ok capturing each of those as a rainy day bug if you’ve spent your points on this one. As it stands, I think the improvements are pretty slick and always appreciate your eye for detail!

**Comment by dan-f** [comment]
Hey, excellent, thanks for taking another look!

As for the **sadness** -
- I'm working on the auto-focus right now. It's bugging me enough, plus, just like it's faster to fire off a few agenda items while the input maintains focus, it's faster for me to fix this particular nuance while this story's got my focus 😉 
- Oh yikes, I thought I fixed that one... I'll attempt to reproduce it and take it from there.

**Comment by ackernaut** [comment]
Sounds good to me, even the pun.

**Comment by ackernaut** [comment]
I checked this out again locally! Looks really good!

**Comment by ackernaut** [comment]
🎉

**Pull request merged**
