### PR TITLE
Fix with coords

### LINKED ISSUE #1542: project editor menu isn't where it should
steps to repro:
1. go to team dash
2. click the + on the done column
3. hit `@` to open the mention menu
4. see the menu appear in the stuck column

### Acceptance Criteria
- Replace withCoords with withCoordsV2

Estimated effort: 12 points

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] on Team Dash, click the reassign button on a card. it opens
- [ ] hit Esc, it closes
- [ ] hit Enter, it opens again
- [ ] hit down arrow, the selected menu item goes down
- [ ] hit up arrow twice, non-menu items are not highlighted 
- [ ] hit Enter to reassign task, it reassigns
- [ ] hit enter, it opens up the menu again
- [ ] click into the body of another card to close the menu, it goes there.
- [ ] the same menu logic works for the GH menu on the card
- [ ] the same logic works for the status menu
- [ ] the same logic works for the meeting avatar menu (start a meeting, go to checkin phase, click an avatar, scroll with arrow keys)
- [ ] there is no flicker on the status or github card meus
- [ ] there is no flicker when adding or changling links in cards
- [ ] there is no flicker when adding mentions or tags or emojis in cards
- [ ] there is no flicker on the change check-in question tool tip
- [ ] there is no flicker on the add agenda item tooltip (add 1 agenda item, hover over the input field)
- [ ] click the status menu in the done column on team dash. it shows up where it should (fixes #1542)

DISCUSS
- [ ] look at `MenuWithShortcuts`. This follows the hipster "styled components" pattern. Emotion borrowed this pattern from https://github.com/styled-components/styled-components. I won't go into comparing other options here, but you can check out https://alligator.io/react/css-in-js-roundup-styling-react-components/ and https://github.com/A-gambit/CSS-IN-JS-Benchmarks/blob/master/RESULT.md
- [ ] look at `MenuItemWithShortcuts`. This follows a pattern very similar to aphrodite. They key differences are:
   - [ ] use cx to combine styles
   - [ ] you can add styles inline
   - [ ] you can add styles outside the component. No `withStyles` HOC needed!
- [ ] not shown is writing css using a tagged template literal. instead of using objects, we can write an actual css string. see an example here: https://emotion.sh/docs/css. i don't have a strong preference either way.

### CODE REVIEW

**Comment by dan-f** [comment]
# Test pass 1 ❌

TEST
- [x] on Team Dash, click the reassign button on a card. it opens
- ❌ hit Esc, it closes
  - It won't close; not even when I click out of the menu
- [ ] hit Enter, it opens again
- [x] hit down arrow, the selected menu item goes down
- [x] hit up arrow twice, non-menu items are not highlighted 
- ❌  hit Enter to reassign task, it reassigns
screen shot 2018-02-19 at 10 33 44 am

- [ ] hit enter, it opens up the menu again
- ❌ click into the body of another card to close the menu, it goes there.
- ❌ the same menu logic works for the GH menu on the card
  - Same problems with the menu not closing
- ❌ the same logic works for the status menu
  - Same problems with the menu not closing
- ❌  the same logic works for the meeting avatar menu (start a meeting, go to checkin phase, click an avatar, scroll with arrow keys)
  - Same issues with not being able to close the menu
  - Also, the coordinates computation seems to be borked:
screen shot 2018-02-19 at 10 36 24 am

- [ ] there is no flicker on the status or github card meus
- [ ] there is no flicker when adding or changling links in cards
- [ ] there is no flicker when adding mentions or tags or emojis in cards
- [ ] there is no flicker on the change check-in question tool tip
- [ ] there is no flicker on the add agenda item tooltip (add 1 agenda item, hover over the input field)
  - ❓ What flicker am I looking for? I don't see anything of note, but I also don't remember seeing a flicker before.
- ❌ click the status menu in the done column on team dash. it shows up where it should (fixes #1542)
screen shot 2018-02-19 at 10 40 00 am

**Comment by ackernaut** [comment]
@mattkrick I took a gander at the usage of emotion-js. Basically what I see are style objects similar to what we had but they can be written inline `className={css({})}` or be declared as constants and mixed in `className={cx(root, hover && active)}` or you can use styled DOM elements (?) like `const Button = styled('div')(({const}) => ({color: '#fff', fontSize: const}))` — did I miss anything? It seems that we are declaring the styles in a very similar way, just not 1 large thunk per component. Do you have a preference? When is it good to used the styled DOM element (or whatever it is best called)?

**Comment by ackernaut** [comment]
@mattkrick took a closer look at the docs, seems pretty straightforward compared to where we’ve been. I was also curious — is there an article that speaks to the benefits or advantages (can be performance, etc.)?

**Comment by mattkrick** [comment]
@ackernaut there's no article that really goes into the weeds to compare, but i wrote out my own comparison in https://github.com/ParabolInc/action/issues/1761.

i think folks like the styled components pattern because it removes styling considerations out of your main JSX. For example `<div className={cx(styles.foo, styles.bar)}>` becomes `<FooBar>`.

**Comment by ackernaut** [comment]
@mattkrick re: emotion-js forgot about those points on #1761 thanks for reminding me! As far as I’m concerned, emotion-js LGTM! 👍

**Comment by mattkrick** [comment]
@dan-f took me far too long to realize that i'm a big dummy & didn't push the last commit... i'll put this thing up on the dev server so we can test there

**Comment by dan-f** [comment]
# Test pass 2

- [x] on Team Dash, click the reassign button on a card. it opens
- [x] hit Esc, it closes
- ❌ hit Enter, it opens again
  - Nope, focus is lost and reset to the top of the page
- [x] hit down arrow, the selected menu item goes down
- [x] hit up arrow twice, non-menu items are not highlighted 
- [x] hit Enter to reassign task, it reassigns
- [x] hit enter, it opens up the menu again
- [x] click into the body of another card to close the menu, it goes there.
- [x] the same menu logic works for the GH menu on the card
  - ❓ Yes, but I noticed that the icons were missing the first time I loaded the page. The second time they were there. Assuming it was a weird caching issue
- [x] the same logic works for the status menu
- ❌ the same logic works for the meeting avatar menu (start a meeting, go to checkin phase, click an avatar, scroll with arrow keys)
  - Nope, can't scroll through options with arrow keys
  - ❗️ Also, isn't this PR about fixing the absolute positioning logic with modals? I'm seeing an issue:
screen shot 2018-02-20 at 3 51 24 pm

- [x] there is no flicker on the status or github card meus
- [x] there is no flicker when adding or changling links in cards
- [x] there is no flicker when adding mentions or tags or emojis in cards
- [x] there is no flicker on the change check-in question tool tip
- [x] there is no flicker on the add agenda item tooltip (add 1 agenda item, hover over the input field)
- [x] click the status menu in the done column on team dash. it shows up where it should (fixes #1542)

**Comment by dan-f** [comment]
# Test Pass 2

- [ ] on Team Dash, click the reassign button on a card. it opens
- [ ] hit Esc, it closes
- [ ] hit Enter, it opens again
- [ ] hit down arrow, the selected menu item goes down
- [ ] hit up arrow twice, non-menu items are not highlighted 
- [ ] hit Enter to reassign task, it reassigns
- [ ] hit enter, it opens up the menu again
- [ ] click into the body of another card to close the menu, it goes there.
- [ ] the same menu logic works for the GH menu on the card
- [ ] the same logic works for the status menu
- [ ] the same logic works for the meeting avatar menu (start a meeting, go to checkin phase, click an avatar, scroll with arrow keys)
- [ ] there is no flicker on the status or github card meus
- [ ] there is no flicker when adding or changling links in cards
- [ ] there is no flicker when adding mentions or tags or emojis in cards
- [ ] there is no flicker on the change check-in question tool tip
- [ ] there is no flicker on the add agenda item tooltip (add 1 agenda item, hover over the input field)
- [ ] click the status menu in the done column on team dash. it shows up where it should (fixes #1542)

**Comment by mattkrick** [comment]
@dan-f _good_ find! scrollX is fixed. merging!

**Pull request merged**
