### PR TITLE
Agenda updates

### LINKED ISSUE #846: Meeting agenda empty state
## Issue - Enhancement

Going through some user feedback notes, I see that there are a few points of feedback like, "I'm not sure what this Agenda list is even for," when folks look at the dashboard.

Let's add some empty state content to clarify what the meeting agenda is for.

- **Estimated effort:** 1 + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #896: 1st Agenda Item bugs
## Issue - Bug

1) can't re-order 1st agenda item during Updates phase
2) can't delete 1st agenda item during Updates phase

### PR DESCRIPTION
**Pull request by ackernaut**
- [x] fixes #846 agenda empty state
- [ ] fixes #896 1st agenda item bug

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick do you mind helping with #896 here?

**Comment by ackernaut** [comment]
@mattkrick there is a minor error when navigating from the Lobby to the Check-In round. If you press `+` you will see the error. If you refresh the browser at the Check-In round then it goes away. The `Sidebar.js` has `const agendaListDisabled = meetingPhase === CHECKIN;` but that doesn’t seem to refresh when going from the Lobby to Check-In. Check out `AgendaInputField.js` where `if (!disabled) { bindHotkey('+', focusOnInput); }`…

**Comment by mattkrick** [comment]
sure, i'll start workin on this one

**Comment by ackernaut** [comment]
@mattkrick 🙈  👻

**Comment by mattkrick** [comment]
merged into #902

**Comment by ackernaut** [comment]
@mattkrick gracias!!

**Pull request closed without merging**
