### PR TITLE
fixed removed groups filter

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- create a list of 10 reflections: people, man, cakes and pies, men, how now, women, pie, Now now, person, cake
- [ ] go to grouping phase & click auto group. it works*
- [ ] auto group again, it works

* there's still a chance it doesn't work, a race condition still exists somewhere, but it's better than being broken 100% of the time.

### CODE REVIEW

**Comment by jordanh** [comment]
# TEST
- create a list of 10 reflections: people, man, cakes and pies, men, how now, women, pie, Now now, person, cake
- [x] 🗒go to grouping phase & click auto group. it works*
- [x] 🗒auto group again, it works

* there's still a chance it doesn't work, a race condition still exists somewhere, but it's better than being broken 100% of the time.

## 🗒Notes

Auto grouping certainly works – i.e. nothing breaks. There are a couple of things I've observed:

1. The auto-group button no longer disappears when it cannot form new groups. It seems like you can always click it
2. The grouping heuristic doesn't seem super accurate on the data set I tried (dataset below). Not sure if the test was fair

I'm leaning toward merging this so that it's no fully borked. I will open a new issue to track tho.

Here's a screencap:

### Dataset
* Cookies
* Chocolate chip cookies
* Peanut butter cookies
* Cakes & pie
* peanut butter pie
* Cherry pie
* apple pie
* Pizza pie 🍕 
* Ice cream
* Cherry ice cream
* Vanilla ice cream
* Mango ice cream
* Pie crusts
* Salted caramel ice cream
* The letter pi
* Ice cream cone
* Tutti frutti ice cream
* I wish I had a cookie right now
* I eat ice cream, even in the winter
* Chocolate chocolate cookies 🍪 
* If your kid is being good, give them a cookie
* Eating pie
* Getting out the first slice of pie
* Slicing pie
* I've disabled cookies on my browser
* Ice cream 🍨 
* pie

**Comment by mattkrick** [comment]
i couldn't reproduce this. it grouped things in an OK way, and then after clicking autogroup 2x the button went away.

worth noting that google thinks eg "mango ice cream" and "vanilla ice cream" are different things, so they don't get grouped. but something like tutti frutti ice cream is just flagged as "ice cream'. interesting how that works. 
we could take partial lemmas, but i don't think that's necessary. it's nice to group the super obvious stuff & leave the rest up to the group. when we have the time to make our own it'll be better

**Comment by jordanh** [comment]
Oh bummer you couldn't repro it. I never saw it work the other way locally (but it worked fine on staging). If I can repro locally again do you want to look at it together?

**Comment by mattkrick** [comment]
it _has_ happened to me locally, but by the time you see it happen, it's too late. we need something reproducible so i can catch it while it's in the act

**Pull request merged**
