### PR TITLE
Retro meeting summary WIP

### PR DESCRIPTION
**Pull request by ackernaut**
- [ ] reworks header to support 2 meeting types
- [ ] reworks quick stats to support 2 meeting types
- [ ] shows new tasks by teammate as generated in the discussion phase (just like Action summary)
- [ ] does not show done tasks (rework to exclude that for Retro)
- [ ] does not show a section of folks who didn’t get tasks (rework to exclude for Retro)
- [ ] shows the generic “How did your meeting go?” as the footer
- [ ] shows a section of voted reflections that were discussed

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick I took a first pass at the summary section that shows all the reflections that were voted on by theme. Otherwise we make the header and quick stats a little more flexible to handle 2 meeting types, and we should have an MVP for meeting summary that supports retros.

**Comment by ackernaut** [comment]
This has latest from master, including the first pass of retro grouping from @mattkrick . For now, stuck behind voting and discussion phase implementation.

**Comment by mattkrick** [comment]
@ackernaut this is looking really solid. check branch `1750-end-meeting` and see if that gets you what you need.

**Comment by mattkrick** [comment]
merging this into 1750-end-meeting, will continue there

**Pull request closed without merging**
