### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by mattkrick**
a little housekeeping to speed up dev builds & bump some package versions

TEST
- [ ] test during integration test to make sure everything works

### CODE REVIEW

**Comment by jordanh** [comment]
If you test this one and don't see any TS warnings, merge away. Anything wrong I figure will be caught during integration testing.

**Comment by jordanh** [comment]
(this is to say, after this CI error is fixed:)

```
Error: Cannot find module 'mocha'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/action/e2e/scripts/runTests.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/root/action/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/root/action/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by mattkrick** [comment]
@jordanh ah! forgot to ping, ready to test! this one fixes graphiql

**Comment by mattkrick** [comment]
works for me, pushing to master

**Pull request merged**
