### PR TITLE
Retro cards

### LINKED ISSUE #1726: Build retro cards
### Background
To use a retro, we need a React Component that looks similar to a Task card, but has no status, offers anonymity, and has different DnD features. @dan-f if you take this on & feel the desire, consider React Storybook. I think we're at a good place to try incorporating it into our workflow. Heck you might get so good with it that you could use it to prototype instead of figma!

### Proposal
- Wrapped in an `AnonymouseEditorCard` that says “Someone is typing…” if the editor is not the creator. Similar to the NullCard for Tasks.
- Cards created by other participants show blurred text when not being edited.
- Cards have a hover state.
- Has a graphQL schema like {id, content, createdAt, group, isCreator}. In the DB we'll save the creatorId, but we'll only offer `isCreator` so we don't leak that information to the client.
- onHover, the zindex animates to 0 (to see the card when it's in a group)
- can be dragged as a RetroCard entity
- it shows a drop zone if being dragged but not onto another card/group
- if dropped on another RetroCard, it joins the droptarget's group, or makes a new group if none exists. a drop zone is shown behind the existing card/cards in group as new cards are placed behind the others.
- if dropped in the column (the area with remaining space at the bottom of the column), it leaves the group. if it was the 2nd to last card in the group, then the group is deleted.
- when the card is grabbed in order to be dragged is has a state indicating that it is being dragged. While it is being dragged it leaves a visual copy in the original position with styles that indicate multiplayer activity. The visual copy disappears when the card is dropped in the new position.
- The group has a label (input) with error states.
- The group can be toggled to an expand list view of cards and back to a stacked visualization.
- The card has placeholder text when a user creates a new one “My reflection thought…”
- The card has a delete button (visual: icon only) that appears on hover of cards that the user created during Reflect/Think.
- The card is read-only during Theme/Group and Discuss/Agenda.
- The cards can have a label for their column heading when dragged outside of their original column.
- Cards/groups can receive up to a max number of votes.

- **See** [1767 comment](https://github.com/ParabolInc/action/issues/1767#issuecomment-367115504) for more granular details and the link to Figma.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1726.

Run `yarn storybook`, then open http://localhost:6006 to test!

### CODE REVIEW

**Comment by jordanh** [comment]
This is just the best.

**Comment by ackernaut** [comment]
Here’s my feedback:

### Looking Good
These look good, but I will probably iterate on the finer details (hover state, styles like color, border color) as the theming gets polished:

- Add a reflection
- Anonymous being edited
- Reflection with one line
- Reflection with many lines (I like the idea of setting a max height with scroll)
- Read only
- Drop preview

### Thoughts/Questions
We need to tighten down the details on these (see notes):

- **Anon not being edited**: I want to decide how to lightly encrypt the text but maintain the same line-length and box-height so that the cards don’t breath/change height once revealed). I think the closest results might look like this > “I think that this is good.” becomes “G pwart qpao owxs pw ieuw.” where we have the same length for each word, same punctuation, but all the characters are randomly replaced with another alpha/numerical character. Just thinking out loud.
- **Reflection card with no content**: I like the subtle change to the placeholder once you focus. We need to decide if we want text controls (Delete > Cancel/Confirm) or the simple (x) always visible or on hover as the affordance for deleting. For simplicity, I prefer the iconic button (with proper a11y attributes, etc.). For clarity, I like the explicit link. Let me simmer on this one for a minute.
- With stage (and column labels): just a nuance, for the initial version they shouldn’t be editable and have a column label at the same time. Column labels get added once cards get grouped and cannot be edited. Otherwise looking good!
- Drag states: going to refer to the attached image 1) there is a visual indication of the card I’ve picked up as the user (highlighted with border, name tag, transparent) in the position where the card was before I drop it 2) there is the visual indication of cards that others have picked up (highlighted with border, name tag, full opacity) 3) there is the “actual” card that I’m dragging (has a deeper drop shadow, no name tag) 4) the cards that are hovered over don’t become transparent, they get a slightly darker background color making them look “over-shadowed”.

multiplayer grouping

**Comment by dan-f** [comment]
Thanks @ackernaut! Adding this to my queue to get back to you this afternoon.

**Comment by dan-f** [comment]
Alright, responding to your review:

> Anon not being edited: I want to decide how to lightly encrypt the text but maintain the same line-length and box-height so that the cards don’t breath/change height once revealed). I think the closest results might look like this > “I think that this is good.” becomes “G pwart qpao owxs pw ieuw.” where we have the same length for each word, same punctuation, but all the characters are randomly replaced with another alpha/numerical character. Just thinking out loud.

This is a good idea! If we were to do this, it would be a pretty minor change from a front-end perspective; since the server would know the true contents of the card being edited, the client would request the obfuscated content, and render it. So rather than the front end generating it's own gibberish, we'd simply take the gibberish as a prop. I can implement the front-end work in this PR if you like.

> Reflection card with no content: I like the subtle change to the placeholder once you focus. We need to decide if we want text controls (Delete > Cancel/Confirm) or the simple (x) always visible or on hover as the affordance for deleting. For simplicity, I prefer the iconic button (with proper a11y attributes, etc.). For clarity, I like the explicit link. Let me simmer on this one for a minute.

Yes, please simmer 🍜! For what it's worth, I initially built the `(x)` approach before moving to the text one, because I thought the text-based one was the "preferred" approach. Both are easy enough. Just let me know!

> With stage (and column labels): just a nuance, for the initial version they shouldn’t be editable and have a column label at the same time. Column labels get added once cards get grouped and cannot be edited. Otherwise looking good!

Cool, good to know! I was not sure which combination(s) of states would be appropriate. I think your tension can be thought of as "taken care of" since we can achieve this by omitting the stage prop until we're in the grouping phase.

> Drag states: going to refer to the attached image 1) there is a visual indication of the card I’ve picked up as the user (highlighted with border, name tag, transparent) in the position where the card was before I drop it 2) there is the visual indication of cards that others have picked up (highlighted with border, name tag, full opacity) 3) there is the “actual” card that I’m dragging (has a deeper drop shadow, no name tag) 4) the cards that are hovered over don’t become transparent, they get a slightly darker background color making them look “over-shadowed”.


OK - got it. I'll go ahead and make this update.

Thank you!!

**Comment by dan-f** [comment]
Rebased on `master`; force-pushing to update the remote.

**Comment by ackernaut** [comment]
@dan-f thanks for the quick response:

1) re: anon card content, glad you see a way forward for obfuscated content
2) re: delete controls, after simmering 🥘 I think we should try the simple (x) variant…if we find it has UX issues we can pull on the more explicit text-based  approach. Tapping (x) removes the card, just like tapping the (x) currently removes an agenda item. (Final color TBD but easy-peasy)
3) re: column labels on cards, good deal, and thanks for the label meta state!
4) re: drag states, thank you and let me know if I can clarify more as you go

**Comment by dan-f** [comment]
Alright Mr. @ackernaut, I'm pretty confident I've implemented this to-spec now. Would you mind giving one final look? Feel free to hit "merge" if you're happy with it, or let me know if you want to see any other changes!

**Comment by ackernaut** [comment]
Ok, I’ll plan to review first thing on Wednesday morning, if I don’t get to it this evening! Thanks @dan-f

**Comment by ackernaut** [comment]
Looking at latest Retro cards now…

**Comment by ackernaut** [comment]
🔥 👌 :shipit: 🚀 

Nice work on this, Dan! The components look well-written, the UI is well-represented, and Storybook is going to unlock better iteration on visual component states.

💯

**Pull request merged**
