### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by mattkrick**
changes
- [ ] uses the prettier formatter. we never had a formatter before. the closest thing to a formatter we had was `eslint --fix`. a formatter turns the code into an AST & then recreates code from the AST, so your styles are guaranteed to be deterministic. this'll cut down on the number of lines we have to review moving forward
- [ ] uses standard-js for linting. there are a lot of decisions i'm not thrilled about (no semicolons, spaces after function name declarations, single quotes in jsx, etc), but at the end of the day, it's all bike shedding. not having to maintain our own eslintrc? that's worth it. 
- [ ] uses a git pre-commit hook to do formatting & linting pre commit. This is kinda huge. Before, linting would take 45 - 60 seconds, so I'd often not lint before commiting, resulting in a failing CI. now, it automatically lints only the staged files, so it takes < 1 second. this means no more "lint" commits and failed CI from linting errors.

manual changes
- put `window` in front of few global vars
- move new Buffer to the safe Buffer.from
- remove the component index files because `export X from Y` kept breaking since it isn't proper ES (and grouping a bunch of components like that made it impossible to code split, plus users were downloading things they were never using)
- comment out/remove old, unused files
- add the standardJS badge to the readme

### CODE REVIEW

**Comment by jordanh** [comment]
I rebased this on current `master`

**Comment by jordanh** [comment]
I miss semis 🙁

**Comment by jordanh** [comment]
We could (should?) put our logo here: https://standardjs.com/#who-uses-javascript-standard-style

**Comment by jordanh** [comment]
# Test Cycle 1

- [x] build passes
- [x] retro meeting ran successfully
- [x] check-in questions file edited to add new questions
- [ ] ❌ could add new questions using pre-commit hook

## Notes

Upon commit, here's the message I see:

```
~/Source/github/Parabol/action.git ⑂prettier +  git commit -m 'flow + new checkin questions (prettier test)'
.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory
```

I've run `yarn && yarn build:relay`; am I missing something else?

**Comment by mattkrick** [comment]
@jordanh looks like you'll have to run `yarn add pre-commit && yarn remove pre-commit`.

Before my time at parabol, something called pre-commit was installed, which is basically the same thing as husky. When you install it, it hijacks the git hooks with its own shell script. so what's happening is when you call git add, git is calling its shell script, which is calling pre-commit, which no longer exists.

**Comment by mattkrick** [comment]
i also really, really miss semicolons. and i miss parenthesis that come right after function declarations, eg `foo()` not `foo ()`.

**Comment by mattkrick** [comment]
ok, merging the beast

**Pull request merged**
