### PR TITLE
fix #2100 retro interrupting chicken

### LINKED ISSUE #2100: New & Improved Interrupting Chicken™ 🐔
## Bug

Repro with 2 users on 2 devices to maintain focus on task card:
- Get to the Retro Discuss phase with at least 2 upvoted topics
- On 1 device, focus a card
- On the other device, as the facilitator, move to the next topic
- Notice that the editing was interrupted for the other user. Also, when you go back it left the card in a false editing state.

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
- During the discussion phase: users can keep jamming on their task card content even if the facilitator moves forward in the new meeting type. The user has to move forward to rejoin via nav or big floaty button.

### PR DESCRIPTION
**Pull request by mattkrick**
TEST

- progress to the discussion phase of a retro meeting
- on 1 device, the non-facilitator start typing a task in the discussion phase
- on another device, the facilitator progresses the meeting
- [ ] the non-facilitator stays on the page and does not get interrupted

EXTRA (for devs)
- [ ] run `yarn flowgen` the schema.flow.js file is not changed so you no longer commit that file with no changes @ackernaut

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1

- progress to the discussion phase of a retro meeting
- on 1 device, the non-facilitator start typing a task in the discussion phase
- on another device, the facilitator progresses the meeting
- [ ] the non-facilitator stays on the page and does not get interrupted

EXTRA (for devs)
- [ ] run `yarn flowgen` the schema.flow.js file is not changed so you no longer commit that file with no changes @ackernaut 

## Notes

### JWT Malformed

I've got an oddness going on while testing on my local environment – and I feel uncomfortable pushing to staging until I resolve it. Here are my steps:

- Create 2 new users accounts `User A` and `User B`
- Invite `User B` to `User A`'s team
- Start a Retro meeting, following error:

```
UnauthorizedError: jwt malformed
    at /Users/jordanhusney/Source/github/Parabol/action.git/node_modules/express-jwt/lib/index.js:102:22
    at /Users/jordanhusney/Source/github/Parabol/action.git/node_modules/jsonwebtoken/verify.js:27:18
    at process._tickCallback (internal/process/next_tick.js:176:11)
UnauthorizedError: jwt malformed
    at /Users/jordanhusney/Source/github/Parabol/action.git/node_modules/express-jwt/lib/index.js:102:22
    at /Users/jordanhusney/Source/github/Parabol/action.git/node_modules/jsonwebtoken/verify.js:27:18
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

**Comment by jordanh** [comment]
# Test Cycle 2

### Notes

Using the same repro steps as above, I'm not getting a different exception. This time, it's clientside:

image

**Comment by mattkrick** [comment]
all fixed!

**Comment by mattkrick** [comment]
tested on dev server, works like a charm, gonna merge

**Pull request merged**
