### PR TITLE
Refactor action meeting Part 1: NewMeeting -> RetroMeeting [WIP]

### PR DESCRIPTION
**Pull request by mattkrick**
Since this refactor job is gonna be so gosh darn huge, I figured it'd be good to break it into chunks. I'll try to keep each chunk around ~50 files,.

overall approach:
- put as much logic into hooks as possible. I try to treat them like controllers in the old MVC pattern. They're nice because I can share that logic between Retro and Action Meetings without HOCs.
- Make each phase load lazy. We can use an `afterPageLoad` pattern if that's too slow. This will get better when relay  releases the `@module` directive
- Maintain a single query per meeting

TEST
- [ ] pressing the right arrow during checkin checks a person in & moves them forward
- [ ] visiting other meeting phases ( and invalid ones!) by using the url bar works
- [ ] standard navigation works

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review! if everything works right, then nothing should have changed

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] pressing the right arrow during checkin checks a person in & moves them forward
- [ ] visiting other meeting phases ( and invalid ones!) by using the url bar works
- [ ] standard navigation works

**Comment by ackernaut** [comment]
@mattkrick 
- The facilitator sees the dev error message during the check-in in the content space, the other player sees the check-in content
```
TypeError: Cannot destructure property `preferredName` of 'undefined' or 'null'.
    at CheckInControls (CheckInControls.tsx:35)
```
- Pressing arrow works, but doesn’t mark teammate as here
- All nav seems to work, URLs seem to work
- See a warning in agenda
```
index.js:3740 Warning: RelayModernRecord: Invalid record update, expected both versions of record `client:root:agendaItemSubscription(teamId:"jIm6S6mfy")` to have the same `__typename` but got conflicting types `MoveMeetingPayload` and `AddAgendaItemPayload`. The GraphQL server likely violated the globally unique id requirement by returning the same id for different objects.
```

**Comment by ackernaut** [comment]
### Test No. 2
- [ ] pressing the right arrow during checkin checks a person in & moves them forward
- [ ] visiting other meeting phases ( and invalid ones!) by using the url bar works
- [ ] standard navigation works

**Comment by ackernaut** [comment]
I’m still seeing this error:
```
TypeError: Cannot destructure property `preferredName` of 'undefined' or 'null'.
    at CheckInControls (CheckInControls.tsx:35)
```
Steps:
1. Sign in as 2 users locally
2. User 1 is facilitator and sees an error during Check-In, User 2 is participant and does not see an error during Check-In

I did pull down latest.

**Comment by mattkrick** [comment]
closing in favor of refactor-action-2

**Pull request closed without merging**
