### PR TITLE
Add grouping grid

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- start a meeting in 2 browsers
- create 20 cards, go to grouping phase

BASIC ACTIONS
- [ ] client A can pick up a card, client B sees it picked up by client A
- [ ] client A can release a card & it animates home for both client A & B
- [ ] client A can drag a card onto another one to form a group, client B sees it
- [ ] client A can repeat the above step quickly
- [ ] client A can ungroup 2 cards from the group quickly and client B sees 2 cards controlled by client A being ungrouped
- [ ]  client A can regroup the cards

MODAL BEHAVIOR
- [ ] client A can click the group & see the modal open
- [ ] client A can ungroup from the modal
- [ ] client B can regroup the cards
- [ ] client A can open the modal that client B just created
- [ ] with the modal open on client A, client B can drag a card into the group. the modal grows to accept the addition
- [ ] client B can remove a card from the modal, the modal shrinks

WINDOW BEHAVIOR
- [ ] client A can resize the window. the cards rearrange themselves
- [ ] client A can select a card on the top & drag & scroll it to the bottom
- [ ] client A can use a browser other than chrome to drag

AUTO GROUP BEHAVIOR
- [ ] client A can click auto group & the cards fall into groups

VOTING
- [ ] client A can progress the meeting to the voting phase
- [ ] client A can expand the modal & vote from the modal

### CODE REVIEW

**Comment by mattkrick** [comment]
Burndown
- [ ] voteCount on reflectionGruops when moving to discuss phase for subscribers
- [ ] box shadows on the undercard stack
- [ ] handle end drag event when it doesn't arrive
- [ ] jordan had 9 groups, when the meeting moved to vote, he had 8
- [ ] scrolling body is broken

**Comment by mattkrick** [comment]
@ackernaut @jordanh ready for another test! see burndown for changes

**Comment by mattkrick** [comment]
we'll still need to do some testing for ultra-edge cases (like both of us start & end a drag before either sees the other starting a drag), but i think this is good for another test. 

changes:
- [ ] use non-determinate ID for each dragContext. relay was storing the cached version & reusing it at inopportune times
- [ ] fixed a bug in my relay PR that shared sinks between committed updates & applied updates, resulting in wonky behavior
- [ ] put a 1 second timer on network requests to verify that all actions can support high latency

**Comment by jordanh** [comment]
Tested with @mattkrick – merging!

**Pull request merged**
