### PR TITLE
add spellcheck for tasks, reflections, and check-in question

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] reflections show red squiggle for spelling errors
- [ ] and tasks
- [ ] and check-in questions

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- [ ] reflections show red squiggle for spelling errors
- [ ] and tasks
- [ ] and check-in questions

## Notes

This PR didn't look to drafty to me, so I went ahead and tested it.

**Comment by jordanh** [comment]
LGTM!

**Comment by jordanh** [comment]
Merge when ready (honoring the draft status of this PR)

**Comment by mattkrick** [comment]
oh feel free to merge a draft PR. i just do that so i don't accidentally merge something before the base branch is master.

**Pull request merged**
