### PR TITLE
support multi-meetings

### PR DESCRIPTION
**Pull request by mattkrick**
Before, 1 team had 1 active meeting.
Now, a team can have a bunch.
But we don't allow that (yet)

This is actually a lot simpler now because a meeting is guaranteed when you hit the meeting route.

TEST
- [ ] massInvitation - accept a mass invite (invite link) when a meeting is running. it takes you to that meeting. accept one when a meeting is not running, it still works.
- [ ] verifiedInvitation - same as above, but with a personal invite to an email address
- [ ] pushInvitation - Browser A starts an Action meeting, Browser B goes to that meeting url & sees the invitation-required link. Browser A clicks "Accept" on the toast that popped up. Browser B is teleported to the meeting. Browser A navigates to the check-in stage of Browser B. Browser B goes to team dash & leaves team. Browser A's meeting is advanced to the next phase. 
- [ ] create a task for a user in the meeting with you, they don't get an involvement notification
- [ ] create a task for a user not in the meeting with you. they do get a notification.
- [ ] everything in a retro meeting works (notice the new url)
- [ ] everything in an action meeting works
- [ ] the meeting lobbies no longer have a sidebar (since a sidebar is calculated after a meeting is created, this would be a lot of work to refactor. it'll be gone soon)
- [ ] get kicked off the team while in a meeting. you get redirected
- [ ] get kicked out of the org while in a meeting. you get redirected
- [ ] start a meeting while on the master branch. then upgrade to this branch & migrate. nothing breaks & you're migrated gracefully-ish (nothing really works, but a refresh fixes it all)

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review!

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [ ] massInvitation - accept a mass invite (invite link) when a meeting is running. it takes you to that meeting. accept one when a meeting is not running, it still works.
- [ ] verifiedInvitation - same as above, but with a personal invite to an email address
- [ ] pushInvitation - Browser A starts an Action meeting, Browser B goes to that meeting url & sees the invitation-required link. Browser A clicks "Accept" on the toast that popped up. Browser B is teleported to the meeting. Browser A navigates to the check-in stage of Browser B. Browser B goes to team dash & leaves team. Browser A's meeting is advanced to the next phase. 
- [ ] create a task for a user in the meeting with you, they don't get an involvement notification
- [ ] create a task for a user not in the meeting with you. they do get a notification.
- [ ] everything in a retro meeting works (notice the new url)
- [ ] everything in an action meeting works
- [ ] the meeting lobbies no longer have a sidebar (since a sidebar is calculated after a meeting is created, this would be a lot of work to refactor. it'll be gone soon)

**Comment by ackernaut** [comment]
@mattkrick I’m seeing a few issues on this PR, and I’ve outlined them above. I wonder if any of this is just the local environment. Lately I get loading screens that hang up, and sometimes realtime feedback doesn’t work but then resumes when I refresh the browser.

**Comment by ackernaut** [comment]
### Reflection dialog disappears
- [ ] Write some reflections
- [ ] Group 2 reflections
- [ ] Delete 1 of the grouped reflections
- [ ] The dialog disappears and you can’t see the other reflection in the column
- [ ] Refresh the browser, the other reflection that wasn’t deleted is in the column

**Comment by mattkrick** [comment]
> Fatal error when creating a new team

fixed

> Push invitation hangs up

i think this is an error that only exists on local dev, flagging to be sure to test on staging!

> Got the involvement snackbar when both users were in meeting

fixed

> Publishing card in Action Agenda to GitHub failed

i think this is fixed, i fixed a lot of stuff, but i couldn't reproduce

> Error when dragging reflection in group, multiplayer

fixed

> Reflection dialog disappears

in progress

**Comment by mattkrick** [comment]
ready to kick them tires on staging

**Pull request merged**
