### PR TITLE
clean up completed phases

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] when on a slow connection, during reflection no double animation when the reflection is submitted (trust me on this one, or put a sleep in the Atmosphere.js, it's commented out)
- [ ] in the reflect phase after it's complete, the header does not look clickable
- [ ] when on the discuss phase, going back & trying to vote/unvote pops a toast

### CODE REVIEW

**Comment by jordanh** [comment]
Is this ready for testing? (I assume so, b/c no [wip])

**Comment by jordanh** [comment]
# Test Cycle 1
- [ ] when on a slow connection, during reflection no double animation when the reflection is submitted (trust me on this one, or put a sleep in the Atmosphere.js, it's commented out)
- [ ] when on the discuss phase, going back & trying to vote/unvote pops a toast
- [ ] in the reflect phase after it's complete, the header does not look clickable

**Comment by mattkrick** [comment]
why yes it is!

**Comment by ackernaut** [comment]
Looking at this now…

**Comment by ackernaut** [comment]
###Test Cycle No. 2
- [ ] when on a slow connection, during reflection no double animation when the reflection is submitted (trust me on this one, or put a sleep in the Atmosphere.js, it's commented out)
- [ ] when on the discuss phase, going back & trying to vote/unvote pops a toast
- [ ] in the reflect phase after it's complete, the header does not look clickable

**Comment by ackernaut** [comment]
Looks good 👍 definitely an improvement in the right direction

**Pull request merged**
