### PR TITLE
Retro card groups

### LINKED ISSUE #1729: Build Retro Card Groups
### Background

During the grouping phase of a retro, cards will be grouped. These groups will have titles.

### Acceptance Criteria
- Drag a card on top of another ungrouped card to form a group
- Drag a card on top of a grouped card to join that group
- Drag a card from a group to the flex space below to ungroup the card
- Dragging the 2nd to last card out of the group removes the grouping

### Proposal
During the entire grouping phase, I think it's easiest to let cards live as a peer entity to groups. After that phase, we may decide to turn single cards into 1-card groups. If we do this, we could use a heuristic to auto-summarize the card so the agenda items look OK.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1729.

## Testing

- Run the "drag and drop" story under "Reflection Card Grouping".
- Drag cards onto each other
- Click groups to expand/collapse
- Edit group titles
- Drag cards out of groups to "ungroup" them
- Note that when you drag the second-to-last out of a group, the group vanishes

Of note: in the demo, I'm not keeping track of the visual ordering of cards with respect to each other or the groups. So often when you group and/or ungroup, the group pops up in a place you wouldn't expect. This is intentional, as I wasn't sure if that work was in scope or not. There's evidently broader work that we'll need to prioritize regarding the more abstract "grouping page" or "grouping phase" in order to "catch" cards that are ungrouped, handle visual ordering/object constancy, etc.

### CODE REVIEW

**Comment by mattkrick** [comment]
I love it!
Couple things I'd like to clean up before a merge:
- When coming in from the top, a scrollbar appears on the drop target (this is likely linux-only, overflow: hidden fixes it)
- When coming from the top, the bottom margin goes away
- When coming from the bottom, the bottom margin goes away, then the top margin goes away
- when coming from the bottom with a 3rd card, the target cards quickly transition down, then when hovered off, they transition up

Here's a gif: 
 
funkydropbehavior

**Comment by dan-f** [comment]
Hey great, thanks for taking a look!

To address the margin issue - the reason you're seeing the card size change in the "collapsed" state is that all the cards have to have the same height in order to do the transform/scale computation at "react render" time e.g. without having references to actual DOM nodes for measurement. This enables the animation.

I do believe `overflow: hidden` will provide a better experience, good feedback!

As for that weird transition, I'll take a look and see what I can do! I was a bit confused by the react transition group package.

**Comment by mattkrick** [comment]
ah gotcha. here's a proposal: when someone hovers a card over the top of a card, drop it on top of the stack. it feels weird that it magically transports to the back of the stack. Then, for the card it's being dropped on, set the maxHeight to the drag target height (with overflow hidden).  this has 2 benefits:
- card stacks are just like programming stacks: last-in-first-out. in other words, the card that i just dropped on the stack is the most important card on the stack. 
- if i accidentally drop a card on a stack, i can quickly see where it went & quickly remove it.

also, it'll make coding much simpler since we won't have to worry about putting a shadow at the back of the stack. that would be very hard to support for multiplayer! if you & i are both dragging a card to a stack, if you get there first, even before you released the mouse to drop it, i should see your card.

**Comment by dan-f** [comment]
I think I see where you're coming from there with respect to card stacking. I worked off of the [figma wireframes](https://www.figma.com/file/ClYTi13FvvTZ2y03Om8wNrXq/Retro-Views?node-id=1%3A9) (check out the "Retro card states" page), which specified that cards should drop at the bottom of the stack. I think the idea behind this UX is that your'e usually dragging a card onto another card/group with which that card agrees thematically. In such a case, it could be awkward to replace the "top card" of the group, which sort of represents the history of that group. cc @ackernaut for his thoughts on that design.

**Comment by mattkrick** [comment]
oh for sure, you masterfully matched those wireframes! it didn't really hit me till i played with the DnD that it feels like the card is going _through_ the stack to appear at the bottom. it feels weird to have the card that i'm dragging on the top of the stack & then this gray card appear on the bottom of the stack. it's like i'm making a sandwich with 2 representations of the same card, all while the card is in its original location but faded out. so essentially, 1 card lives in 3 places when it's hovered over something. you mastered the engineering aspect of it! after seeing it though, i think we can make it simpler: we show where it is (in your hard) and we show where it's gonna go (either original location or some new stack, which we update on hover)

**Comment by dan-f** [comment]
Cool. I don't have the same tension with the current UX, but I think I understand where you're coming from! Before reimplementing to a new spec, I'd want @ackernaut to test this, since it'll give him a chance to validate his design.

**Comment by mattkrick** [comment]
understood, @ackernaut here are my proposed changes, as it relates to wireframes & this PR:
- [ ] When the card i'm dragging is hovered over a card group, remove the card from it's original location & put it on the top of the stack of the new location (same logic as how we drag cards today). Truncate the card beneath it to the height of the card being dropped with overflow:hidden.
- [ ] When i drop a card, do nothing, it's already where it should be! (same logic as how we drag cards today)

**Comment by ackernaut** [comment]
My suggestions to move forward:

1) I can totally see both ways (add new card to top of stack or bottom of expanded group VS. add new card to bottom of stack or top of expanded group) and have pondered UX of both. I consider this part to be complete according to design feedback cycles and the AC. Let’s create a new issue and prioritize changing the design and implementation for new cards to be added to the top of the stack. Otherwise, safe to try and move forward.

2) I think the top card of a stack should retain its own height (2 lines, 3 lines, etc.) and the other cards  underneath the top card can shrink to the height of 1 line while hidden. (Requires change, how hard?)

3) The outer, invisible box needs to collapse to the new height so that the card or group under it doesn’t have a large vertical space. Not sure if this is true or not in Storybook. (May require change, if so how hard?)

4) I say we keep the original location of the user because the purpose is to visually reinforce the multiplayer hints and reduce layout noise. I will see which cards others have grabbed in their original locations, and they will see the card I’ve grabbed in its original location. So the layout has less visual change and is more consistent across clients. So I consider this part complete!

Very nice work on this @dan-f and thanks for the keen eye on it @mattkrick .

**Comment by dan-f** [comment]
Thanks @ackernaut - replying to your last comment:

1. I agree.
2. I would like this as well. The cards in the middle of the stack need their height truncated to simplify the scaling/transform computation, but since the height of the last card doesn't influence any of the others, I think this should be doable! I'll take a look at this next.
3. I _think_ that this is a result of my use of CSS Grid in laying out the examples. Something about the height of the group expanding to the height of it's parent. If I'm correct, then there shouldn't be any action needed.
4. Good!

**Comment by dan-f** [comment]
@ackernaut - this now hits the following additional criteria:
- You can drag a card into an expanded retro group without auto-collapsing it
- Clicking anywhere in the expanded card stack collapses it

The following AC shall be added to #1745:
- When dragging cards out of retro groups, the "dragging" state is visible, including the user that is dragging

**Comment by ackernaut** [comment]
For #1745, I would clarify that when a card is being dragged out of a group, and that group is open for a user, that the user sees the original position MP indicator.

- I open a group, and grab a card, I see my 50% opacity with name.
- Another has the same group open, they see that I grab a card 100% opacity with name.
- Another has the same group closed, they don’t see the feedback.

**Comment by dan-f** [comment]
Excellent. I'll quote your comment directly on #1745 to avoid anything getting lost in translation :)

**Comment by ackernaut** [comment]
@dan-f 👏 this looks great, thanks for addressing those 2 points and capturing the AC for #1745 — ready to merge?

**Comment by ackernaut** [comment]
🚀

**Pull request merged**
