### PR TITLE
Slack personal

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] set up a slack integration before checking this branch out. check out branch & migrate db. the integration still exists & works
- [ ] going to /settings/integrations shows a slack row
- [ ] on the bottom of the slack row is a list of notifications & a dropdown box of channels they get sent to
- [ ] clicking a channel from the dropdown updates the channel for me
- [ ] when teammembers User A & User B are both on /settings/integrations & User A updates a channel, the update does not change the setting for User B
- [ ] the notifications work for Meeting Start, Meeting End
- [ ] Remove slack, then re-add it, un-toggle an event, then change the channel. the toggles stay put

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test
**Note**: running a test cycle before code changes for styles
- [ ] set up a slack integration before checking this branch out. check out branch & migrate db. the integration still exists & works
- [ ] going to /settings/integrations shows a slack row
- [ ] on the bottom of the slack row is a list of notifications & a dropdown box of channels they get sent to
- [ ] clicking a channel from the dropdown updates the channel for me
- [ ] when teammembers User A & User B are both on /settings/integrations & User A updates a channel, the update does not change the setting for User B
- [ ] Setting "No Channel" remove the slack notification
- [ ] the notifications work for Meeting Start, Meeting End
- [ ] Remove slack, then re-add it, un-toggle an event, then change the channel. the toggles stay put

**Comment by ackernaut** [comment]
@mattkrick a few things I’m seeing so far:
- when adding a second user, after selecting a channel in the Slack Oauth view, the channel says “No Channel” for that user
- when updating the channel with 1 of 2 users, the other user gets an error in browser console ```Captured error: RelayNetwork: No data returned for operation `TeamSubscription`, got error(s):
abstractType.resolveType is not a function```
- I didn’t see an option in the dropdown for “No Channel” once a channel has been selected
- for the last item, when I remove and re-add, un-toggle, then try to change channels, it collapses most of the time back to the unconnected state. Also, when I re-add and pick a channel, it says the previous channel, not the new one that I picked in Slack Oauth

I’ll start working on a small list of style updates.

**Comment by ackernaut** [comment]
### Style Checklist
- [ ] Row style for notification
- [ ] Switch updated to use MD styles
- [ ] Stretch: select dropdown styles updated
- [ ] Stretch: Figma concept upgraded for target

**Comment by jordanh** [comment]
Checked if this was ready to release, see some work still needs to be done. So, moving on!

**Comment by ackernaut** [comment]
@mattkrick ok, that’s about all I’m going to push on styles here in order to time-box this. A few notes:

- When I go back to the view, I have to pick a channel each time
- I don’t see an option to set the channel back to “No Channel Selected”

Basically 2 items that didn’t pass on the test above

**Comment by ackernaut** [comment]
Another note to add here @mattkrick I’ve figured out 1 nuance:

If you select a channel, but switch off the first notification “Meeting Start” then when you refresh the dropdown says “No Channel Set”. If you switch it back on you see the right channel. If you keep the first switch on but turn off the second switch “Meeting End” you still see the correct channel set.

**Comment by mattkrick** [comment]
good for another review!
note: you must change the slack client id & slack client secret to the dev credentials, found here: https://api.slack.com/apps/A4ZM70S93/distribute?

once our app gets approved, you can switch back to the public creds.

**Comment by ackernaut** [comment]
I will do another full test cycle, but I was still seeing the behavior [described above](https://github.com/ParabolInc/action/pull/2901#issuecomment-497514466) with a quick local test.

**Comment by ackernaut** [comment]
### Test Cycle No. 2
- [ ] set up a slack integration before checking this branch out. check out branch & migrate db. the integration still exists & works
- [ ] going to /settings/integrations shows a slack row
- [ ] on the bottom of the slack row is a list of notifications & a dropdown box of channels they get sent to
- [ ] clicking a channel from the dropdown updates the channel for me
- [ ] when teammembers User A & User B are both on /settings/integrations & User A updates a channel, the update does not change the setting for User B
- [ ] the notifications work for Meeting Start, Meeting End
- [ ] Remove slack, then re-add it, un-toggle an event, then change the channel. the toggles stay put

**Comment by ackernaut** [comment]
Currently stuck on the first test, seeing an error message in the settings UI and this in server console:
```
GraphQL request (11:3)
10: fragment ProviderList_viewer on User {
11:   providerMap(teamId: $teamId) {
      ^
12:     SlackIntegration {

    at Object.Field (/Users/terryacker/code/parabolinc/action/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:64:31)
    at Object.enter (/Users/terryacker/code/parabolinc/action/node_modules/graphql/language/visitor.js:334:29)
    at Object.enter (/Users/terryacker/code/parabolinc/action/node_modules/graphql/language/visitor.js:385:25)
    at visit (/Users/terryacker/code/parabolinc/action/node_modules/graphql/language/visitor.js:252:26)
    at validate (/Users/terryacker/code/parabolinc/action/node_modules/graphql/validation/validate.js:63:22)
    at graphql (/Users/terryacker/code/parabolinc/action/src/server/graphql/graphql.ts:52:30)
    at wsGraphQLHandler (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/wsGraphQLHandler.ts:28:24)
    at handleGraphQLTrebuchetRequest (/Users/terryacker/code/parabolinc/action/src/server/graphql/handleGraphQLTrebuchetRequest.ts:54:30) path: undefined, locations: [ { line: 11, column: 3 } ] }
```
Going to back up a step by migrating down, adding a new Slack integration (new user, team, etc.) on `master` then migrate again and see if it still works.

**Comment by ackernaut** [comment]
Seeing TS warnings:
```
WARNING in [at-loader] ./src/universal/utils/SlackClientManager.ts:17:11
    TS6196: 'IdentityResponse' is declared but never used.

WARNING in [at-loader] ./src/server/graphql/mutations/startNewMeeting.ts:14:46
    TS6133: 'ITeamMember' is declared but its value is never read.
```

**Comment by ackernaut** [comment]
Okie dokie, so the closest I get so far to testing again is to be able to log in and see the error above under Team Settings, or the app doesn’t work (depending on how I go back and up with commits and migrations #2939.

If I can create a user on master and migrate on this branch, I don’t see that it works without the error above.

Also, a strange thing I’m seeing (could be the weird state) is that the meeting notifications didn’t show until I added a second team, on master.

I can’t say that there isn’t some user error (on my part) when testing this branch but @jordanh did experience the same issue #2939 when starting a database from initial state.

**Comment by mattkrick** [comment]
fixed, but after running `yarn relay` on `slack-personal` you'll need to run `yarn postdeploy`.

**Comment by mattkrick** [comment]
ready for another test!

steps to test migration:
- on slack-personal, run `db:migrate-down` if db is ahead of the `queryMap` migration
- checkout master
- run `r.table('QueryMap').delete()` on master
- run `yarn build:relay && yarn postdeploy`
- create a new account, link slack
- checkout slack-personal, run `yarn build:relay && yarn postdeploy`
- [ ] the integrations page looks as it should

@ackernaut

**Comment by ackernaut** [comment]
Looking at this now…

**Comment by ackernaut** [comment]
### Test No. 3
- [ ] set up a slack integration before checking this branch out. check out branch & migrate db. the integration still exists & works
- [ ] going to /settings/integrations shows a slack row
- [ ] on the bottom of the slack row is a list of notifications & a dropdown box of channels they get sent to
- [ ] clicking a channel from the dropdown updates the channel for me
- [ ] when teammembers User A & User B are both on /settings/integrations & User A updates a channel, the update does not change the setting for User B
- [ ] the notifications work for Meeting Start, Meeting End
- [ ] Remove slack, then re-add it, un-toggle an event, then change the channel. the toggles stay put

**Comment by ackernaut** [comment]
@mattkrick I think this looks good, all the behaviors are there.
- I did see the weird “Channel Not Set” at first, but I couldn’t reproduce it later. I want to say it happened when I switched and migrated on the `slack-personal` branch and that was the first thing I tried. I’ll look for it again on `staging` or `development` since it seems to be hard to reproduce.
- I see this error (truncated) for player A or B when the other player changes their channel:
```
Captured error: RelayNetwork: No data returned for operation `TeamSubscription`, got error(s):
abstractType.resolveType is not a function

See the error `source` property for more information. at…

Uncaught TypeError: result.dispose is not a function at…
```

**Comment by mattkrick** [comment]
hmm, that error is usually caused by a bad hot module reload (changed code w/o refreshing the browser). should be fine, let's test more on staging

**Pull request merged**
