### PR TITLE
fix #1252, notice the menus can't be selected

### LINKED ISSUE #1252: fix several are editing bug

### PR DESCRIPTION
**Pull request by mattkrick**
already accidentally pushed this to prod. if only i could protect a branch from pushes so you must PR into it....

### CODE REVIEW

**Comment by mattkrick** [comment]
it:
- [ ] open 2 different windows to the same team dash. add a new card. the other window sees the NullCard (#1252)
- [ ] create a new card. change the owner & the status before adding text. the card does not go away.
- [ ] create a new card. type #private and hit enter. hit tab. the card turns yellow
- [ ] create a new card. open the status menu. click away from the card. the card goes away.
- [ ] open websocket tab in debugger. add text to the card & click away from it. notice only 1 update message is sent.

**Comment by mattkrick** [comment]
@jordanh this is ready for review! my goal is to get this & then #1256 merge by EOD & up on production because this bug is _nasty_.

**Comment by jordanh** [comment]
# Test Cycle 1
**Status**: in progress

## Tests
it:
- [ ] open 2 different windows to the same team dash. add a new card. the other window sees the NullCard (#1252)
- [ ] create a new card. change the owner & the status before adding text. the card does not go away.
- [ ] create a new card. type #private and hit enter. hit tab. the card turns yellow
- [ ] create a new card. open the status menu. click away from the card. the card goes away.
- [ ] open websocket tab in debugger. add text to the card & click away from it. notice only 1 update message is sent.

**Comment by jordanh** [comment]
Great work! All checked out.

**Pull request merged**
