### PR TITLE
Suggested Actions

### PR DESCRIPTION
**Pull request by mattkrick**
This is PR 1/5. It goes like this:
- **PR 1: Suggested Actions**
- PR 2: Remove welcome wizard
- PR 3: Timeline
- PR 4: what's new
- PR 5: tasks shortlist

TEST - Organic Onboard

- Create a new account
- [x] after create a new account, i land on `/me`
- [x] A team is created called 'name's team'
- [x] I can click the "Tasks" tab to to see a kanban board with a seeded task
- [x] I can click the "Timeline" tb to see my timeline
- [x] If i resize the timeline to be very narrow, the right drawer disappears
- [x] I see a suggested action to invite my team
- [x] when i click the CTA to invite them, the invite team modal pops up
- [x] if i successfully invite a team member, the inviteYourTeam suggested action goes away
- [x] when the invitee joins my team, i get a new CTA to run my first retro
- [x] if i click that, it takes me to the retro lobby
- [x] if i complete a retro, the suggested action goes away & is replaced with a "create new team" CTA
- [x] if i create a new team (or a new org!), the new team CTA goes away & is replaced with "run first action meeting"
- [x] if i complete an action meeting, that CTA goes away
- [x] deleting a team removes the CTAs for "invite my team" "try a retro" and "try action meeting"
- [x] dismissing the "create new team" CTA causes the "run action meeting" cta to show
- [x] dismissing "run action meeting" results in a nice fading & scaling animation

TEST - accept an invitation

- accept a team invitation as a new parabol user
- [x] after accepting the invitation, i land on /me
- [x] i see a suggested action to run a demo, when i click it, i go to the demo
- [x] when hitting the back button from the demo route, it goes back to /me after only 1 click
- [x] when i go back to /me i have a CTA to create a team
- [x] if i hit the X in the upper right, i can dismiss the CTA & then i see nothing

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review!

**Comment by ackernaut** [comment]
### Test No. 1

TEST - Organic Onboard

- Create a new account
- [ ] after create a new account, i land on `/me`
- [ ] A team is created called 'name's team'
- [ ] I can click the "Tasks" tab to to see a kanban board with a seeded task
- [ ] I can click the "Timeline" tb to see my timeline
- [ ] If i resize the timeline to be very narrow, the right drawer disappears
- [ ] I see a suggested action to invite my team
- [ ] when i click the CTA to invite them, the invite team modal pops up
- [ ] if i successfully invite a team member, the inviteYourTeam suggested action goes away
- [ ] when the invitee joins my team, i get a new CTA to run my first retro
- [ ] if i click that, it takes me to the retro lobby
- [ ] if i complete a retro, the suggested action goes away & is replaced with a "create new team" CTA
- [ ] if i create a new team (or a new org!), the new team CTA goes away & is replaced with "run first action meeting"
- [ ] if i complete an action meeting, that CTA goes away
- [ ] deleting a team removes the CTAs for "invite my team" "try a retro" and "try action meeting"
- [ ] dismissing the "create new team" CTA causes the "run action meeting" cta to show
- [ ] dismissing "run action meeting" results in a nice fading & scaling animation

TEST - accept an invitation

- accept a team invitation as a new parabol user
- [ ] after accepting the invitation, i land on /me
- [ ] i see a suggested action to run a demo, when i click it, i go to the demo
- [ ] when i go back to /me i have a CTA to create a team
- [ ] if i hit the X in the upper right, i can dismiss the CTA & then i see nothing

**Comment by ackernaut** [comment]
Seeing this when trying to accept the invite that was sent from the timeline CTA:

```
{ ReqlLogicError: Cannot call `branch` term with an even number of arguments in:
r.table("TeamMember").getAll("VzjnSHwYgO", {
    index: "teamId"
}).filter({
    isLead: true
}).nth(0)("userId").default("").do(function(var_22) {
    return r.branch(var_22, r.table("SuggestedAction").getAll(var_22, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        index: "userId"
        ^^^^^^^^^^^^^^^
    }).filter({
    ^^^^^^^^^^^
        type: "tryRetroMeeting"
        ^^^^^^^^^^^^^^^^^^^^^^^
    }).count().eq(0), var_22, null)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})

    at Connection._processResponse (/Users/terryacker/code/parabolinc/action/node_modules/rethinkdbdash/lib/connection.js:395:15)
    at Socket.<anonymous> (/Users/terryacker/code/parabolinc/action/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at Socket.emit (events.js:197:13)
    at Socket.EventEmitter.emit (domain.js:439:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
  message:
   'Cannot call `branch` term with an even number of arguments in:\nr.table("TeamMember").getAll("VzjnSHwYgO", {\n    index: "teamId"\n}).filter({\n    isLead: true\n}).nth(0)("userId").default("").do(function(var_22) {\n    return r.branch(var_22, r.table("SuggestedAction").getAll(var_22, {\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        index: "userId"\n        ^^^^^^^^^^^^^^^\n    }).filter({\n    ^^^^^^^^^^^\n        type: "tryRetroMeeting"\n        ^^^^^^^^^^^^^^^^^^^^^^^\n    }).count().eq(0), var_22, null)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n})\n',
  locations: [ { line: 5, column: 3 } ],
  path: [ 'acceptTeamInvitation' ] }
```

**Comment by mattkrick** [comment]
all fixed up, i tested the remaining items so it should be good to go. ready for the test to continue @ackernaut

**Comment by ackernaut** [comment]
👍 will pick back up, thanks!!

**Comment by ackernaut** [comment]
### Test No. 2

TEST - Organic Onboard

- Create a new account
- [x] after create a new account, i land on `/me`
- [x] A team is created called 'name's team'
- [x] I can click the "Tasks" tab to to see a kanban board with a seeded task
- [x] I can click the "Timeline" tb to see my timeline
- [x] If i resize the timeline to be very narrow, the right drawer disappears
- [x] I see a suggested action to invite my team
- [x] when i click the CTA to invite them, the invite team modal pops up
- [x] if i successfully invite a team member, the inviteYourTeam suggested action goes away
- [ ] when the invitee joins my team, i get a new CTA to run my first retro
- [ ] if i click that, it takes me to the retro lobby
- [ ] if i complete a retro, the suggested action goes away & is replaced with a "create new team" CTA
- [ ] if i create a new team (or a new org!), the new team CTA goes away & is replaced with "run first action meeting"
- [ ] if i complete an action meeting, that CTA goes away
- [ ] deleting a team removes the CTAs for "invite my team" "try a retro" and "try action meeting"
- [ ] dismissing the "create new team" CTA causes the "run action meeting" cta to show
- [ ] dismissing "run action meeting" results in a nice fading & scaling animation

TEST - accept an invitation

- accept a team invitation as a new parabol user
- [ ] after accepting the invitation, i land on /me
- [ ] i see a suggested action to run a demo, when i click it, i go to the demo
- [ ] when i go back to /me i have a CTA to create a team
- [ ] if i hit the X in the upper right, i can dismiss the CTA & then i see nothing

**Comment by ackernaut** [comment]
🔥

**Pull request merged**
