### PR TITLE
fixes #444

### LINKED ISSUE #444: Meeting layout broken for Chromebook
## Bug

Most notably, the agenda item list has unintended wrapping.

Other points made by @tayamueller are that the avatars are small and the copy is hard to read?
- **OS:** Chromebook (??)
- **Browser:** Chrome version??

screenshot 2016-10-25 at 10 17 25 am
- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**

### CODE REVIEW

**Comment by jordanh** [comment]
Is this ready for merge?

**Comment by ackernaut** [comment]
I’m going to test it one more time and then I’ll confirm!

**Comment by ackernaut** [comment]
@jordanh looks good on my copy of Chrome, Firefox and Safari —I spun up Chromium OS on Virtualbox to test the same properties using Web Inspector and it seemed to fix the broken, wrapping layout (I didn’t go looking for how to share my localhost with the vm).

**Comment by jordanh** [comment]
Let's do it!

**Pull request merged**
