### PR TITLE
RethinkDB moar typesafe + Notification menu

### LINKED ISSUE #3550: Anonymous task card present even when person is not online
This is a bug reported by a user.

The current logic is to show this card if there is no content on a card. So, if I user signs off & the card doesn't get automatically removed, it'll stick around.

AC
- [ ] if the card has no content & the user is offline & the user is not the viewer, hide it

Effort: 11 points

### PR DESCRIPTION
**Pull request by mattkrick**
While refactoring the Notification table i kept hitting errors because i was using an index that didn't exist or accessing a field that was no longer there.

So, I forked the rethinkdb driver typings to include a user-defined schema, basically giving us an ORM without the runtime penalty.

Doing so uncovered a LOT of little bugs: missing `updatedAt` fields, writing to fields that were no longer in use, etc.

Now, it's a LOT harder to write a bad rethinkdb query.

Business Logic:
- A notification has 3 states: UNREAD, READ, CLICKED. 
- The red dot appears on the notification bell when the viewer has at least 1 UNREAD notification. 
- READ is defined as being 90% visible in the viewport
- when they "read" the notification, the notification state gets set to READ.  
- if all notifications are read, then the red dot goes away on the bell
- the red dot stays present on read notifications until they re-open the menu
- if they click a notification, the background turns to white & the status changes to CLICKED
- a "mark all as read" button at the top of the menu may be good (even though it says read, it means clicked, we should only show 2 states to the user)
- the list starts with 5 notifications. as you scroll, 20 more load at a time until you finish.

TEST - SPECIFIC NOTIFICATIONS
- [ ] mention someone in a task (be sure they aren't on the same dashboard or in the same meeting or they won't get the notification) they get notification
- [ ] assign someone a task, they get notificaiton
- [ ] create a task, type some text, then assign to someone else. the other person does not see the Nullable card (fixes #3550)
- [ ] invite someone by email, they get notification
- [ ] promote that someone to billing leader, they get notification
- [ ] archive the team. they get a notification that the team was archived
- [ ] invite to another team, have them accept, then kick them out. they get a kicked out notification
- [ ] remove that person from the team. the team invitation stays, but they can't get back on the team with it
- [ ] remove that person from the org. the billing leader notification stays, but they can't get back to the org view
- [ ] start an async meeting that expires in 5 mins that doesn't notify via slack. then after the time is up, run `runScheduledJobs(seconds: 100)` on the private schema. you'll get a notification that the meeting time limit is up
- [ ] fail a payment by adding the following notification into the DB. the notification looks good
```
r.db('actionDevelopment')
.table('Notification')
  .insert({
    id: 'foobarx',
    userId: "google-oauth2|104933228229706489335",
    createdAt: new Date(),
    last4: '6666',
    orgId: 'v1quv24J8',
    type: 'PAYMENT_REJECTED',
    status: 'UNREAD'
  })
```

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for testing

**Comment by ackernaut** [comment]
## Test cycle no. 1
### Test specific notifications
- [ ] mention someone in a task (be sure they aren't on the same dashboard or in the same meeting or they won't get the notification) they get notification
- [ ] assign someone a task, they get notificaiton
- [ ] create a task, type some text, then assign to someone else. the other person does not see the Nullable card (fixes #3550)
- [ ] invite someone by email, they get notification
- [ ] promote that someone to billing leader, they get notification
- [ ] archive the team. they get a notification that the team was archived
- [ ] invite to another team, have them accept, then kick them out. they get a kicked out notification
- [ ] remove that person from the team. the team invitation stays, but they can't get back on the team with it
- [ ] remove that person from the org. the billing leader notification stays, but they can't get back to the org view
- [ ] start an async meeting that expires in 5 mins that doesn't notify via slack. then after the time is up, run `runScheduledJobs(seconds: 100)` on the private schema. you'll get a notification that the meeting time limit is up
- [ ] fail a payment by adding the following notification into the DB. the notification looks good
```
r.db('actionDevelopment')
.table('Notification')
  .insert({
    id: 'foobarx',
    userId: "google-oauth2|104933228229706489335",
    createdAt: new Date(),
    last4: '6666',
    orgId: 'v1quv24J8',
    type: 'PAYMENT_REJECTED',
    status: 'UNREAD'
  })
```

**Comment by ackernaut** [comment]
### Notes WIP
- I’m seeing the task assign/mention notification even when I’m on the same team dash context
- I had to hard refresh to see the kick-out notification and lose access to the team

**Comment by mattkrick** [comment]
> I’m seeing the task assign/mention notification even when I’m on the same team dash context

there was a bug in how this was calculated. if you first visit and leave a meeting before running the test does the problem resolve itself?

> Locally I have to hard refresh to see the kick-out notification and lose access to the team

fixed (when removed from org)

**Pull request merged**
