### PR TITLE
Redirect to original url after login

### PR DESCRIPTION
**Pull request by ndey96**
This PR addresses https://github.com/ParabolInc/action/issues/436

Test steps:
- npm run dev
- login
- start a meeting
- copy the url for the meeting
- log out during the meeting
- paste meeting url in browser
- log in
=> should be redirected to the meeting url you pasted

@mattkrick @jordanh @ackernaut

### CODE REVIEW

**Comment by ndey96** [comment]
Right now this redirects you to the correct meeting url... but the dashboard renders instead. If the page is refreshed then the meeting renders properly.

[Screen cap of whats happening](http://recordit.co/8obUaHm6Tz)

**Comment by mattkrick** [comment]
here's how i'd design the basic flow:
- refactor the login modal to be `(/:login)`. then, when you click the login button, the `props.params.login = 'login'`. Make it a boolean & based on that, you can call `showAuth0Lock`.
- in the `requireAuthAndRole` higher-order component, instead of redirecting back home, first set the current url as `nextUrl` in the redux auth reducer. Then, redirect to `/login`. that way, the user doesn't have to click the login button, the modal pops up automatically.
- upon a successful login, check for `auth.nextUrl` if it's non-null, the redirect to that url & set it to null. Most apps do this redirect by sticking a nextUrl query in the url itself, but i always thought that was ugly...

an extra test might be going to the graphiql route, which is for admin users only. trying to go there should redirect you to `/login` then you enter your credentials, it redirects you back to the admin route, sees that you have a token but the `rol` is wrong & then sends you back home.

**Comment by ndey96** [comment]
@mattkrick @jordanh @ackernaut ready for review :)

**Comment by jordanh** [comment]
## Test Plan

- [ ] Create new account, team, & login
- [ ] Copy new team URL, logout
- [ ] Paste team URL, login
- [ ] It should redirect to team URL after login
- [ ] Navigate to meeting lobby for team, copy URL, logout
- [ ] Paste meeting lobby URL, login
- [ ] It should redirect to meeting lobby

**Comment by jordanh** [comment]
So, even though your tests passed @ndey96 ... there were some hidden 🐛 s.

I was going to comment on the changes you made to the authDuck. You were modifying state, which in redux is a big 🚫 . So, your PR was working by _coincidence_. Once I fixed it, it stopped working because the dispatch functions (called from `render`) were doing as they should and causing the react components to try and re-render...but they can't...because they were already in the middle of rendering.

I had to refactor two of the components to apply these state transitions elsewhere. Stand by!

**Comment by jordanh** [comment]
## Test Plan

### User testing

- [ ] Create new account, team, & login
- [ ] Copy new team URL, logout
- [ ] Paste team URL, login
- [ ] It should redirect to team URL after login
- [ ] Navigate to meeting lobby for team, copy URL, logout
- [ ] Paste meeting lobby URL, login
- [ ] It should redirect to meeting lobby
- [ ] Logout, login, it should redirect as before to `/me`

### Unit testing

- [ ] All tests run by `npm run test` should pass

**Comment by jordanh** [comment]
Ok @ndey96 here's your mission: run the above test plan and fix all the unit tests. Once you're ready, this should be GTG.

**Comment by ndey96** [comment]
@jordanh @mattkrick Unit tests and test plan are passing 👍

**Comment by jordanh** [comment]
LGTM!

**Pull request merged**
