### PR TITLE
Remove legacy context & Persisted queries

### LINKED ISSUE #2475: migrate away from legacy context API
react 16.6 strict mode has deprecated legacy context API. we'll need to do something to do the same to prepare for v17

AC
- [ ] legacy context API is removed

effort: 11 points

### LINKED ISSUE #2597: Upgrade Relay to v2.0.0
Persisted queries finally landed in v2.0.0. 
However, there are a few things we need to do before:
- #2475, which is stuck on #2172
- Merge my PR into the new version

we'll finish #2172 in the next sprint so we can move forward

### LINKED ISSUE #2605: TypeError: this.atmosphere.getMasonry is not a function
https://sentry.io/parabol/action-production/issues/861598806/?referrer=github_plugin

```
TypeError: this.atmosphere.getMasonry is not a function
  at Object.StartDraggingReflectionMutation (/production/build/v3.2.0/app_ad2d5eae1d7e93d264c9.js:1:44558)
  at Z.pendingBotAction (/production/build/v3.2.0/app_ad2d5eae1d7e93d264c9.js:1:38824)
  at pendingBotTimeout.window.setTimeout (/production/build/v3.2.0/app_ad2d5eae1d7e93d264c9.js:1:38939)
  at o (/production/build/v3.2.0/vendors~app_c31a495c491190447885.js:107:8764)
```

### PR DESCRIPTION
**Pull request by mattkrick**
This broke a bunch of stuff. Namely, react-dnd, react-router, and relay.

TEST
- [ ] subscriptions work (eg have a meeting in 2 tabs)
- [ ] drag-n-drop works (drag cards around in a retro meeting, the work on the other tab)
- [ ] go back to team dash, the team dash alert modal shows up
- [ ] go to Organization members, the leave org modal looks OK
- [ ] in org members, the remove from org modal looks OK

fix #2475 
fix #2597 
fix #2605

### CODE REVIEW

**Comment by jordanh** [comment]
Is this one still in progress?

**Comment by mattkrick** [comment]
@jordanh just finished. the new relay introduced an error that pops up in CI though, so i'll need to use a custom relay-compiler to get it to pass tests. but the app code itself is ready to be tested

**Comment by mattkrick** [comment]
@jordanh ready to review!

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests

- [ ] subscriptions work (eg have a meeting in 2 tabs)
- [ ] drag-n-drop works (drag cards around in a retro meeting, the work on the other tab)
- [ ] go back to team dash, the team dash alert modal shows up
- [ ] go to Organization members, the leave org modal looks OK
- [ ] in org members, the remove from org modal looks OK

## Notes

**Comment by jordanh** [comment]
@mattkrick first test cycle complete!

**Comment by mattkrick** [comment]
fixed! @jordanh ready for another test

**Comment by jordanh** [comment]
# Test Cycle 2

## Tests

- [ ] subscriptions work (eg have a meeting in 2 tabs)
- [ ] drag-n-drop works (drag cards around in a retro meeting, the work on the other tab)
- [ ] go back to team dash, the team dash alert modal shows up
- [ ] go to Organization members, the leave org modal looks OK
- [ ] in org members, the remove from org modal looks OK
- [ ] can leave org
- [ ] create new team on new org

## Notes

**Comment by jordanh** [comment]
Just a TS warning to fix and this branch looks GTG!

**Pull request merged**
