### PR TITLE
Remove empty reflections

### LINKED ISSUE #2094: Card styling poor when stack gets thick
## Issue - Enhancement

When lots of cards are themed together during the retro grouping phase, they can take up so much vertical room that they bump into the card below.

image

This is important to fix because it looks like the last card is part of the group.

### Acceptance Criteria (optional)
Users can:
   - Margin is preserved even when six or more cards are stacked together

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #2097: Empty Reflections in Group Phase
@jordanh had an empty reflection in the group phase not sure how.
@jordanh can you tell me how to reproduce?

AC
- [ ] no empty reflections can make it to the group phase

Effort: 10.5

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- comment out ReflectionCard.js line 124 (RemoveReflectionMutation...)
- in browser 1, start a retro
- in browser 2, join that retro
- in browser 1, add 10 - 15 reflections with a couple words in each
- in browser 2, click "Add a reflection" but do not type anything
- in browser 1, navigate to the next phase
- [ ] both browsers go to the group phase & the empty reflection is not there (fixes #2097)
- [ ] group all the reflections except the bottom one. notice they don't overlap (fixes #2094)

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- comment out ReflectionCard.js line 124 (RemoveReflectionMutation...)
- in browser 1, start a retro
- in browser 2, join that retro
- in browser 1, add 10 - 15 reflections with a couple words in each
- in browser 2, click "Add a reflection" but do not type anything
- in browser 1, navigate to the next phase
- [ ] both browsers go to the group phase & the empty reflection is not there (fixes #2097)
- [ ] group all the reflections except the bottom one. notice they don't overlap (fixes #2094)

**Comment by mattkrick** [comment]
that is weird...
must be a browser thing?
lemme think up a new strategy...
screenshot from 2018-05-08 17-35-28

**Comment by mattkrick** [comment]
ok, fixed it to be pixel perfect, although a bit more computationally expensive

**Comment by jordanh** [comment]
# Test Cycle 2

## Tests
- comment out ReflectionCard.js line 124 (RemoveReflectionMutation...)
- in browser 1, start a retro
- in browser 2, join that retro
- in browser 1, add 10 - 15 reflections with a couple words in each
- in browser 2, click "Add a reflection" but do not type anything
- in browser 1, navigate to the next phase
- [x] both browsers go to the group phase & the empty reflection is not there (fixes #2097)
- [x] group all the reflections except the bottom one. notice they don't overlap (fixes #2094)

**Comment by jordanh** [comment]
Wunderbar!

**Pull request merged**
