### PR TITLE
New Type & Palette (WIP)

### LINKED ISSUE #1814: Style the team swapping menu trigger on cards
## Enhancement

Let’s make the styles consistent for the bottom left triggers (team vs owner) on cards.

### Acceptance Criteria
- The menu label is consistent on the bottom left of cards

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**
Addresses #1661 and #1766 

Fixes #1814 

### Test Criteria
As this touches all views, verify that no view is “visually broken” but remains usable and understandable (more polish to come in smaller issues).
- [ ] My Dash
- [ ] Team Dash
- [ ] Team Settings (Members)
- [ ] Team Settings (Integrations)
- [ ] Team Settings (Single Integration)
- [ ] Add New Team
- [ ] User Settings
- [ ] User Notifications
- [ ] User Orgs List
- [ ] Org Billing
- [ ] Org Members
- [ ] Meeting Views (advance through as facilitator)
- [ ] Meeting Views (take a look as 2nd participant, not the facilitator)
- [ ] Meeting Summary in Browser
- [ ] Meeting Summary Email
- [ ] Welcome Views
- [ ] Welcome Email
- [ ] Team Invite Email
- [ ] Notifications Email (hard to fake unless you play with the database locally)

### CODE REVIEW

**Comment by ackernaut** [comment]
There’s a version of the universe that looks significantly different than the current version of the universe. I’m painfully aware of remaining polish, but does anybody want to poke around on this branch? I’ve got latest up, but am looking to style Matt’s filter input for the team dash. @jordanh @mattkrick 

I’d look around and only point out what you love/hate, because I plan on capturing some smaller tasks to improve and polish.

**Comment by ackernaut** [comment]
Working to resolve the conflict with master now, and add styles for the search filter.

**Comment by jordanh** [comment]
@ackernaut I forgot to write a note that I tried this this weekend with Sasha and was 💣 blown away 💥 !

On a purely surface level, I think this is _more_ than safe to try aesthetically. You have made a lot of choices to ease our transition very well. Here are some things I looked for:

Cards:
- I can d&d cards
   - [x] across columns
   - [x] within columns
- The menu works, and I can assign cards to:
   - [x] people
   - [x] various statuses
- [x] I can add formatted text and it looks right
- [x] I can make a very long card, and drag it around

Dash:
- [x] dash breaks in the right spots when downsized
- [x] I can add enough agenda items that it requires scrolling, and that works

My Dash:
- looks and works as expected:
   - [x] filter by team
   - [x] agenda list absent

Meeting:
- [x] I can flow through an entire meeting
- [x] I can add enough agenda items that it requires scrolling, and that works


Various menus still look ok:
- [x] orgs
- [x] org billing
- [x] new team
- [x] notifications

I think this is safe to try!

**Comment by ackernaut** [comment]
Thank you @jordanh 🙏 and I like your list of tests!

**Pull request merged**
