### PR TITLE
Fix team member kickout sub error #1664

### PR DESCRIPTION
**Pull request by mattkrick**
fix team member kickout from team settings #1664
fix webpack hmr for ubuntu 16.04
fix UserSettings redirect for new users (undocumented)

### CODE REVIEW

**Comment by dan-f** [comment]
This is one way to handle it! I was also thinking that, since the root cause of this error is that the server responds with an unauthorized error, we could catch the error at the site at which it occurs. Taking a look at the `TeamRoot` component, for example, shows that it throws away its `error` argument in the `render` function, and doesn't subscribe to team removal events. If it were to redirect away on unauthorized errors, we could catch this error at the place in which it occurs, and the `TeamSettings` can continue to assume that the viewer is in fact a member of the team.

**Comment by mattkrick** [comment]
there's 2 things going on: 
- the unauth error
- you get removed from team so the viewerTeamMember isn't found & so the component barfs 

this fixes the latter, which is the only thing that impacted the UX.

the former has errors originating from the server, so on the client the best we could do is ignore the errors & not post em to the console. Alternatively, we could squelch the errors on the server. I opted for the former because squelching errors always makes me nervous, but you got a good point, it's not really an error. i'll tell the server to not send error messages if it's caused by someone being kicked off a team.

**Comment by dan-f** [comment]
These two cases:

> - the unauth error
> - you get removed from team so the viewerTeamMember isn't found & so the component barfs

...are caused by the same fact - that you're not on the team. What if we extract the `TeamRoot`'s `QueryRenderer`'s `render` function, and make it:

- Handle the auth error by redirecting you back to your dashboard
- Subscribe to the team member subscription, and redirect you to your dashboard when you're no longer on the team

That means that the team components lower down on the tree can assume that we're in fact still on the team.

On the error topic, I actually think that the server throwing errors is a good idea. The problem I see is that without HTTP status codes we should have some sort of sum type of errors so that components handling GraphQL errors can understand the kind of error which occurred.

**Comment by mattkrick** [comment]
in reactlandia a render function cannot (should not) trigger a side effect like a redirect, so we'd need to do that inside the rendered child element. Currently, i fixed it by rendering null & waiting for the event to redirect.
For sanity, it's much easier to act on events instead of trying to infer events from state. So, we can say, "if i get a kick out notification, redirect me". That's so much easier than listening to things in the team, team settings, and meeting components & redirecting when a prop has changed (and making sure that as the app grows we expand those listeners to other team-specific components!).

For errors, it depends what kind of error:
- GraphQL parsing/validation error: Equivalent to HTTP 400. if this happens, if means they are writing their own operation. we don't support that, so we don't need a UI for it. 
- Auth error inside a GraphQL resolve: Equivalent to HTTP 403. if this happens, if means they're trying to subscribe to something they don't have permission to. We don't support that, so we don't need a UI for it (in this case, since _our_ server is the one attempting this, it's not really an error on the client's behalf, so I'm now convinced that there's no need to tell the client)
- Validation/Resolution error inside the resolve: Equivalent to HTTP 200. An error is a valid response. The error is defined in the schema & can be used by the UI. See `src/server/graphql/types/AcceptTeamInviteEmailPayload.js` for an example.

**Comment by mattkrick** [comment]
oh man super interesting! router.location only achieves eventual consistency with router.history.location. we managed to catch it at a time before the 2 converged. We should either PR react-router or switch over the rest of our app to using history.location.pathname. i'll opt for the latter in a chore.

@dan-f ready to merge, let me know if it's fixed.

**Comment by dan-f** [comment]
Indeed, it is fixed.

**Pull request merged**
