### PR TITLE
fix small sentry bugs

### LINKED ISSUE #2527: Try removing attached pictures from email
The green download cloud doesn't show up as a pic to download. Maybe we can do that for the other icons? Let's investigate

AC
- [ ] try to remove attached icons

Effort 10.5

### LINKED ISSUE #2653: GraphQLError: 'to' parameter is not a valid address. please check documentation
https://sentry.io/parabol/action-production/issues/895788350/?referrer=github_plugin

```
GraphQLError: 'to' parameter is not a valid address. please check documentation
  File "app:///../../node_modules/mailgun-js/lib/request.js", line 301, in IncomingMessage.<anonymous>
    error = new Error(msg);
  File "events.js", line 202, in IncomingMessage.emit
  File "domain.js", line 439, in IncomingMessage.EventEmitter.emit
  File "_stream_readable.js", line 1129, in endReadableNT
  File "internal/process/next_tick.js", line 76, in processTicksAndRejections

GraphQLError: 'to' parameter is not a valid address. please check documentation
```

This is caused by a bad email address. In this particular instance, they forgot the tld (eg matt@parabol). technically, that _could_ be a valid email address. but it's not. we can't figure that out via regex, but mailgun will tell us.

AC
- [ ] when mailgun tells us the email address is bad, we send that message to the client

Effort: 11 points

### LINKED ISSUE #2656: Error: dataloader not found for wf0Vn1xQy, on NewMeeting
https://sentry.io/parabol/action-production/issues/897462681/?referrer=github_plugin

```
Error: dataloader not found for wf0Vn1xQy, on NewMeeting
  File "app:///utils/RethinkDataLoader.js", line 27, in keys.map.val
    sendToSentry(new Error(`dataloader not found for ${cacheKeyFn(val)}, on ${table}`), {
  ?, in Array.map
  File "app:///utils/RethinkDataLoader.js", line 23, in map
    return keys.map((val) => {
  File "app:///utils/RethinkDataLoader.js", line 289, in batchFn
    return normalizeRethinkDbResults(keys, 'id')(docs, this.authToken, table)

Error: dataloader not found for wf0Vn1xQy, on NewMeeting
```

Fix: on the Team object, before looking up newMeeting by meetingId, make sure that activeFacilitator does not exist so we are sure that the meetingId is a newMeetingId

AC
- [ ] no sentry bug

effort: 11 points

### LINKED ISSUE #2658: update slack logo
probably time to update the slack logo in our app

AC
- [ ] new slack logo used

Effort: 10.5

### PR DESCRIPTION
**Pull request by mattkrick**
TEST

- [ ] start a retro meeting, then navigate back to the dashboard. you don't see any console errors about a missing dataloader (fix #2656)
- [ ] Goto Team Settings>Integrations>Slack Integrations. The slack logo is updated (fix #2658)

Invitations (fix #2653)
- invite 2 invalid emails to the team that still pass the regex, eg `matt+1@parabol, matt+2@parabol`
- [ ] when you try to invite the 2 above, you get an error message
- change the emails to 1 valid & 1 invalid, eg`matt+1@parabol.co, matt+2@parabol` & submit
- [ ] the valid email disappears & the invalid one remains with an error message
- fix the last email eg `matt+2@parabol.co`
- [ ] when you submit, you see a success message including both emails

Emails (fix #2527)
- trigger an email to be sent to your email inbox (invitation, retro summary, etc)
- Goto Gmail>>Email>>3 vertical dots, "Show Original"
- [ ] all images are linked to the CDN
- [ ] SVG images that were uploaded after this PR (ie any SVG image you upload while testing) show correctly in the email

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review!

**Comment by ackernaut** [comment]
👀 looking now…

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] start a retro meeting, then navigate back to the dashboard. you don't see any console errors about a missing dataloader (fix #2656)
- [ ] Goto Team Settings>Integrations>Slack Integrations. The slack logo is updated (fix #2658)

Invitations (fix #2653)
- invite 2 invalid emails to the team that still pass the regex, eg `matt+1@parabol, matt+2@parabol`
- [ ] when you try to invite the 2 above, you get an error message
- change the emails to 1 valid & 1 invalid, eg`matt+1@parabol.co, matt+2@parabol` & submit
- [ ] the valid email disappears & the invalid one remains with an error message
- fix the last email eg `matt+2@parabol.co`
- [ ] when you submit, you see a success message including both emails

Emails (fix #2527)
- trigger an email to be sent to your email inbox (invitation, retro summary, etc)
- Goto Gmail>>Email>>3 vertical dots, "Show Original"
- [ ] all images are inlined for all emails sent via mailgun
- [ ] images are deduped (eg there is only 1 thumb_up icon)
- note: if an avatar is an SVG, it will appear as an attachment since gmail doesn't show svgs inline

**Comment by ackernaut** [comment]
I’m seeing attachments for both `.png` and `.jpeg` files. To reproduce, upload a profile avatar and run either meeting and look at the summary. In Gmail I see attachments, and can confirm with looking at “Show original” in the vertical ellipsis menu for the message.

**Comment by mattkrick** [comment]
oh you're so right. guess it depends on the gmail user's layout. gmail hides attachments that it can display inline once in the email, but also from the email list view it'll show a bunch. 

i suppose we should just make everything a link @jordanh FYI gonna revert strategies & just make every image a link instead of inlining everything so it looks cleaner in the inbox

**Comment by mattkrick** [comment]
OK, now all email images are coming from the CDN. @ackernaut ready for another test.

**Comment by ackernaut** [comment]
### Test No. 2
- [ ] start a retro meeting, then navigate back to the dashboard. you don't see any console errors about a missing dataloader (fix #2656)
- [ ] Goto Team Settings>Integrations>Slack Integrations. The slack logo is updated (fix #2658)

Invitations (fix #2653)
- invite 2 invalid emails to the team that still pass the regex, eg `matt+1@parabol, matt+2@parabol`
- [ ] when you try to invite the 2 above, you get an error message
- change the emails to 1 valid & 1 invalid, eg`matt+1@parabol.co, matt+2@parabol` & submit
- [ ] the valid email disappears & the invalid one remains with an error message
- fix the last email eg `matt+2@parabol.co`
- [ ] when you submit, you see a success message including both emails

Emails (fix #2527)
- trigger an email to be sent to your email inbox (invitation, retro summary, etc)
- Goto Gmail>>Email>>3 vertical dots, "Show Original"
- [ ] all images are inlined for all emails sent via mailgun
- [ ] images are deduped (eg there is only 1 thumb_up icon)
- note: if an avatar is an SVG, it will appear as an attachment since gmail doesn't show svgs inline

**Comment by mattkrick** [comment]
woooo! no more 100KB emails :smile:

**Comment by ackernaut** [comment]
🔥 nice work @mattkrick

**Pull request merged**
