### PR TITLE
Beautiful grouping

### PR DESCRIPTION
**Pull request by mattkrick**
TEST - REFLECT
- [ ] reflect phase works as before
- [ ] can press escape and blur a currently edited card
- [ ] can edit a card using the fallback (dev tools -> mobile view -> refresh)

TEST - GROUP
- [ ] can add a reflection
- [ ] can click a card to enter editing mode
- [ ] in editing mode, the group title appears
- [ ] in editing mode, can click the top card & edit the contents of the card if it is yours
- [ ] in editing mode, can delete
- [ ] can click outside the card to exit editing mode
- [ ] can drag a card 
- [ ] cards being remotely dragged show the Dragger tag 
- [ ] cards being remotely dragged off the screen show a Dragger tag + an arrow pointing in that direction
- [ ] card being remotely dragged in a scrollable column that is too low or too high to see shows a Dragger tag at the top/bottom of the column + arrow 
- [ ] cards dropped in a location in a scrollable column that is out of view fade out as they go away
- [ ] when a card is picked up, the rest of the stack animates up to fill the gap it left
- [ ] when a card is dropped on a stack, the rest of the stack animates down to make room for it
- [ ] when a single card is picked up, it's vertical space reduces to 0
- [ ] when a card group is expanded, it's vertical space reduces to 0
- [ ] cards in the expanded group have the same rules as single card stacks (click to enter editing mode, etc)
- [ ] remote cards in flight are relatively positioned to their prospective drop targets (ie the card i'm hovering is the card you see me hovering)
- [ ] can hold a card over the top/bottom of a scrollable column & see it scroll

TEST - GROUP MOBILE (dev tools -> mobile view -> refresh)
- [ ] can swipe across columns
- [ ] can use progress dots to navigate across columns
- [ ] when dragging a card, can hold it over the left or right side of the screen to navigate across columns
    
TEST - VOTE
- [ ] vote looks identical to group phase on desktop/mobile, but everything is readOnly

BURNDOWN
- [x] update group title when a card has been edited
- [x] Demo

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick one small nuance on the stacked group, when there are more than 3 the box-shadow begins to layer up and get pretty dark. Not sure if this is a feature or a bug, ha! Thoughts? Should we try to hide the extra box-shadow?
Screenshot 2019-09-19 13 04 40

**Comment by mattkrick** [comment]
@ackernaut yeah, in the past i got rid of the extra shadows, but seeing it again, i think it's kinda cool as it's a subtle way to should you there's a lot more than 3.

**Comment by jordanh** [comment]
# Test Cycle 1

TEST - REFLECT
- [ ] reflect phase works as before
- [ ] can press escape and blur a currently edited card
- [ ] can edit a card using the fallback (dev tools -> mobile view -> refresh)

TEST - GROUP
- [ ] can add a reflection
- [ ] can click a card to enter editing mode
- [ ] in editing mode, the group title appears
- [ ] in editing mode, can click the top card & edit the contents of the card if it is yours
- [ ] in editing mode, can delete
- [ ] can click outside the card to exit editing mode
- [ ] can drag a card 
- [ ] cards being remotely dragged show the Dragger tag 
- [ ] cards being remotely dragged off the screen show a Dragger tag + an arrow pointing in that direction
- [ ] card being remotely dragged in a scrollable column that is too low or too high to see shows a Dragger tag at the top/bottom of the column + arrow 
- [ ] cards dropped in a location in a scrollable column that is out of view fade out as they go away
- [ ] when a card is picked up, the rest of the stack animates up to fill the gap it left
- [ ] when a card is dropped on a stack, the rest of the stack animates down to make room for it
- [ ] when a single card is picked up, it's vertical space reduces to 0
- [ ] when a card group is expanded, it's vertical space reduces to 0
- [ ] cards in the expanded group have the same rules as single card stacks (click to enter editing mode, etc)
- [ ] remote cards in flight are relatively positioned to their prospective drop targets (ie the card i'm hovering is the card you see me hovering)
- [ ] can hold a card over the top/bottom of a scrollable column & see it scroll

TEST - GROUP MOBILE (dev tools -> mobile view -> refresh)
- [ ] can swipe across columns
- [ ] can use progress dots to navigate across columns
- [ ] when dragging a card, can hold it over the left or right side of the screen to navigate across columns
    
TEST - VOTE
- [ ] vote looks identical to group phase on desktop/mobile, but everything is readOnly


## Notes

**Comment by jordanh** [comment]
Test cycle complete!

**Comment by mattkrick** [comment]
> Single card titles should remain expanded?

fixed

> On mobile can use progress dots to navigate across columns, but must scroll

no way to test w/o an iphone. 

> When Topic AI fails, empty agenda name

you got steps for a repro? when AI fails, it should just grab the first word or 2. what did you type in to make it go blank?

**Comment by mattkrick** [comment]
@jordanh got a repro for the empty agenda name?

**Comment by jordanh** [comment]
> @jordanh got a repro for the empty agenda name?

@mattkrick I'm not sure, exactly. I really should have captured what the text of the card was that caused the topic-naming AI to bork. Perhaps try:

1) Suppress the topic-naming AI from returning a valid topic name by either having it return "" or raising an exception
2) When you click name give a topic name to a single card, note it's topic name is the default for the component: `Topic`
3) Note that the agenda is an empty string

**Pull request merged**
