### PR TITLE
Epic 7 Archive Squeeze

### PR DESCRIPTION
**Pull request by ackernaut**
This PR:

- [x] Shows cards that have been archived 14 days or less when on a Personal account.
- [x] Shows a CTA panel encouraging users on a Personal account to upgrade to a Pro account for full access to the archive.
- [x] The CTA panel shows how many cards are unaccessible.
- [ ] Tapping “Upgrade” in the CTA panel routes to the Billing view in the appropriate state TBD.
- [ ] Update CTA button with new `buttonSize` prop.
- [x] Link to new pricing page

Test plan TBD

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick this is at a point where you can take over when you want to…I need to move on to designing the updated Billing view and states…so we may just need to wait until then. I can address any more design feedback and iterations on this branch as needed. But the first pass is there.

**Comment by mattkrick** [comment]
@ackernaut 
what if the non-org leader sees the squeeze? Do they get an upgrade button? What does their squeeze look like?

What's the url for the pricing page?

Do we do anything different to the OrgBilling page when they land on it from clicking "Upgrade"?

**Comment by mattkrick** [comment]
Todo for @ackernaut:
- [ ] link to pricing page in the squeeze
- [ ] design the squeeze to accomodate for a non-billing leader
- [ ] review new paginated archive & adjust styles

todo for matt:
- [ ] wire up subscriptions for archive
- [ ] verify squeeze for personal accounts
- [ ] feed isBillingLeader to the squeeze
- [ ] write tests

**Comment by ackernaut** [comment]
Hi 👋  @mattkrick 

Good update with the checklists! A few things:

- I took a look at what options are available with React Virtualized. Not sure that there is much in terms of responsive (which is out of scope anyway), so I’m gonna go on our smallest scoped browser window size (1280w). I made a first pass based on that.
- I liked how we had the grid scroll while the app header and nav stayed fixed. I may take a second pass and see if that is an option. Any reason why we couldn’t do that with RV? One of their examples showed this behavior.
- Re: squeeze for non-billing leader: I’m trying to remember what we did before with the trial message? Did we say “Email your Billing Leader?” and give an email? I think something along those lines is the best we can go with for now? Any opinion on dropping a name and/or email?

**Comment by mattkrick** [comment]
@ackernaut 
- responsive: i can do that, we just can't use media queries. if you write a pseudo media query (ie 4 cards until 1080, 5 cards untill 1400, etc) then I'll build that in. on my setup, 4 columns only fill about 2/3 of the white space & it looks awkward, so i think it'd be nice to get that in on the this first pass. 
- scrolling - if we do that, we'll need to use a scroll bar that is _not_ the window scrollbar. is that OK?
- i'd say email at a minimum, maybe email + name of the billing leader
- card width: on the other dashboards, the cad width is coming in at 264.5. I think we should standardize this across all card views so the line breaks are predictable.

**Comment by mattkrick** [comment]
tests:

Team Archive. Matt on browser 1, Jordan on browser 2.
- [ ] Jordan can unarchive a card & it is optimistically removed from the grid
- [ ] Jordan can unarchive a card & it is removed from matt's view
- [ ] If Jordan unarchives a private card, matt does not see that card (even in the websocket frame)

**Comment by ackernaut** [comment]
@mattkrick 

- re: responsive - It seems we can do fixed card widths plus fixed column counts? So yeah we could calculate that. There are nuances about the card with (next bullet).
- re: scrolling - I’m ok skipping for this pass. But a question: do we have to design/style the scrollbar?
- re: non-BL squeeze - I think “Contact your Billing Lead” as a link with the email is fine.
- re: card width. The card width varies depending on the window/display size, so I would defer trying to maintain a single width. The user dash has 4 columns. The team dash has 4 + 1 columns. The main content area for the columns can essentially be `window width - navbar width`. I think we try to sort out the archive based on the first bullet. Later, if we go very adaptive/responsive we probably won’t be able to do this. However we could probably normalize some max-widths per breakpoint where views are more consistent on a single device/display.

**Comment by ackernaut** [comment]
@mattkrick we only plan to show the squeeze if they are on the free plan and have cards older than 14 days? I’m seeing a squeeze for 0 cards.

screenshot 2017-10-17 12 13 55

**Comment by mattkrick** [comment]
todo
- [ ] adjust column count from comments
- [ ] 0 cards unavailable go away

**Comment by mattkrick** [comment]
@jordanh ready for :eyes:

**Comment by jordanh** [comment]
# Test Cycle Template
## Status: in progress/completed

Team Archive. Matt on browser 1, Jordan on browser 2, Jordan on browser 3.
- [ ] Jordan can unarchive a card & it is optimistically removed from the grid
- [ ] Jordan can unarchive a card & it is removed from matt's view
- [ ] If Jordan unarchives a private card, matt does not see that card (even in the websocket frame)
- [ ] If Jordan unarchives a private card in browser 2, it is removed on browser 3
- [ ] Matt archives a project. Jordan sees it update in his archive in real time
- [ ] user always has a tms when logging in/out/adding a team, etc. (secured tms on User doc)
- [ ] Jordan unarchives a card causing the following rows to change height. All cards keept their 8px border & it all looks like
- [ ] the number of columns changes based on the screen width _at load time_. (we don't have logic for screen resizes because archive will go away soon anyways)
- [ ] as a PERSONAL user, archive a card, notice that there is no squeeze below the archived cards grid
- [ ] go into the database for that PERSONAL user, change the archived card to have an `updatedAt` of `new Date(Date.now() - 6000000000)` (about 2 months prior). Refresh the archive. See the squeeze telling you you're missing out on a card.
- [ ] Jordan can unarchive the only card in the archive, it then shows empty state

## Notes on Test Cycle Results

**Comment by jordanh** [comment]
# Test Cycle 1
## Status: in progress

Team Archive. Matt on browser 1, Jordan on browser 2, Jordan on browser 3.
- [ ] Jordan can unarchive a card & it is optimistically removed from the grid
- [ ] Jordan can unarchive a card & it is removed from matt's view
- [ ] If Jordan unarchives a private card, matt does not see that card (even in the websocket frame)
- [ ] If Jordan unarchives a private card in browser 2, it is removed on browser 3
- [ ] Matt archives a project. Jordan sees it update in his archive in real time
- [ ] user always has a tms when logging in/out/adding a team, etc. (secured tms on User doc)
- [ ] Jordan unarchives a card causing the following rows to change height. All cards keept their 8px border & it all looks like
- [ ] the number of columns changes based on the screen width _at load time_. (we don't have logic for screen resizes because archive will go away soon anyways)
- [ ] as a PERSONAL user, archive a card, notice that there is no squeeze below the archived cards grid
- [ ] go into the database for that PERSONAL user, change the archived card to have an `updatedAt` of `new Date(Date.now() - 6000000000)` (about 2 months prior). Refresh the archive. See the squeeze telling you you're missing out on a card.
- [ ] Jordan can unarchive the only card in the archive, it then shows empty state

## Notes on Test Cycle Results

**Comment by jordanh** [comment]
Wowee! Awesome work team!

I only found one small bug. See the notes for *Test Cycle 1* above.

**Pull request merged**
