### PR TITLE
Redirect active meeting

### PR DESCRIPTION
**Pull request by ackernaut**
Addresses part of #2915
### Tests

This should handle 2 cases.

1) I’m at the lobby for one meetingType when the other meetingType starts
2) One meetingType is active, but I try to reach a URL for the other meetingType

#### Redirected to Action meeting
- [ ] With User A, go to Action lobby
- [ ] With User B, go to Retro lobby (and copy the URL)
- [ ] With User A, start the Action meeting
- [ ] User B is redirected from the Retro lobby to the Action meeting
- [ ] Advance to Solo Updates with User A
- [ ] With User B, paste the URL of the Retro meeting into the browser
- [ ] User B is redirected to the Action meeting
#### Redirected to Retro meeting
- [ ] With User A, go to Retro lobby
- [ ] With User B, go to Action lobby (and copy the URL)
- [ ] With User A, start the Retro meeting
- [ ] User B is redirected from the Action lobby to the Retro meeting
- [ ] Advance to Reflect with User A
- [ ] With User B, paste the URL of the Action meeting into the browser
- [ ] User B is redirected to the Retro meeting

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick this works but when pasting the URL in it loads pretty slowly so I imagine there’s a better way to handle this. In reality it should be an edge case where somebody uses a link for 1 meeting (from a calendar event or something outside our app UI) but the other meeting type is active. This is just a shortcut until we work out better multi-meeting architecture. What do you think?

**Comment by mattkrick** [comment]
can you do this all in a mounting effect in `useMeeting`? that would make it a little DRYer & then we wouldn't have to use that logic on every re-render.

**Comment by ackernaut** [comment]
@mattkrick thanks for that suggestion, I’ll look at that next

**Comment by ackernaut** [comment]
@mattkrick okie dokie, I made a second attempt at this. I’m not entirely sure that `setSafeRoute(true)` is necessary or should be `false` instead.

This should handle 2 cases.

1) I’m at the lobby for one meetingType when the other meetingType starts
2) One meetingType is active, but I try to reach a URL for the other meetingType

**Comment by ackernaut** [comment]
Also, there is a warning about the sidebar not cleaning up when un-mounting. Not sure if this is a regression or not:
```
VM18994 backend.js:6 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Relay(RetroMeetingSidebar) (created by ForwardRef(Relay(RetroMeetingSidebar)))
```

**Pull request merged**
