### PR TITLE
Refacto Action Meeting Summary (and remove old files)

### PR DESCRIPTION
**Pull request by mattkrick**
This wasn't a part of the sprint until I tried to blend the action meeting summary with the retro meeting summary. There was just too much old stuff with competing spacing rules that make it impossible to be sure that all email variants would have proper spacing.

Notes
- All sections end with a `<EmailBorderBottom/>` that adds a 24px bottom padding and a 1 pixel border. HRs should be avoided per email compat guidelines
- All sections begin with 24px padding-top. email compat guidelines say margins are unreliable
- use HTML4 attributes as much as possible, align, width, etc. the older the better when it comes to emails

TEST
- [ ] Summary looks good
- [ ] If meetingNumber === 1, it shows the GCal invite section
- [ ] Can click "Export to CSV" to get tasks and their associated agenda items. If the task was created in the updates phase, no agenda item is shown
- [ ] action/retro summary looks good in browser
- [ ] action/retro summary email look good on mobile 
  - [ ] footer is centered (although the "crafted with care" being off center made me smile more than it should)
  - [ ] "Present" is green for folks with tasks and without
  - [ ] QuickStats are all the same height
  - [ ] you don't get a weird too-purpley color for the text on gmail android
  - [ ] Cards looks good
  - [ ] spacing between sections is 24px above and below the HR

Changes
- Added SSR for relay components. That means no more rethinkdb super queries that break every time the code on the client breaks.
- flattened the table hierarchy. Almost all components are 1 or more `<tr>`s. flatter tree = less room for email clients to mess it up. plus this should eliminate the 100KB emails that we were sending
- use the same grid logic for avatars, tasks, and reflections: while minimizing the number of rows, minimize the number of empty cells. For example, if showing 5 avatars, use 3 on first row, 2 on 2nd, not 4 and 1.

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test No. 1

TEST
- [ ] Summary looks good
- [ ] If meetingNumber === 1, it shows the GCal invite section
- [ ] Can click "Export to CSV" to get tasks and their associated agenda items. If the task was created in the updates phase, no agenda item is shown
- [ ] action/retro summary looks good in browser
- [ ] action/retro summary email look good on mobile 
  - [ ] footer is centered (although the "crafted with care" being off center made me smile more than it should)
  - [ ] "Present" is green for folks with tasks and without
  - [ ] QuickStats are all the same height
  - [ ] you don't get a weird too-purpley color for the text on gmail android
  - [ ] Cards looks good
  - [ ] spacing between sections is 24px above and below the HR

**Comment by ackernaut** [comment]
@mattkrick this looks good, the only thing we need to do is make a choice about those icons for calendar:

Screenshot 2019-05-14 17 12 40
Screenshot 2019-05-14 17 12 52

I could make some new ones using our blue color.

**Comment by ackernaut** [comment]
The icon and the count need a margin, maybe 4 or 8px

Screenshot 2019-05-14 17 23 10

**Comment by mattkrick** [comment]
> this looks good, the only thing we need to do is make a choice about those icons for calendar

agreed, that blue is weird looking. i'd say let's use Google's colors for their icon & then whatever for the ics icon. we can do that later though.

> The icon and the count need a margin, maybe 4 or 8px

fixed!

**Comment by mattkrick** [comment]
merging to master, let's beat it up one more time on staging

**Pull request merged**
