### PR TITLE
Signup / Login view share fields

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] can login via oauth
- [ ] can sign up via oauth (delete user from auth0 & your local db for testing)
- [ ] can login via email/pass
- [ ] can sign up via email/pass
- [ ] can type email in signup view, switch to login view & keep the email & pass values the same
- [ ] can type email in login view, switch to forgot password view & email persists
- [ ] closing oauth window results in an error below the button
- [ ] wrong email/pass results in an error when logging in
- [ ] existing email/bad pass results in error when creating account
- [ ] existing email/matching pass when creating an account results in a login
- [ ] can login, logout, login again without error (there may be a warning about react not being able call set state, you can ignore that for now)

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] can login via oauth
- [ ] can sign up via oauth (delete user from auth0 & your local db for testing)
- [ ] can login via email/pass
- [ ] can sign up via email/pass
- [ ] can type email in signup view, switch to login view & keep the email & pass values the same
- [ ] can type email in login view, switch to forgot password view & email persists
- [ ] closing oauth window results in an error below the button
- [ ] wrong email/pass results in an error when logging in
- [ ] existing email/bad pass results in error when creating account
- [ ] existing email/matching pass when creating an account results in a login

**Comment by ackernaut** [comment]
@mattkrick this looks good, there is just one that I’m seeing locally.

When I login via oauth, sometimes the view doesn’t redirect from `/signin` to `/me` and it requires a hard refresh to do so. So I’m left staring at the signin view.

**Comment by mattkrick** [comment]
that's weird, let's test on dev or staging, i can't reproduce locally

**Comment by ackernaut** [comment]
I’ll try it on dev

**Comment by ackernaut** [comment]
@mattkrick I’m seeing the same behavior on the dev server.
1) I tap to log in via Google
2) The pop-up shows briefly then goes away
3) I’m still on the auth view, nothing happens but I can hard refresh and be at `/me`
I turned off the 1 privacy extension that I had running, and am allowing 3rd party cookies. That doesn’t mean I may be missing some other setting I’ve used in my browser, assuming any of that would cause the issue in the first place.

**Comment by ackernaut** [comment]
PS. Feel free to try it there since I’ve pushed this branch into that env.

**Pull request merged**
