### PR TITLE
zIndex scrubbed

### LINKED ISSUE #2772: audit zindexes
we've got a few competing zindexes in the app, we should standardize on em & ideally match z-index to elevation so things on top look like they're on top

AC
- [ ] all zindexes follow material design guidelines

effort: 11 points

### LINKED ISSUE #3295: Dragged reflections should be below the open dialog
Currently, in the group phase, dragged reflections hover over the group dialog when it’s open.

### AC
- Dragged cards are below the open dialog
- Dragging cards out of the dialog show up above the dialog

### EE
- 10.5 pts

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #3295 
Fixes #2772 

In a few cases there’s a difference between the visual elevation and the necessary z-index of the portal components since they sit on a different plane. Tooltips by spec are an elevation of 0 but must show above sidebars at 16 (invite button tooltip has to be above open agenda sidebar). Menus have a visual elevation of 8 but also must show above sidebars of 16 (user hub menu needs to open above mobile dash nav sidebar, change facilitator menu must show above mobile meeting left nav). Tooltips and menus are at a z-index of 24 like dialogs, but with the correct box-shadow or lack thereof.

### Test
- [ ] Browser windows side by side: with user 1, open a group dialog in the Group phase. With user 2, drag another card. The card should not fly above the open dialog in user 1’s view
- [ ] The facilitator’s bottom bar is above the content of a meeting phase/stage
- [ ] The sidebars are at the right elevation at both mobile and laptop breakpoints: dash left nav, team dash agenda sidebar, meeting left nav
- [ ] Menus are at the right elevation (showing above sidebars when “in” sidebars): card menus, help menus, sidebar menus, kanban filter menus, top/bottom bar menus (users, timer), select menus (new team form, integrations), etc.
- [ ] Dialogs are at the right elevation: invite, update avatar for me/org, member action confirmation dialogs, etc.
- [ ] Tooltips are at the right elevation (no shadow, but showing above sidebars, etc.): agenda input, phase column header, team invite button, copy URL, org member is only billing leader
- [ ] Drag and drop is at the right elevation: reflections cards, task cards, agenda items
- [ ] Snackbars are at the right elevation: meeting alerts, team alerts, timer gauge
- [ ] FABs are at the right elevation: help FAB, rejoin FAB

~My recommendation is to use a simple formula `MD elevation * 100` to allow for collisions, because it would be confusing to have to override a component and bump it up or down 1 if there was something else at the same elevation (e.g. 16 and 16, make one component 15 or 17 or change the order of the DOM?). Whereas `1600 + 10` gets us a 16.1 and with a comment might make for a more clear adjustment. Probably overly cautious.~

### CODE REVIEW

**Comment by mattkrick** [comment]
I'd say ditch the coefficient, if we allow for +/- 1 here and there then we'll get breaks in the future.
I'd say let's just use the MD spec where elevation matches the box Shadow and the zindex.

**Comment by ackernaut** [comment]
@mattkrick okay! ready

**Comment by mattkrick** [comment]
testing now

**Comment by mattkrick** [comment]
Screen Shot 2019-11-06 at 9 57 14 AM

i still get a foreign card floating above my dialog, but honestly i don't mind it. everything else in the code looks SO MUCH BETTER!

**Pull request merged**
