### PR TITLE
Pop toast when not allowed to advance meeting

### PR DESCRIPTION
**Pull request by ndey96**
This addresses https://github.com/ParabolInc/action/issues/392

If a meeting participant tries to advance the phase they get this toast:
screen shot 2017-03-13 at 1 32 15 am

@jordanh @mattkrick @ackernaut

### CODE REVIEW

**Comment by jordanh** [comment]
Hey awesome! We'll have a look.

**Comment by ndey96** [comment]
Feedback from checkin: remove next buttons rather than popping toast

I will do this^

**Comment by ndey96** [comment]
@jordanh @mattkrick @ackernaut This is ready for a review now :)

It should:
- [ ] hide the controls to advance the meeting if the participant can't use them
- [ ] add a "waiting for {facilitatorName} to advance the meeting" to agendaItems first call
- [ ] allow a participant to navigate through any part of the meeting that is before the meetingPhase and meetingPhaseItem (back in time)

**Comment by jordanh** [comment]
# Test plan

It should:
- [x] hide the controls to advance the meeting if the participant can't use them
- [x] add a "waiting for {facilitatorName} to advance the meeting" to agendaItems first call
- [x] allow a participant to navigate through any part of the meeting that is before the meetingPhase and meetingPhaseItem (back in time)

_Excellent_ work @ndey96.

**Pull request merged**
