### PR TITLE
Epic 7 New Team Form

### PR DESCRIPTION
**Pull request by ackernaut**
This PR includes:

- Updates to the New Team form.
- General updates to UI components: buttons, inputs, textareas, labels, etc.

Test Plan TBD

### CODE REVIEW

**Comment by dan-f** [comment]
My gut says that name-changing refactors shouldn't necessarily count towards a file count. The 50 file thing seems to me as a rough codification of an otherwise subjective feeling one gets when things grow too large.

My 2 cents: If you've got a PR with more than one atomic unit of value, and the size of the PR makes it difficult to review, then go ahead and separate those atomic deliverables into separate PRs. But if the size is large because the value necessitates a lot of changes, and there's no way around it, then it would actually be harmful to create multiple PRs, inventing modularity where otherwise there was none.

**Comment by mattkrick** [comment]
hey @ackernaut i adjusted the "whats an org" copy & made the button change based on radio button selection. Please review & then I think we're ready to test & merge!

**Comment by ackernaut** [comment]
@mattkrick taking a 👀  now

**Comment by mattkrick** [comment]
- [ ] i can go to /newteam and the "existing" option is preselected
- [ ] if i go to organizations & then click "add organization" it takes me to `/newteam/1` and the "new org" radio button is preselected
- [ ] changing the radio button disables the field for the other value
- [ ] i can create a new team on an existing org & it takes me to the new team dashboard
- [ ] i can create a new team on a new org & it takes me to the new team dashboard
- [ ] after creating a new org, i can navigate back to /newteam and that new org is in the dropdown

**Comment by ackernaut** [comment]
# Test Cycle No. 1 (TA)

/newteam

- [x] i can go to /newteam and the "existing" option is preselected
- [x] if i go to organizations & then click "add organization" it takes me to `/newteam/1` and the "new org" radio button is preselected
- [x] changing the radio button disables the field for the other value
- [x] i can create a new team on an existing org & it takes me to the new team dashboard
- [ ] i can create a new team on a new org & it takes me to the new team dashboard
- [x] after creating a new org, i can navigate back to /newteam and that new org is in the dropdown

@mattkrick when I create a new team on a new org, I just get loading ducks. I have to refresh the browser to see the new team. Might it be a local dev thing?

**Comment by mattkrick** [comment]
hey @ackernaut can you give this another test cycle? i only changed 1 line, so it should just be enough to check off that last box.

**Comment by ackernaut** [comment]
@mattkrick I’m still seeing ducks. Do I need to update schema with Relay or something along those lines?

**Comment by mattkrick** [comment]
nope, as long as you pulled the most recent version you should be OK

**Comment by mattkrick** [comment]
if it's repeatable can you do it with the console open & then after you see ducks go to network > websocket > frames and screenshot the most recent ~10 frames?

**Comment by ackernaut** [comment]
@mattkrick I’m not seeing any information for Web Sockets under Network. I can hop on video if ya want.

**Comment by jordanh** [comment]
# Test Cycle 1
## Status: in progress

### /newteam

- [ ] i can go to /newteam and the "existing" option is preselected
- [ ] if i go to organizations & then click "add organization" it takes me to `/newteam/1` and the "new org" radio button is preselected
- [ ] changing the radio button disables the field for the other value
- [ ] i can create a new team on an existing org & it takes me to the new team dashboard
- [ ] i can create a new team on a new org & it takes me to the new team dashboard
- [ ] after creating a new org, i can navigate back to /newteam and that new org is in the dropdown

**Comment by mattkrick** [comment]
we sure can, if i do it naively, anyone on a team, including an outside consultant, will be able to see 
- a count of how many people are in that org
- the billing leader
- the active statuses of every member in the org
- the payment plan & dates

is that OK? anything we want to hide from non-org leader? my only concern with showing all orgs instead of just owned orgs is that we're giving the average user a bunch of useless information that may be distracting.

**Comment by jordanh** [comment]
I was thinking of something perhaps a little simpler:

image

**Comment by ackernaut** [comment]
We should consider #1431 at some point in the future on the Orgs list view.

**Comment by mattkrick** [comment]
alrighty, you now see all orgs.
we might wanna add both buttons instead of replacing 1 button with the other, i can see a user saying "hey, how come i get different buttons for different orgs?" and i can see a billing admin saying "hey, i want to create a team, how come i can't do that?"

on the backend, i only locked down the orgUsers, everything else is accessible by anyone who is on a team under the org. if you'd like to lock down more fields, just let me know which ones. 

@jordanh ready for another test:

- [ ] from the Organizations page, i see all the orgs i'm a part of
- [ ] for orgs i own, i see a button to go to settings
- [ ] for the orgs i don't own, i see a button to create a new team
- [ ] if i click "new organization" it takes me to `/newteam` and the new org radio button is selected
- [ ] if i click "create new team" it takes me to `/newteam` and the existing org radio button is selected & the org is preselected
- [ ] if i click New Team from the sidebar, the existing org radio button is selected & the first org is selected

**Comment by mattkrick** [comment]
gonna have @dan-f do the final test so we can get this beast merged

**Comment by dan-f** [comment]
Sweet, here we go! All works as expected 🙌 

- [x] from the Organizations page, i see all the orgs i'm a part of
- [x] for orgs i own, i see a button to go to settings
- [x] for the orgs i don't own, i see a button to create a new team
- [x] if i click "new organization" it takes me to `/newteam` and the new org radio button is selected
- [x] if i click "create new team" it takes me to `/newteam` and the existing org radio button is selected & the org is preselected
- [x] if i click New Team from the sidebar, the existing org radio button is selected & the first org is selected

**Comment by ackernaut** [comment]
💥

**Pull request merged**
