### PR TITLE
fix group demo animations & discuss overflow

### PR DESCRIPTION
**Pull request by mattkrick**
there's a bug where the discuss task column doesn't scroll. this fixes that + smoothes out the demo animations during grouping. 

TEST
- [ ] demo grouping animations look OK
- [ ] can scroll a list of a bunch of tasks on a discuss topic

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review! if possible i'd like to get this into prod today

**Comment by ackernaut** [comment]
Looking now…

**Comment by ackernaut** [comment]
### Test No. 1
- [x] demo grouping animations look OK
- [x] can scroll a list of a bunch of tasks on a discuss topic

**Comment by mattkrick** [comment]
thank you!

**Pull request merged**
