### PR TITLE
Demo Bug Fixes

### PR DESCRIPTION
**Pull request by mattkrick**
First pass was to just get an active meeting menu out the door. Now we can make it a little nicer.

TEST
- [ ] User 1 & User 2 on same team. User 1 in a meeting, User 2 on the dash.
- [ ] User 2 looks at active meeting menu, User 1 changes meeting name, User 2 looks at active meeting menu, sees name change
-[ ] User 1 advances the meeting, User 2 sees the updated phase
 
Mobile header
- [ ] browser around the app in mobile view. the header has a good title (e.g. My Timeline, My Tasks, team name, etc)

bouncing next button
- [ ] go to reflect phase, wait 2 mins, see the button bounce. then add a timer for 1 min. it doesn't bounce until the timer runs out.
- [ ] go to group phase, wait 1 min, it bounces. add timer for 1 min, bounces after 1 min. group a card, it stops bouncing for 30 seconds.

DEMO
- [ ] do the demo, the robot avatars appear in the upper right
- [ ] add a timer, it works
- [ ] the grouping animations are a lot less janky
- [ ] group a couple cards, press escape to collapse. it works

### CODE REVIEW

**Comment by jordanh** [comment]
@mattkrick when running `yarn run dev` following `yarn && yarn build && yarn workspace parabol-server` I get:

```
 jordanhusney@Jordans-MBP-2  ~/Source/github/Parabol/action.git   meeting-menu-fix  yarn run dev
yarn run v1.21.1
$ yarn workspace parabol-server dev
$ node webpack/buildDll.js && node server.babel.js
buildDll.js: using cached DLL
buffer.js:313
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:313:9)
    at Object.<anonymous> (/Users/jordanhusney/Source/github/Parabol/action.git/packages/server/utils/getVerifiedAuthToken.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Module._compile (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/pirates/lib/index.js:99:24)
    at Module._compile (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at newLoader (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/pirates/lib/index.js:104:7)
    at newLoader (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/pirates/lib/index.js:104:7)
    at Object.newLoader [as .ts] (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jordanhusney/Source/github/Parabol/action.git/packages/server/utils/getReqAuth.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Module._compile (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/pirates/lib/index.js:99:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by mattkrick** [comment]
doh! forgot to mention you need to rename `AUTH0_CLIENT_SECRET` TO `SERVER_SECRET` in your `.env`

**Comment by ackernaut** [comment]
> doh! forgot to mention you need to rename `AUTH0_CLIENT_SECRET` TO `SERVER_SECRET` in your `.env`

Is this change in the devops repo as well?

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [ ] User 1 & User 2 on same team. User 1 in a meeting, User 2 on the dash.
- [ ] User 2 looks at active meeting menu, User 1 changes meeting name, User 2 looks at active meeting menu, sees name change
-[ ] User 1 advances the meeting, User 2 sees the updated phase
 
#### Mobile header
- [ ] browser around the app in mobile view. the header has a good title (e.g. My Timeline, My Tasks, team name, etc)

#### Bouncing next button
- [ ] go to reflect phase, wait 2 mins, see the button bounce. then add a timer for 1 min. it doesn't bounce until the timer runs out.
- [ ] go to group phase, wait 1 min, it bounces. add timer for 1 min, bounces after 1 min. group a card, it stops bouncing for 30 seconds.

#### Demo
- [ ] do the demo, the robot avatars appear in the upper right
- [ ] add a timer, it works
- [ ] the grouping animations are a lot less janky
- [ ] group a couple cards, press escape to collapse. it works

**Comment by ackernaut** [comment]
### Test cycle no. 1 notes:
#### Bouncing button
>go to group phase, wait 1 min, it bounces. add timer for 1 min, bounces after 1 min. group a card, it stops bouncing for 30 seconds.

The bouncing stops after dragging a card before using the timer. After using the timer, the button keeps bouncing even when you drag a card.

#### Reflection DnD
Sometimes the card doesn’t move when I drag. Something feels wrong because I have the drag cursor but nothing happens. It usually takes 2-3 tries to grab and move. Sometimes it moves on the first time. I wonder if the actual target and the wrapper that has the drag cursor are sharing the same box, but I don’t think this is the problem. This happens when I drag from the middle of the card, too.

**Comment by ackernaut** [comment]
@mattkrick see the comment above; going to merge, that edge case can be fixed in a patch commit

**Comment by mattkrick** [comment]
> Reflection DnD

can you repro reliably? if so let's first make sure it's not a regression in this PR & 2nd meet up in sync to figure it out, i thought we squashed this awhile ago

**Pull request merged**
