### PR TITLE
Sucrase

### PR DESCRIPTION
**Pull request by mattkrick**
sucrase is a babel alternative written in rust. they claim 20x faster. in reality, i'm only seeing 5x faster (because i still have to do a little work with babel) that's still huge. that means instead of 25 seconds to build the app in dev, it only takes 5 seconds.

there are a few things i had to adjust to get it to play nicely. maybe more later, but for now, i'm pretty happy with a 5x speedup for webpack builds.

### CODE REVIEW

**Comment by jordanh** [comment]
## Tests

- [ ] Can run `yarn build:relay` without error
- [ ] Can run `yarn run dev` and smoke test retro

**Comment by jordanh** [comment]
# Test Cycle 1 

## Tests

- [ ] ❌Can run `yarn build:relay` without error
- [ ] ❌Can run `yarn run dev` and smoke test retro

## Notes

```
~/Source/github/Parabol/action.git ⑂sucrase +  yarn build:relay
yarn run v1.15.2
$ yarn update-schema && yarn build:relay-unsafe
$ node ./src/server/utils/updateSchema.babel.js && yarn tsgen
/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/plugin-transform-typescript/lib/index.js:245
          throw path.buildCodeFrameError("Namespaces are not supported.");
          ^

SyntaxError: /Users/jordanhusney/Source/github/Parabol/action.git/src/universal/utils/githubQueries/createIssue.graphql.d.ts: Namespaces are not supported.
  1 | import {DocumentNode} from 'graphql-typed'
  2 | import {CreateIssueInput} from './types'
> 3 | export namespace CreateIssueMutationMutationPartialData {
    |        ^
  4 |   export interface CreateIssueIssueAssigneesNodes {
  5 |     __typename?: 'User' | null
  6 |     id?: string | null
    at File.buildCodeFrameError (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at PluginPass.TSModuleDeclaration (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/plugin-transform-typescript/lib/index.js:245:22)
    at newFn (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/Users/jordanhusney/Source/github/Parabol/action.git/node_modules/@babel/traverse/lib/index.js:76:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jordanh** [comment]
What should I try next? Feel like I must be doing something wrong here...

**Comment by mattkrick** [comment]
should be all fixed

**Pull request merged**
