### PR TITLE
Fix meta tag

### LINKED ISSUE #2509: Demo route meta overridden, default meta updated
### Jobs to Be Done

When I'm a search engine, I want to index the Parabol demo for what it is, so that folks can find it.

When I share a link to Parabol via Slack, I want the unrolled description to be relevant, so that it'll make me look smart and intrigue others to evaluate it

#### Default meta updated:

```Parabol is a free online retrospective tool featuring custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.```

#### Meta for `/retrospective-demo` updated:

```
Try Parabol without creating an account; a free online retrospective tool featuring custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.
```

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**
fix #2509

TEST
- [ ] meta name description is different for /retrospective-demo

### CODE REVIEW

**Comment by jordanh** [comment]
- [ ] going to check that this meta looks sharp when shared in Slack too

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- [ ] meta name description is different for /retrospective-demo 
- [ ] check that this meta looks sharp when shared in Slack too

## Notes

**Comment by mattkrick** [comment]
let's start fresh-- how many different meta tags do you want & for what pages? 
if you just want 1 for the landing page & 1 for the app, then we should just do that & scrap the top short tag.

**Comment by jordanh** [comment]
> let's start fresh-- how many different meta tags do you want & for what pages?
> if you just want 1 for the landing page & 1 for the app, then we should just do that & scrap the top short tag.

That's right, something like:

- [ ] helmet meta + description properties removed
- [ ] meta tag defined for `https://action.parabol.co/retrospective-demo`
- [ ] default meta tag defined for `https://action.parabol.co/(signin|create-account)` and all other app routes

**Comment by mattkrick** [comment]
sounds good
what's the desired meta for that 3rd checkbox?

**Comment by mattkrick** [comment]
@jordanh stuck on getting a description for the 3rd checkbox

**Comment by jordanh** [comment]
See updated design on #2509

**Comment by mattkrick** [comment]
updated!

**Pull request merged**
