### PR TITLE
don't listen to hotkeys while in inputs

### PR DESCRIPTION
**Pull request by mattkrick**

### CODE REVIEW

**Comment by mattkrick** [comment]
@jordanh not to be contrarian, but here's another strategy to attack it.

**Comment by jordanh** [comment]
You contrarian you 😉  I considered this approach – effectively not using HotKeys when the input field is focused. I considered some future use cases where we'd want to selectively enable and disable certain HotKeys. Extending stopCallback seemed a way to go.

What compelled you to go down this route?

**Comment by mattkrick** [comment]
The biggest reason is modularity. Imagine I add a new hotkeys for "-". I
now have to visit every single piece of middle ware and write a handler for
that key. For example, as is if we listen on inputs, what happens if the
user hits the right arrow accidentally? They probably didn't mean to
advance the meeting. My assumption is that if an input field is active,
they only want to work on the input.

Also, we eliminate race conditions. It's possible that a focus gets called
before blur. If both share the same hotkeys, then one may or may not
overwrite the other. That's what was happening when I had navigation
hotkeys in different phases. In this case, if 2 middlewares call blur and
focus on the same key press, it'll break and be hard to find. Modular code
shouldn't have to worry about middlewares written in other parts of the
codebase.

Third, I subjectively find it more declarative. I declare what I want to
happen on a keypress instead of what I don't want to happen.

Fourth, it makes things simpler :-).

Definitely open for a discussion on the topic!

On Nov 7, 2016 12:35 PM, "Jordan Husney" <notifications@github.com> wrote:

>

> You contrarian you 😉 I considered this approach – effectively not using
HotKeys when the input field is focused. I considered some future use cases
where we'd want to selectively enable and disable certain HotKeys.
Extending stopCallback seemed a way to go.
>
> What compelled you to go down this route?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/ParabolInc/action/pull/501#issuecomment-258954691>, or
mute the thread

**Comment by jordanh** [comment]
Hmm... Let's talk about it. I'm running into a meeting now – but mañana!

**Pull request merged**
