### PR TITLE
add basic snackbar

### PR DESCRIPTION
**Pull request by mattkrick**
Replaces toasts with snackbar. Also wires up push invitations.

TEST - Snackbar
- [ ] creating a new team pops a snackbar
- [ ] if the cursor is hovering over the snackbar, it doesn't get dismissed until its time is up & the mouse cursor is no longer over it
- [ ] clicking a snackbar dismisses it
- [ ] getting disconnected causes a snackbar (to test, shut down the server)
- [ ] reconnecting removes the disconnected snackbar
- [ ] snackbar looks good on mobile
- [ ] when snackbar appears where there is a FAB (e.g. in a meeting) it is closer to the top of the page than the FAB (test with promoting a meeting facilitator)

TEST - Push notification
- User A in Browser A is on the team dash for Team Foo, User B is a user, but not on Team Foo
- User B in Browser B navigates to the the team dash for team foo
- [ ] User B sees a "waiting for invitation" screen 
- [ ] User A sees a snackbar asking to accept/deny User B
- [ ] when User A clicks accept, User B is accepted onto the team

TEST - Denials (preventing spamming)
There are 2 measure to keep malicious users from attempting to join teams.
First, if I user gets denied from the same team 2 times, they no longer trigger a snackbar when attempting to visit that team dash.
Second, if a user gets denied from 3 different teams, they not longer trigger a snackbar for any team in the future
These values are reset every 30 days.

- User A sets up 4 new teams: 1,2,3,4
- repeat above steps for Team 1, but User A denies User B
- [ ] After User B was denied, they refresh the team dash page again. User A does NOT see a snackbar
- [ ] reject from teams 2 and 3
- [ ] When User B tries to go to Team 4, no snackbar is shown

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review! requires a db migration, a yarn install & a refresh of relay components.

**Comment by ackernaut** [comment]
thanks @mattkrick I’ll review today

**Comment by ackernaut** [comment]
## Testing Round No. 1
TEST - Snackbar
- [ ] creating a new team pops a snackbar
- [ ] if the cursor is hovering over the snackbar, it doesn't get dismissed until its time is up & the mouse cursor is no longer over it
- [ ] clicking a snackbar dismisses it
- [ ] getting disconnected causes a snackbar (to test, shut down the server)
- [ ] reconnecting removes the disconnected snackbar
- [ ] snackbar looks good on mobile
- [ ] when snackbar appears where there is a FAB (e.g. in a meeting) it is closer to the top of the page than the FAB (test with promoting a meeting facilitator)

TEST - Push notification
- User A in Browser A is on the team dash for Team Foo, User B is a user, but not on Team Foo
- User B in Browser B navigates to the the team dash for team foo
- [ ] User B sees a "waiting for invitation" screen 
- [ ] User A sees a snackbar asking to accept/deny User B
- [ ] when User A clicks accept, User B is accepted onto the team

TEST - Denials (preventing spamming)
There are 2 measure to keep malicious users from attempting to join teams.
First, if I user gets denied from the same team 2 times, they no longer trigger a snackbar when attempting to visit that team dash.
Second, if a user gets denied from 3 different teams, they not longer trigger a snackbar for any team in the future
These values are reset every 30 days.

- User A sets up 4 new teams: 1,2,3,4
- repeat above steps for Team 1, but User A denies User B
- [ ] After User B was denied, they refresh the team dash page again. User A does NOT see a snackbar
- [ ] reject from teams 2 and 3
- [ ] When User B tries to go to Team 4, no snackbar is shown

**Comment by ackernaut** [comment]
🔥 👾 👍

**Comment by 0508999687** [comment]
دعم ملي مبلغ تمويل

**Comment by 0508999687** [comment]
دعم ملي مبلغ تمويل

**Comment by 0508999687** [comment]
دعم ملي مبلغ تمويل

**Pull request merged**
