### PR TITLE
Add swipeable dash left nav [base: mass-invite]

### PR DESCRIPTION
**Pull request by mattkrick**
TEST in a browser with < 800 pixels width on /me with a scrollable list of timeline events:

- [ ] swiping from the left opens the left nav
- [ ] flinging it open works, too
- [ ] flinging it closed works
- [ ] slowly closing it to <55% open and then releasing also closes it
- [ ] pressing down on the left side of the screen makes the menu peek out
- [ ] scrolling when the menu is peeking out causes it to hide again
- [ ] when you click on a team in the left nav, the nav closes & it redirects to that team page
- [ ] if you have 20+ teams, you can still scroll through them without it triggering a close
- [ ] the body cannot scroll while the menu is open
- [ ] on a desktop, there is no change to the sidebar

OUT OF SCOPE
- [ ] mobile safari doesn't support drag to open, it tries to navigate backwards (i think, i don't know. i'd need an iphone to test). that means we probably need to show a hamburger, but i'm not doing that until we refactor all the dash headers to look the same. I'm OK with shipping it as is.

### CODE REVIEW

**Comment by ackernaut** [comment]
Glad to see this step in the right direction! I’d be happy to test this one @mattkrick, related I’m eager to make the minimal first pass of updating the IA and layout of the dashboard. This is a design activity first, and not sure how soon it’ll be prioritized. In the meantime, I try to chip away at targets like this when working on other prioritized objectives.

**Comment by mattkrick** [comment]
@ackernaut ready to test!

**Comment by ackernaut** [comment]
👀 looking at this now…

**Comment by ackernaut** [comment]
## Test No. 1
TEST in a browser with < 800 pixels width on /me with a scrollable list of timeline events:

- [ ] swiping from the left opens the left nav
- [ ] flinging it open works, too
- [ ] flinging it closed works
- [ ] slowly closing it to <55% open and then releasing also closes it
- [ ] pressing down on the left side of the screen makes the menu peek out
- [ ] scrolling when the menu is peeking out causes it to hide again
- [ ] when you click on a team in the left nav, the nav closes & it redirects to that team page
- [ ] if you have 20+ teams, you can still scroll through them without it triggering a close
- [ ] the body cannot scroll while the menu is open
- [ ] on a desktop, there is no change to the sidebar

OUT OF SCOPE
- [ ] mobile safari doesn't support drag to open, it tries to navigate backwards (i think, i don't know. i'd need an iphone to test). that means we probably need to show a hamburger, but i'm not doing that until we refactor all the dash headers to look the same. I'm OK with shipping it as is.

### Notes/Feedback

**Comment by mattkrick** [comment]
closing in favor of #3008

**Pull request closed without merging**
