### PR TITLE
Enhance agenda list

### PR DESCRIPTION
**Pull request by ackernaut**
For this first pass, the agenda list shows:

- Agenda items completed or not completed (without local or facilitator state)
- Where one is locally (whether completed or not)
- Where the facilitator is (whether completed or not)

It addresses a few gotchas across phases:

- Only shows the facilitator location if the facilitator is in that phase.
- Only shows the local state for agenda when one is in that phase, otherwise seeing local phase item in the progress bar

One current gotcha not addressed:

- The `facilitatorPhaseItem` doesn’t update when an agenda item is dragged before that item causing a local state for facilitator and a false facilitator location for all users. This is because the other phases don’t change the number of phase items. Suggestions:
  - We can create a separate `agendaFacilitatorPhaseItem` and refactor current changes OR
  - We can update `facilitatorPhaseItem` in the agenda phase.

Do we want to make the agenda list more linear?

- Do we want to allow folks to skip ahead? (maybe not, what is the purpose?)
- Do we want to allow folks to go back (I think so, they can add an additional task, or resume their card because of interrupting chicken UX bug)
- Do we want to allow the facilitator to skip ahead but treat that as a auto-resort (that item becomes the next item).
- Do we want to show completed history and styles in a linear fashion (ex: only 1-5 of 10 have been completed).
  - Cannot delete current or completed items.
  - Cannot drag incomplete item into the range of completed items.
  - Can only navigate back to them.

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick feels non-DRY to pass down the same props over and over (see current files changed)...do we hook in with a deeper container (say AgendaList container?)

**Comment by mattkrick** [comment]
yeah, i'd probably calculate `isFacilitatorPhase` on MeetingContainer & just pass that into the children.
I don't see the harm in showing the facilitator phase on agenda items when the client is on another phase.

**Comment by mattkrick** [comment]
can you give me some steps to reproduce the stuff that doesn't look good?

**Comment by ackernaut** [comment]
@mattkrick the only thing to reproduce is:

1. Start a meeting as facilitator.
2. Note that you are on agenda item 3 of 5.
3. Drag item 4 before agenda item 3.
4. You should see a facilitator location that isn’t accurate (because the number didn’t update) and you should see a local state for the agenda item you are on (dark colored agenda item—you should never see a local style as you are the facilitator).

**Comment by mattkrick** [comment]
ah gotcha. yep, that's a bug! we don't send an update to the server.

So let's roll with that same 3/5 scenario.

So let me see if I understand what you want:

The facilitatorPhaseItem and meetingPhaseItem is 3 of 5. 1 and 2 are done.
I'm the facilitator:
  - If i try to drag item 4 to item <= 3, it doesn't move
  - If I go to item 4, item 3 is marked completed
  - If i go to item 5, item 5 becomes item 4. item 3 is marked completed.

I'm not the facilitator
  - If i go to item 5, it stays item 5

**Comment by ackernaut** [comment]
@mattkrick I think that is true to what I was describing for the linear agenda progress. (ht to @jordanh for the idea) —does that sound like a good improvement to you? I'm not sure why regular participants need to skip ahead unless they were wanting to get a head-start on writing a card (which I’m not sure that is what we want, although I don’t like being too rigid).

**Comment by mattkrick** [comment]
@ackernaut try merging the agenda-fix branch into this. it disables dragging items <= current item and when the facilitator clicks on an item out of order, it sorts it so it becomes the next. Note that this means a team MUST visit every agenda item now!

**Comment by mattkrick** [comment]
imma take a crack at drying it up a bit, hold tight for 10 mins

**Comment by mattkrick** [comment]
ah shoot, ran outta time on refactoring AgendaItem.
For the general idea, i think we still wanna show where the facilitator is, regardless of what phase the client is on.
So, as long as the facilitator is on AGENDA_ITEMS, there should be something pink.
As for locally, if the localPhase === AGENDA_ITEMS, then make it black.
what we do for agendaPhaseItem we'll wanna do with the facilitatorPhase & localPhase. eg `localAgendaItem = localPhase === AGENDA_ITEMS && localPhaseItem`. We pass in those to the sidebar & as long as they aren't undefined, then we show their style.

**Comment by ackernaut** [comment]
I have it written so that it is like the progress bar. The local state is dark unless it is also where the facilitator is, then it is warm, overriding the dark style.

I had it right, in that agenda phase item was not affecting progress bar styles in other phases and vice versa (the phase item for a progress bar, during that phase, shouldn't cause a state in agenda, and if I am at a phase with progress bar, I shouldn't see facilitator phase item if the facilitator is in the agenda phase). But I'm sure any clean-up you are doing is spot on.

**Comment by mattkrick** [comment]
Test:
- [ ] If the facilitator clicks on an agenda item > meeting item + 1, it becomes meeting item + 1
- [ ] no one can drag an agenda item above the current meeting item
- [ ] the pink agenda item is where the facilitator is
- [ ] the black agenda item is where the client is (for non facilitators)
- [ ] if you are on updates/2 and go back to checkin, the progressbar does not show the facilitator on 2
- [ ] fix for segment `createdAt.getTime()` fixes #850

**Comment by mattkrick** [comment]
@jordanh ready for review

**Comment by jordanh** [comment]
I tried to beat this up _good_. There is one corner case I found:

1. Non-facilitators can drag the current item (pink, where the facilitator is) to the end of the list and take the meeting with them. Drag should be disabled for the current item for non-facilitators

Other than that, looks great! Fix, I'll verify, then let's merge and ship!

**Comment by ackernaut** [comment]
Oh, wow @mattkrick this is really, really good! Yeah, I was able to replicate what @jordanh described (good catch, btw!). I think this will improve the current design a lot. Thanks for fixing the progress bar on the updates phase!

**Comment by ackernaut** [comment]
Oooh, I noticed one other thing (which isn’t a use care for regular users).

If one _hacks_ the meeting (causing it to end early) it can leave completed items in the agenda queue. New agenda items can be dragged to any spot in the list.

I ran through the meeting again, and nothing has crashed yet. Just a FYI note.

**Comment by jordanh** [comment]
Dope! Merging now.

**Pull request merged**
