### PR TITLE
Speed up development server deployments

### PR DESCRIPTION
**Pull request by jordanh**
Addresses #1831 

Tests:

- [ ] When pushing to this feature branch, all the tests run
- [ ] When pushing to `development` only the required build stages run

### CODE REVIEW

**Comment by jordanh** [comment]
Current results, cut deploy time in half:
image

**Comment by jordanh** [comment]
@mattkrick will this work for starters?

**Comment by mattkrick** [comment]
that's HUGE!

**Comment by jordanh** [comment]
Alright, merge it if you want it :)

**Pull request merged**
