### PR TITLE
fix privacy, vanishing links, integration regression

### LINKED ISSUE #1604: 8.5 Privacy updates
1. When a card is changed to private, a `projectDeleted` message should be sent to everyone but the user (not mutatorId) so that card goes away
2. During the updates phase, no private cards should be seen
3. in the MeetingSummary, no private cards should be seen

### LINKED ISSUE #1624: Incorrect Copy: "Add a project set to undefined"
## Issue - Bug

screen shot 2018-01-08 at 1 20 44 pm

The title of the add project button is not being properly generated.

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #1658: Links disappear on cards
## Bug

Reproduction steps:
- Create a card in a lane
- Add a link
- Drag the card, or update status via menu (vertical ellipsis)
- The card is in another lane, but the link is no longer there

**Note**: You can do the same steps but send it to the archive via status menu instead of another status lane, and the link is still on the card.

**Recordit**: http://recordit.co/3cZrf9QkF1

**Estimated effort**: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #1667: GitHub integration regression: fetch not defined
## Issue - Bug

I'm unable to link my GitHub user to our Sales & Marketing team.

image

(note: it looks like the overall exception is caught, so there is nothing to show on the console)

### Repro steps:

(for a team already integrated with GitHub by a different user)

1. Navigate to Team Settings -> Integrations -> GitHub
2. Click "Link" on a given repository
3. Observe error message

- **OS:** macOS
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Link their GitHub account to a given repository

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] assign yourself a private card to your team dash
- [ ] start a meeting & go to your updates phase, you don't see a private card (fix #1604)

- [ ] On Team Dash highlight a single word, hit ctrl + k for the link popup, add a url and hit enter. click out of the card. drag the card to another column. The link persists. (fix #1658)

- [ ] add a github integration. add a public github repo. it works (fix #1667) 

- [ ] hover over the add project button at the top of the project column. it has a meaningful message (fix #1624)

### CODE REVIEW

**Comment by dan-f** [comment]
Ran a meeting, ended it, and saw this:

screen shot 2018-01-31 at 5 38 07 pm

**Comment by dan-f** [comment]
Doing another test run, as I can't seem to reproduce that.

TEST
- [x] assign yourself a private card to your team dash
- [x] start a meeting & go to your updates phase, you don't see a private card (fix #1604)

- [x] On Team Dash highlight a single word, hit ctrl + k for the link popup, add a url and hit enter. click out of the card. drag the card to another column. The link persists. (fix #1658)

- [ ] ❌  add a github integration. add a public github repo. it works (fix #1667) 

screen shot 2018-01-31 at 5 44 11 pm

... and in the console:

```
DEBUG GraphQL Error: [ { TypeError: Cannot read property 'split' of undefined
      at _callee2$ (/Users/dan/code/github.com/parabolinc/action/src/server/graphql/mutations/createGitHubIssue.js:94:30)
      at tryCatch (/Users/dan/code/github.com/parabolinc/action/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (/Users/dan/code/github.com/parabolinc/action/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (/Users/dan/code/github.com/parabolinc/action/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (/Users/dan/code/github.com/parabolinc/action/src/server/graphql/mutations/createGitHubIssue.js:41:191)
      at /Users/dan/code/github.com/parabolinc/action/src/server/graphql/mutations/createGitHubIssue.js:41:361
      at <anonymous>
    message: 'Cannot read property \'split\' of undefined',
    locations: [ [Object] ],
    path: [ 'createGitHubIssue' ] } ]
```

- [x] hover over the add project button at the top of the project column. it has a meaningful message (fix #1624)

💬 Well, it no longer says "Add project set to undefined," which is great, but I think that, moving forward, "Add project set to future" could be better phrased. An issue: https://github.com/ParabolInc/action/issues/1705

**Comment by mattkrick** [comment]
oh man, a github issue for a soft team member!
that's a fun one. fix coming soon

**Comment by dan-f** [comment]
BTW, the base of this should be `master`

**Comment by mattkrick** [comment]
yeah, base is always a tricky one. if i build it off master, then i'll have merge conflicts against the other branch that's being reviewed. if i build it off soft-team-members but base it off master, then it'll be a 200 file diff, which is no fun to look at. so i usually just base it off of what i built it on, then when that thing lands in master, i can change the base of this one to master. if you know a good way to manage this i'm all ears!

**Comment by jordanh** [comment]
# TEST CYCLE 2
## Status: _in progress_
- [ ] assign yourself a private card to your team dash
- [ ] start a meeting & go to your updates phase, you don't see a private card (fix #1604)

- [ ] On Team Dash highlight a single word, hit ctrl + k for the link popup, add a url and hit enter. click out of the card. drag the card to another column. The link persists. (fix #1658)

- [ ] add a github integration. add a public github repo. it works (fix #1667) 

- [ ] hover over the add project button at the top of the project column. it has a meaningful message (fix #1624)

**Comment by jordanh** [comment]
I also see a different error after adding a public repo:

image

**Comment by mattkrick** [comment]
investigating now

**Comment by jordanh** [comment]
# TEST CYCLE 3
## Status: in progress
- [x] assign yourself a private card to your team dash
- [x] start a meeting & go to your updates phase, you don't see a private card (fix #1604)

- [x] On Team Dash highlight a single word, hit ctrl + k for the link popup, add a url and hit enter. click out of the card. drag the card to another column. The link persists. (fix #1658)

- [ ] add a github integration. add a public github repo. it works (fix #1667) 

- [x] hover over the add project button at the top of the project column. it has a meaningful message (fix #1624)

**Comment by jordanh** [comment]
Ok, it looks like we have on last failing CI test, then we are GTG here

**Pull request merged**
