### PR TITLE
fix #2797 dash alert for over limit

### LINKED ISSUE #2797: Create over-limit alert
AC
- [ ] flagOverLimit(email, message) mutation exist on the private schema. (probably adds "overLimit" string to user doc)
- [ ] if flagOverLimit is called with a null message, the message is removed
- [ ] if overLimit text exists, a banner appears at the top of every dashboard page. the banner supersedes the in-meeting banner
- [ ] the banner parses the message, extracts the email address, and creates a mailto anchor that includes a body and message

Effort: 11 points

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] can use graphiql to set a flag (flagOverLimit...)
- [ ] can use graphiql to unset a flag
- [ ] when there is a meeting in progress & the over limit flag is set, the dash alert shows the over limit alert
- [ ] when a flag is set with a valid email address, the alert shows a mailto anchor with a prepopulated subject line
- [ ] when the flag is removed & the page is refreshed, the meeting alert shows us as normal

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] can use graphiql to set a flag (flagOverLimit...)
- [ ] can use graphiql to unset a flag
- [ ] when there is a meeting in progress & the over limit flag is set, the dash alert shows the over limit alert
- [ ] when a flag is set with a valid email address, the alert shows a mailto anchor with a prepopulated subject line
- [ ] when the flag is removed & the page is refreshed, the meeting alert shows us as normal

**Comment by ackernaut** [comment]
@mattkrick does the mutation look like this? Does running it without copy unset it?
```
mutation {
 flagOverLimit(copy:"over limit!", email:"terry@parabol.co") {
   error {
     message
   }
   result
 }
}
```

**Comment by mattkrick** [comment]
hit ctrl + space (or cmd + space i think) for autocomplete, i think it'll reveal that result is invalid & it'll show you what fields you can enter (user).

Yeah, no copy unsets it, check out the description for the copy arg in the right sidebar in graphiql

**Comment by ackernaut** [comment]
I see, I see, this works:
```
mutation {
  flagOverLimit(copy:"over the limit!", email:"terry@parabol.co") {
    user {
      id
    }
  }
}
```

**Comment by ackernaut** [comment]
Looks good!!

**Pull request merged**
