### PR TITLE
Fix #2610 left undefined

### LINKED ISSUE #2610: TypeError: Cannot read property 'left' of undefined
https://sentry.io/parabol/action-production/issues/839441061/?referrer=github_plugin

```
TypeError: Cannot read property 'left' of undefined
  at Da (/production/build/v3.1.0/RetroRoot_a3a996d8f7895cf1155a.js:35:383901)
  at HTMLDocument.setViewerDragState.e (/production/build/v3.1.0/RetroRoot_a3a996d8f7895cf1155a.js:35:386474)
  at HTMLDocument.o (/production/build/v3.1.0/vendors~app_e9e71d8473d7be84a20f.js:107:8764)
```

See handleDropOnGrid.js L25

### PR DESCRIPTION
**Pull request by mattkrick**
Won't know until we try, but I think this may fix the undefined `left` sentry bug.

note: this PR is inclusive of the persisted-queries branch and master

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- [ ] D&D retro smoke test

**Comment by jordanh** [comment]
Test cycle complete!

**Comment by mattkrick** [comment]
fixed! ready for another test

**Comment by jordanh** [comment]
# Test Cycle 2

## Tests
- [x] No TS Warnings
- [x] D&D retro smoke test

## Notes

Hells yeah!

**Comment by jordanh** [comment]
This is GTG. Merging

**Pull request merged**
