### PR TITLE
Epic 7 Activity Toggle and Billing Leader Menu/Tooltip

### PR DESCRIPTION
**Pull request by ackernaut**
**This PR addresses**:

- #1405 handling pause for free account
  - disables toggle and adds tooltip
- #742 / #1390 tooltip option for sole Billing Leader
  - disables ellipsis button and shows tooltip instead of menu 

**Todo**:

- [x] Add real boolean value for org on the Free plan
- [x] Wordsmith those tooltips (activity toggle, disabled ellipsis menu button)
- [x] Bug: The tooltip doesn’t always go away for the disabled ellipsis menu button.

**Future**: Support links in tooltips to link to helpful documentation for users?

_billing_toggle

## Test Plan

- [ ] As a Billing Leader for an org on the Free plan, visit the Members tab. You should see a disabled activity toggle with a tooltip.
- [ ] As a Billing Leader for an org on the Paid plan, visit the Members tab. You should be able to interact with the activity toggle.
- [ ] As a sole Billing Leader for an org, you should only get a disabled ellipsis menu button that shows a tooltip on hover.
- [ ] As one of many Billing Leaders for an org, you should get an option to remove the role from your user, or leave the org.

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick a first pass at handling some user context here…what do you think? See the TODO list. Thank you!

**Comment by mattkrick** [comment]
looks like you stumbled upon https://github.com/facebook/react/issues/4251 for the disabled button thing.
Easiest thing to do is just not have it be disabled.
i wired up the stuff.
i think it's good to go

**Comment by ackernaut** [comment]
## Test Cycle No. 1

- [ ] As a Billing Leader for an org on the Free plan, visit the Members tab. You should see a disabled activity toggle with a tooltip.
- [ ] As a Billing Leader for an org on the Paid plan, visit the Members tab. You should be able to interact with the activity toggle.
- [ ] As a sole Billing Leader for an org, you should only get a disabled ellipsis menu button that shows a tooltip on hover.
- [ ] As one of many Billing Leaders for an org, you should get an option to remove the role from your user, or leave the org.

**Comment by ackernaut** [comment]
@mattkrick everything looks good and I passed the test as sole Billing leader and 1 of many BLs both on free and paid plans. The only thing bugging us is the codecov targets.

**Pull request merged**
