### PR TITLE
update draft to my github branch fix #1317

### LINKED ISSUE #1317: TypeError: Cannot read property 'getIn' of undefined
https://sentry.io/parabol/action-production/issues/340877351/

```
TypeError: Cannot read property 'getIn' of undefined
  at method (../node_modules/draft-js/lib/editOnInput.js:89)
  at func (../node_modules/draft-js/lib/DraftEditor.react.js:147)
  at invokeGuardedCallback (../node_modules/react-dom/lib/ReactErrorUtils.js:26)
  at executeDispatch (../node_modules/react-dom/lib/EventPluginUtils.js:85)
  at executeDispatchesInOrder (../node_modules/react-dom/lib/EventPluginUtils.js:108)
...
(13 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mattkrick**

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Template

It:
- [ ] allows me to create Card with Safari browser

**Comment by jordanh** [comment]
I'm getting this:

```
1504308286203 - Origin: Worker (PID 7390)
   [Error] Error: /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/universal/modules/email/components/Card/Card.js: Cannot find module 'draft-js' from '/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/universal/modules/email/components/Card'
```

even if I delete yarn.lock and node_modules...

**Comment by mattkrick** [comment]
oh grrr, i heard something about yarn not playing kindly with tarballs & non-relative paths. lemme try another way

**Comment by mattkrick** [comment]
that feeling when finding the bug & fixing it took less time than installing a dependency from github...

**Comment by jordanh** [comment]
Something odd, unrelated to these changes:

image

**Comment by jordanh** [comment]
Sorry, went too fast there. That happened when I tried to signout.

**Comment by jordanh** [comment]
Hmm, this may be a red herring. I think my .env got smoked (somehow??)

**Comment by jordanh** [comment]
# Test Cycle 2

It:
- [ ] allows me to create Card with Safari browser
- - -
Results: tested on Safari, I still wasn't able to type. Is the package in package.json correct?

**Comment by jordanh** [comment]
I gave this another crack. I tested the CSS hack from your PR (https://github.com/facebook/draft-js/pull/1356) and saw that it worked. I also verified that the `draft-js` version I had contained your fix. However, when I tested with Safari it still wasn't working.

There must be some other component in the tree that's behaving badly...

**Comment by mattkrick** [comment]
some versions of safari need a -webkit prefix.
all fixed up & working on dev!

**Comment by jordanh** [comment]
# Test Cycle 3

It:
- [ ] allows me to create Card with Safari browser

**Comment by jordanh** [comment]
Verified! Bravo @mattkrick !!

**Pull request merged**
