### PR TITLE
do not end long running retros

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] call endOldMeetings from the private schema, retro is not ended & an event is sent to segment

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] call endOldMeetings from the private schema, retro is not ended & an event is sent to segment

**Comment by ackernaut** [comment]
@mattkrick so should I start a retro, hack the start time in DB, then run this?

**Comment by ackernaut** [comment]
Worked like a charm!

**Comment by mattkrick** [comment]
@ackernaut yep, db hack is the only way. thanks!

**Pull request merged**
