### PR TITLE
Add rejoin facilitator button

### PR DESCRIPTION
**Pull request by ndey96**
This PR addresses https://github.com/ParabolInc/action/issues/301

I really like the current UX with the react-notification system. While a floating material button would be cool, I think the current solution is pretty good. Curious to get everyone's thoughts
@mattkrick @ackernaut @jordanh

### CODE REVIEW

**Comment by ackernaut** [comment]
Hey @ndey96!

I like your thinking, using the existing toast pattern with a “Rejoin” button!

I’m noticing a few things that need work (and perhaps you were just getting started):

1. If both the non-facilitator and the facilitator are at the same location, and the non-facilitator goes to another phase or another location in the same phase, they don’t get a toast right away. The toast only appears once they navigate a second time. I think it should show as soon as one is in a different phase (updates vs agenda) or a different location in the same phase (agenda item 2 vs agenda item 4).
2. Every location change (besides the initial change of phase already mentioned) pops a brand new toast. I suggest we show a single toast instance on the first nav-away that persists until the user either rejoins by navigating or rejoins by tapping the toast button.
3. I saw that if I navigated to a different agenda item than the one the facilitator is on, and then navigated back to where the facilitator was, I got the rejoin toast.

**Some examples on record.it**

[link](http://recordit.co/bFIH7Gc6lX)
GIF

[link](http://recordit.co/ZHtIgw6yMk)
GIF

@mattkrick if we stick with the toast for this, can you think of any UX conflicts with other toasts during the meeting?

**Comment by ackernaut** [comment]
Also I noticed a regression in agenda item nav states, and I’m not sure that it is from any changes in this PR so far. When I navigated back to an agenda item that was already covered, I didn’t get the styles for my local state. Basically, there should be an active state for local agenda item regardless of facilitator state. I can look at that.

**Comment by ackernaut** [comment]
Never mind my last comment, I don’t think there was ever an active style for local user.

**Comment by mattkrick** [comment]
I'll be the stick in the mud: I think a toast is something temporary. It's
not wrong to be out of sync with the facilitator, and it's not something
that requires immediate action, so in my eyes, it doesn't pass the toast
test. By letting a toast rest up there, we've got this big thing just
chilling in the corner and eventually users will just ignore all toasts,
which isn't good. I'd prefer something much smaller and calls less
attention to it, but I'll let you guys have final say.

**Comment by ackernaut** [comment]
Good points. I feel it is on the edge of our use cases.

So the spec might look like:

- If user location !== facilitator location, show a Thing to Be Designed™
- Thing to Be Designed™ should route back to facilitator location.

I feel like this is something that be done in the `MeetingContainer`? We just have a condition and show a presentational Thing to Be Designed™ that floats above the main area. I feel like we can get away with `position: absolute` in this case (no need for portal HOC).

What do you think @mattkrick and @ndey96? Shall I design the Thing to Be Designed™?

**Comment by mattkrick** [comment]
Sounds good! Just 3 things to keep in mind for design: we want to make the
avatars bigger. We want to support 8-person teams. We want to minimize the
whitespace in the updates phase. As long as the thing doesn't cover up
anything and impede me from what I wanna do (like click avatar #8) I'm
happy.

**Comment by ackernaut** [comment]
Here’s a concept:

agenda-item-rejoin-facilitator 2x

• Facilitator ring more pronounced
• Viewing label added for clarity
• Floating “Rejoin” button, bottom right (when `local location !== facilitator location`) (routes to facilitator location)
• Local active style for agenda item “lobby routes”
• Can click on facilitator avatar for same effect as rejoin button???

**Comment by mattkrick** [comment]
How do you change facilitators?
I kinda want the rejoin button smaller (no text +tooltip?) Otherwise their
future column is gonna get covered up
Good stuff!

**Comment by ackernaut** [comment]
@mattkrick not sure we need to design for changing facilitators yet —I was just wondering if the iteration made sense against what we think future designs might be.

I agree with the button—could it be round + icon + tooltip?

**Comment by ackernaut** [comment]
Suggestions for the icon-only button:

[comments](http://fontawesome.io/icon/comments/)
[comments](http://fontawesome.io/icon/comments/)

**Comment by ndey96** [comment]
@ackernaut Nice work! I vote [user](http://fontawesome.io/icon/user/)(since there is only one facilitator to rejoin) or [crosshairs](http://fontawesome.io/icon/crosshairs/) (because google maps)

**Comment by jordanh** [comment]
@ndey96 you have the power to choose! Choose wisely :)

**Comment by ndey96** [comment]
@ackernaut @jordanh @mattkrick This is kind of a long thread but here is a Checklist™ of what I think needs to be done to get this merged:

- [x] Add floating rejoin-facilitator button
- [ ] Clicking facilitator avatar rejoins facilitator
- [ ] Figure out why rejoin only appears after 2nd navigation (Terry's issue)

Would appreciate some confirmation that I'm getting everything straight 👍

**Comment by jordanh** [comment]
@ndey96 that list looks correct to me!

**Comment by mattkrick** [comment]
@jordanh @ndey96 i would say "Clicking facilitator avatar rejoins facilitator" is out of scope. In the future, clicking an avatar will pull up a menu with many possible actions (promote to facilitator, change name/avatar, rejoin facilitator, ???). As soon as we make the avatars clickable, i think it'd be good patterning to have them do the same action to minimize breaking UX changes.

**Comment by jordanh** [comment]
Ah, @mattkrick I agree. I misread @ndey96's original list. Just the button is perfect.

**Comment by ndey96** [comment]
@mattkrick @jordanh @ackernaut Ready for review!

**Comment by jordanh** [comment]
@ndey96 looking pretty good! Would you mind resolving that conflict and then I'll give it a test?

**Comment by ndey96** [comment]
@jordanh Conflicts resolved 👍

**Comment by jordanh** [comment]
Simple. Elegant. Works well. Thank you so much @ndey96!

**Pull request merged**
