### PR TITLE
Fix css insertRule error

### LINKED ISSUE #1946: SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule ':-ms-input-placehold...
## Bug:

We saw this one when we reviewed the new auth pages PR, but decided to ignore it. It is now generating an automatic exception report on Sentry:

https://sentry.io/parabol/action-production/issues/507510528/

```
SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule ':-ms-input-placeholder{color:rgba(68, 66, 88, 0.6);}'.
  at injectStyleTag (../node_modules/aphrodite-local-styles/lib/inject.js:53:1)
  at call (../node_modules/aphrodite-local-styles/lib/inject.js:210:1)
  at call (../node_modules/asap/browser-asap.js:48:1)
  at MutationObserver.n (../node_modules/asap/browser-raw.js:52:1)
```

On the surface, it looks like a rather simple CSS syntax error. We should clean it up.

**Expected effort:** 10.5 points

### Acceptance Criteria
A developer can:
- [ ] fix the above exception or, if the effort is greater than 10.5, open a new issue which identifies the root cause and scopes the effort to fix it

If this issue is fixed, a user can:

- [ ] login without causing the above, or any new, exception

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1946 

To verify:
- run `yarn build && yarn start` on master
- see the error in the console when visiting the `/signin` page
- checkout `fix-css-insertrule-error`
- run `yarn build && yarn start` again
- don't see the error in the console when visiting the `/signin` page

### CODE REVIEW

**Comment by ackernaut** [comment]
I’d like to review this one when it’s ready!

**Comment by dan-f** [comment]
'tis ready, mr @ackernaut!

**Comment by ackernaut** [comment]
@dan-f this one LGTM! nice work

**Comment by mattkrick** [comment]
:+1:

**Pull request merged**
