### PR TITLE
copy edits

### PR DESCRIPTION
**Pull request by mattkrick**
@ackernaut @jordanh check out the copy edits, let me know what you think.

### CODE REVIEW

**Comment by jordanh** [comment]
Note @mattkrick, ts warning on this branch:

```
WARNING in [at-loader] ./src/universal/components/MeetingHelp/withStaggerShow.tsx:8:12
    TS2339: Property 'timeout' does not exist on type 'WithStaggerShow'.

WARNING in [at-loader] ./src/universal/components/MeetingHelp/withStaggerShow.tsx:15:26
    TS2339: Property 'timeout' does not exist on type 'WithStaggerShow'.
```

**Comment by jordanh** [comment]
Adding this to the wish list, I'd love to have a little animated ellipses in a pill that would signify that more text is coming, making this surface feel even more conversational:

gif

**Comment by ackernaut** [comment]
Small typography things: I’d like to add a `.` (period) to every line and make any straight ticks `'` into smart single quotes `’`.

**Comment by jordanh** [comment]
I took @ackernaut's suggestions. Made a few small copy edits too.

**Comment by jordanh** [comment]
I also added a speech bubble component. It isn't wired to anything right now:

gif

If you like it, I figure it could get intelligently plumbed into `DelayedCopy`. Otherwise, if we hate it we can nuke it. @ackernaut, @mattkrick check it out.

**Comment by jordanh** [comment]
Merging this for now

**Pull request merged**
