### PR TITLE
New reflect phase

### PR DESCRIPTION
**Pull request by mattkrick**
Trying out 2 new tools in this PR: typescript & storybook. i love them both.

Burndown:
- [x] make columns focusable when the facilitator clicks them
- [x] share focused column with other team members
- [x] animate focus change
- [x] build an editor for the top of the columns
- [x] build a placeholder for the reflection stack
- [x] build an energy bar below the editor
- [x] wire up the energy bar to work with the top-of-column editor
- [x] wire up the energy bar to work with existing reflections
- [x] build a chit pool to show other reflections
- [x] animate the reflection moving to the stack
- [x] update prod webpack config to support ts

Reflection Modal Burndown:
- [x] modal animates in/out smoothly
- [x] deleting a reflection from the modal looks good
- [x] modal decides how many columns to show & it looks good
- [x] editing a reflection in the modal changes the reflow when a line is added/removed
- [ ] resizing the window resizes the modal (optional)

TEST - COLUMN
- [ ] facilitator clicking on the column header focuses the column for everyone in the meeting

TEST - EDITOR + STACK
- [ ] when your caret is in the editor, others can see that someone is editing
- [ ] hitting enter to submit a blank reflection fails
- [ ] hitting enter to submit a reflection with text succeeds
- [ ] when submitted, the reflection flies down to the stack
- [ ] if the stack is of size 1, you can edit it in place
- [ ] if the stack has 2+ reflections, clicking the card opens the modal

TEST - MODAL
- [ ] the modal opening animation is pretty
- [ ] the modal supports a LARGE number of reflections (20+)
- [ ] the scrollbar appears when there are a large number of reflections
- [ ] extra columns are used to avoid the scrollbar
- [ ] editing a card in the modal works
- [ ] editing a card in the modal is visible to other participants
- [ ] when editing a card, if you add/remove a line, the size & layout of the modal readjusts
- [ ] when deleting a card, the layout readjusts
- [ ] closing the modal looks good

TEST - CHITS
- [ ] when someone else is editing, a progress chit appears
- [ ] when a card is submitted, a white chit appears

### CODE REVIEW

**Comment by mattkrick** [comment]
hey @ackernaut this is ready for your stylish touches. 
- [ ] the font colors & sizes need to be fix
- [ ] check out the health bar vs. the active chits. IMO the latter is cleaner, so i say we nuke the health bar

**Comment by ackernaut** [comment]
@mattkrick I pulled locally and also checked it out on dev. Currently I’m seeing an error in the Reflect view so I’ll wait to hear from you:
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at getBBox (getBBox.ts:6)
    at ReflectionStack.animateFromEditor (ReflectionStack.tsx:106)
    at ReflectionStack.componentDidUpdate (ReflectionStack.tsx:101)
    at commitLifeCycles (react-dom.development.js:14370)
    at commitAllLifeCycles (react-dom.development.js:15463)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:15604)
    at completeRoot (react-dom.development.js:16619)
```

**Comment by ackernaut** [comment]
UI updates WIP:
- [ ] Yank health bar under input control
- [ ] TBD column vs grid layout
- [ ] TBD max number of reflections represented by chit grid (3 rows?)
- [ ] Layout polish (alignment, gutters)
- [ ] Typography polish (size, color)
- [ ] Component detail polish

**Comment by mattkrick** [comment]
i ended up going with the 2nd option.
the reason why is because i forgot how relay worked.
- when the server response comes back, relay deletes the optimistic card, which means we'd have to do a deep copy of it before we pass it through.
- it's also difficult to know when to put the stack in state. `getSnapshotBeforeUpdate` should be a pure method, but even if we returned the whole stack, we wouldn't be able to update the ref in the render method. that means we'd have to use gDSFP, which means we'd have to move all the isAnimating boolean and all the refs into the props or state, which makes it a little uglier.

the 2nd option turned out to look pretty natural. If an animation is still going on, we see where it is & how much time it has left & then we calculate it's remaining time & bezier-curve & put the new item on that animation path.

**Comment by ackernaut** [comment]
@mattkrick that sounds pretty sharp, I’ll give it a try!! thanks

**Comment by mattkrick** [comment]
known bugs to address before release:
- [ ] clicking in & out of the phase editor increments the team member counter
- [ ] do the above a whole bunch shifts the contents to the left (around 6 or 7 times needed)

**Comment by ackernaut** [comment]
@mattkrick I’ve got [a list](https://github.com/ParabolInc/action/pull/2335#issuecomment-417491248), linking to comment above, and I would like to ship sooner and less-than-perfect, as the things I’m seeing are time-consuming or can be deferred until we add templates. I think that the 3 to-do items need to be included to ship this. I can create an issue to capture the future items as UI improvements. Let me know. I want to get to the other PRs.

**Comment by mattkrick** [comment]
the group phase stuff is fixed in the subsequent PR, so i think all that's needed is handling the activity for the current viewer.

i was torn between showing & not showing a viewer's own activity, i'll go ahead & remove

**Pull request merged**
