### PR TITLE
use yarn in CI

### PR DESCRIPTION
**Pull request by mattkrick**
just testing :smile:

### CODE REVIEW

**Comment by jordanh** [comment]
LGTM!

**Comment by mattkrick** [comment]
i'm not seeing the time savings I thought i would (still takes ~5 mins to run) but I guess it's best to use yarn here if we're gonna eventually move to yarn in deployment, cuz faster deploys = better.

**Comment by jordanh** [comment]
Definitely fun to try and experiment with.

dokku uses herokuish, which will need to be extended to use yarn. It's probably inevitable. But that's what will gate us from yarning on the production infrastruture.

**Comment by mattkrick** [comment]
i'd be very surprised if someone hasn't already published a script/guide to make the switch. If not, we can give it another week or 2.

**Comment by jordanh** [comment]
Well, I just looked at the herokuish source. I just learned it actually uses the heroku buildpacks directly. So, when the nodejs buildpack is updated, we can yarn away. In fact, if we wanted to live dangerously: https://github.com/heroku/heroku-buildpack-nodejs/issues/337

**Comment by mattkrick** [comment]
eh i can wait till it lands in the next version. I simply love how much the JS community loves to adopt new tech.

**Pull request merged**
