### PR TITLE
Epic6.5 closeout mk

### PR DESCRIPTION
**Pull request by mattkrick**
Project Card
- [ ] type "hello". highlight it. hit ctrl+k. see cursor starts in url field. add a url.
- [ ] click anywhere on the hyperlink & hit ctrl+k, see cursor starts in text field.
- [ ] go to end of "hello " (+1 space), hit ctrl+k, see cursor starts in text field.
- [ ] create a new card with 3 blank lines & then the word "hello". click out of the card. see the blank lines go way

Seed Projects fixed
- [ ] create a new user. see #private cards are yellow
 
Migrations
- [ ] verify that the Invitations table has homogeneous types for tokenExpiration

### CODE REVIEW

**Comment by ackernaut** [comment]
## Partial Test Cycle No. 1
### Status: Completed!
👏  @mattkrick nice work!
Wasn’t sure what to look for with the Migrations checklist item.

Project Card
- [x] type "hello". highlight it. hit ctrl+k. see cursor starts in url field. add a url.
- [x] click anywhere on the hyperlink & hit ctrl+k, see cursor starts in text field.
- [x] go to end of "hello " (+1 space), hit ctrl+k, see cursor starts in text field.
- [x] create a new card with 3 blank lines & then the word "hello". click out of the card. see the blank lines go way

Seed Projects fixed
- [x] create a new user. see #private cards are yellow

**Note**:

Trimming accounts for empty new lines, but doesn’t handle arbitrary spaces (using spacebar). I’m not worried about this, but I’m wondering how to make the error message for “no title” a little more user friendly. Is there a way to catch the error and specify what copy to use? @mattkrick 

img

**Comment by mattkrick** [comment]
of course, what copy would you like?

**Comment by ackernaut** [comment]
@mattkrick good questions, perhaps “Check the first line. It will be the GitHub issue title.” That’s a first iteration, yay/nay?

**Comment by mattkrick** [comment]
that's wrapping onto 3 lines, i tried "The first line is the title. It cannot be empty" and got it to 2

**Comment by ackernaut** [comment]
@mattkrick oh that’s good 💥

**Comment by ackernaut** [comment]
“can’t” is ok too, with a real apostrophe, of course ;)

**Comment by mattkrick** [comment]
fixed! ready to merge?

**Comment by ackernaut** [comment]
@mattkrick LGTM! Nice work on this one and thanks for hearing my nags! I didn’t verify your checklist item about migrations, so if you’re ok pushing that one through then 👍  from me.

**Pull request merged**
