### PR TITLE
bug fixes

### LINKED ISSUE #3525: Bug: cannot scroll prompt column with many Reflection Groups
## Issue - Bug

Reported by a user 🔒 . Screenshot is here 🔒 (protecting sensitive user data).

User writes:

> We just had a retro today. For two of our team members, they couldn't scroll to the bottom of the items list to vote on / examine a ticket.

What I presume the screenshot is showing is a user that navigated backward in order to capture the issue, after they had advanced to Discuss.

For additional details, please see the [support ticket](https://app.hubspot.com/contacts/3888472/ticket/80755359?) 🎟 🔒 

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
   - Triage and fix root cause if the fix is trivial
      - Fix: a user can scroll a column with a dozen groups or more
   - Open a new issue if fix is non-trivial

### LINKED ISSUE #3530: teams without leaders
There exist about 100 teams that do not have a leader, ie `isLead == false`.
I'm not really sure how this is possible, but it's not good since you can't really admin anything if you don't have a leader.
Problem goes back to 2017, although it happens much more frequently now (more users?)
Doesn't matter if it's an onboarding team or an added team.

The commonality is that the Team.createdAt timestamp is typically much older than the TeamMember.createdAt where the member id is Team.createdBy.

the only way i could see this happening is if the TeamMember was recreated, since we have a conflict overwrite to handle team members who were removed & then re-added.

Following that premise, we assume `insertNewTeamMember` is called for someone who is already on the team.

there are 2 ways this could get called:
- createTeamAndLeader (used by addOrg, addTeam, bootstrapNewUser)
- acceptTeamInvitation 

addOrg/addTeam are not likely candidates because the team would not exist yet. if it were a duplicate creation requestion, it'd have a new teamId, so I don't think it can come from there.
bootstrapNewUser is unlikely because that means the user is brand new, so the team & team member likely doesn't exist yet.

acceptTeamInvitation throws an error if it's a team invite & the viewer is already on the team (user.tms.includes(teamid))

this safety check is NOT performed on the mass invitation link.
therefore, if a team lead visit a mass invite link, they may remove their isLead tag.

AC
- [ ] error on using a token when you're a part of a team
- [ ] don't replace on conflict. merge

Effort: 10.5

### PR DESCRIPTION
**Pull request by mattkrick**
This is the result of another round of sentry bugfixes.
most aren't serious, a couple are

TEST

fix #3525 vertical height in meeting
- [ ] put 20 cards in a column for a retro
- [ ] the height of the column never exceeds the bottom of the window
- [ ] can drag & drop & everything looks good

fix #3530 teams without leaders
- [ ] create a new team, have someone else join it via team invite, it works
- [ ] create a mass invite token & visit that link. ensure that you are still the team lead

fix bork on invite existing member
- [ ] invite someone by email who is already on the team. an error message pops up instead of the whole app borking

ended meetings
- [ ] go into a meeting that has already ended, the facilitator bar doesn't exist

add reflect template
- [ ] add a new reflect template, it works

fix regexp
- [ ] in the top search bar type in "*" or "+", the app doesn't crash

reactji
- [ ] click the reactji icon on a reflection. then hit the enter button. no error is printed to the console

reflection group animations
- [ ] create a reflection group of 5+ cards & expand/collapse the group. the animation is seamless

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut the borked team invite & borked regexp make me wanna treat this as a hotfix, but i'll let you make the call.

**Comment by ackernaut** [comment]
I’m looking at this now; yeah, I think pushing a patch makes sense.

**Comment by jordanh** [comment]
# Test Cycle 1

This is the result of another round of sentry bugfixes.
most aren't serious, a couple are

## Tests

fix #3525 vertical height in meeting
- [ ] put 20 cards in a column for a retro
- [ ] the height of the column never exceeds the bottom of the window
- [ ] can drag & drop & everything looks good

fix #3530 teams without leaders
- [ ] create a new team, have someone else join it via team invite, it works
- [ ] create a mass invite token & visit that link. ensure that you are still the team lead

fix bork on invite existing member
- [ ] invite someone by email who is already on the team. an error message pops up instead of the whole app borking

ended meetings
- [ ] go into a meeting that has already ended, the facilitator bar doesn't exist

add reflect template
- [ ] add a new reflect template, it works

fix regexp
- [ ] in the top search bar type in "*" or "+", the app doesn't crash

reactji
- [ ] click the reactji icon on a reflection. then hit the enter button. no error is printed to the console

reflection group animations
- [ ] create a reflection group of 5+ cards & expand/collapse the group. the animation is seamless

## Notes

TS warnings encounted on `yarn build` from top level:
```
WARNING in [at-loader] ./graphql/mutations/createReflection.ts:103:58
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.group' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ./graphql/mutations/removeReflection.ts:63:58
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.group' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ./graphql/mutations/voteForReflectionGroup.ts:116:9
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.discuss' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:20:28
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:20:61
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:24:26
    TS6133: 'event' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:24:33
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:25:14
    TS2339: Property 'skipWaiting' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:40:32
    TS6133: 'url' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:51:27
    TS6133: 'event' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:51:34
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:52:14
    TS2339: Property 'clients' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:61:31
    TS2304: Cannot find name 'FetchEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:90:6
    TS2339: Property 'oninstall' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:91:6
    TS2339: Property 'onactivate' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:92:6
    TS2339: Property 'onfetch' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:92:20
    TS2304: Cannot find name 'FetchEvent'.
```

**Comment by jordanh** [comment]
@mattkrick I'm blocked testing the above because I keep getting:

```
sw.ts:61 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at onFetch (sw.ts:61)
    at sw.js:173
```

I've tried:
   * Unregistering the service worker and clearing application data and reloading
   * Removing yarn.lock, rebuilding, doing the above, and reloading

...to no avail! What might I be missing?

**Comment by mattkrick** [comment]
do you have devtools open? that error is actually sent on behalf of devtools

**Comment by jordanh** [comment]
I do have DevTools open. Here's what I see when I try to create an account:

image

There is no error on the server console, but I think that's because we are not emitting them anymore. Let me see if I can track that down

**Comment by mattkrick** [comment]
@jordanh for easy testing, i'd just run in dev instead of building & running in prod.
if you do want to run in prod & see server errors you'll have to edit L16 of sendToSentry.ts

**Comment by jordanh** [comment]
Ah yes. That's right. Now I'm cooking with gas again. It was the silly `postdeploy` hook

**Comment by jordanh** [comment]
@mattkrick I'm starting to fear the worst here like something is wrong with my environment

**Comment by mattkrick** [comment]
what's the bug?

**Comment by jordanh** [comment]
Note for future generations: during test cycle1, my `packages/client/__generated__` folder assets were not being correctly invalidated by the relay compiler. Removing this folder and running `yarn run build:relay` and `yarn workspace parabol-server postdeploy` made everything happy once again

**Comment by jordanh** [comment]
# Test Cycle 2

This is the result of another round of sentry bugfixes.
most aren't serious, a couple are

## Tests

fix #3525 vertical height in meeting
- [ ] put 20 cards in a column for a retro
- [ ] the height of the column never exceeds the bottom of the window
- [ ] can drag & drop & everything looks good

fix #3530 teams without leaders
- [ ] create a new team, have someone else join it via team invite, it works
- [ ] create a mass invite token & visit that link. ensure that you are still the team lead

fix bork on invite existing member
- [ ] invite someone by email who is already on the team. an error message pops up instead of the whole app borking

ended meetings
- [ ] go into a meeting that has already ended, the facilitator bar doesn't exist

add reflect template
- [ ] add a new reflect template, it works

fix regexp
- [ ] in the top search bar type in "*" or "+", the app doesn't crash

reactji
- [ ] click the reactji icon on a reflection. then hit the enter button. no error is printed to the console

reflection group animations
- [ ] create a reflection group of 5+ cards & expand/collapse the group. the animation is seamless

**Comment by jordanh** [comment]
@mattkrick LGTM! Ready to merge and deploy are your convenience...

**Pull request merged**
