### PR TITLE
Epic 6.5 Check-In Sprint (TA)

### PR DESCRIPTION
**Pull request by ackernaut**
This PR addresses #1164 “Remove “Here/Not Here” from non-facilitator view”.

_The 3rd non-Facilitator test needs a 2nd opinion if the UX is safe_:
>You can go back to the Check-In once the meeting phase is Updates or Agenda and you see the Check-In controls that the Facilitator sees. This allows team members to go back and check somebody in (late-comer). We could hide it always and they can simply press “Rejoin Facilitator” or use the left navigation.

_Note that the facilitation hint_ is a component with a message followed by an animated ellipsis. I changed the color from warm pink to mid-purple gray so that it doesn’t distract from the primary purpose of each view.

## UX Test Plan (updated)
Sign in to 2 separate windows locally (perhaps 1 Chrome Incognito) using different `@prbl.co` seed users. Start a meeting with one of the users. Join the meeting as the other user.

**As a non-Facilitator**:

- [ ] You see “Waiting for `currentMember.preferredName` to share with the team…” on all but the last team member’s Check-In.
- [ ] You see “Waiting for `facilitatorName` to advance to Updates…” on the last team member’s Check-In.
- [ ] You can go back to the Check-In once the meeting phase is Updates or Agenda and you see the Check-In controls that the Facilitator sees. This allows team members to go back and check somebody in (late-comer).
- [ ] You can tap on a top-right avatar menu and advance to others’ Check-In, but you still see a facilitation hint at the bottom (during Check-In, unless the meeting has advanced to Updates or Agenda).
- [ ] You see “Waiting for `currentMember.preferredName` to give Updates…” on all but the last team member’s Updates.
- [ ] You see “Waiting for `facilitatorName` to advance to the Agenda…” on the last team member’s Updates.
- [ ] You can go back to the Updates once the meeting phase is the Agenda and you see the button control that the Facilitator sees. This allows for easy navigation forward when behind.
- [ ] You can tap on a top-right avatar menu and advance to others’ Updates, but you still see a facilitation hint (during Updates, unless the meeting has advanced to the Agenda).
- [ ] During Agenda First Call, you see a facilitation hint “Waiting for…” the Facilitator to begin the Agenda.
- [ ] During the last Agenda Item, you see a facilitation hint “Waiting for…” the Facilitator to wrap up the Agenda (only if the meeting hasn’t made it to Last Call yet).
- [ ] During the last Agenda Item, you see the same button the Facilitator sees “Wrap up the Meeting” (if the meeting has already made it to Last Call and you or the team navigated back to an item).
- [ ] During Agenda Last Call, you see a facilitation hint “Waiting for…” the Facilitator to end the meeting.

**As the Facilitator**:

- [ ] You see controls to mark “Here/Not Here” during the Check-In phase.
- [ ] You can advance to Updates from Check-In.
- [ ] You can advance to Agenda from Updates.
- [ ] You can begin the Agenda item processing.
- [ ] You can advance to Last Call after the last Agenda Item.
- [ ] You can end the meeting.

### CODE REVIEW

**Comment by jordanh** [comment]
You are hitting #1325, it's fixed in PR #1328 – do you want me to run a test cycle on this branch before merging. Is it ready?

**Comment by ackernaut** [comment]
@jordanh I’ll merge in latest `epic6.5` and push here…and yes running a test plan cycle would be great to get a 2nd pair of 👀  on the UX.

**Comment by jordanh** [comment]
Ok, I'll be watching for your merge to this branch from `epic6.5` and then I will test

**Comment by jordanh** [comment]
# Test Cycle 1
## Status: _in progress_
## Tests

Sign in to 2 separate windows locally (perhaps 1 Chrome Incognito) using different `@prbl.co` seed users. Start a meeting with one of the users. Join the meeting as the other user.

**As a non-Facilitator**:

- [ ] You see “Waiting for `currentMember.preferredName` to share with the team…” on all but the last team member’s Check-In.
- [ ] You see “Waiting for `facilitatorName` to advance to Updates…” on the last team member’s Check-In.
- [ ] You can go back to the Check-In once the meeting phase is Updates or Agenda and you see the Check-In controls that the Facilitator sees. This allows team members to go back and check somebody in (late-comer). We could hide it always and they can simply press “Rejoin Facilitator” or use the left navigation.
- [ ] You can tap on a top-right avatar menu and advance to others’ Check-In, but you still see a facilitation hint at the bottom (during Check-In, unless the meeting has advanced to Updates or Agenda).
- [ ] During Updates, you see a facilitation hint “Waiting for `facilitatorName` to advance to the Agenda…” on the last team member’s Update.
- [ ] During Agenda First Call, you see a facilitation hint “Waiting for…” the Facilitator to begin the Agenda.
- [ ] During Agenda Last Call, you see a facilitation hint “Waiting for…” the Facilitator to end the meeting.

**As the Facilitator**:

- [ ] You see controls to mark “Here/Not Here” during the Check-In phase.
- [ ] You can advance to Updates from Check-In.
- [ ] You can advance to Agenda from Updates.
- [ ] You can begin the Agenda item processing.
- [ ] You can end the meeting.

**Comment by jordanh** [comment]
All tests pass and LGTM!

I think the only thing I noticed is that there is an opportunity to use similar facilitation logic in Updates as Check-in: we could change the "Next team member" to say "Waiting for `preferredName` to give their update" &c.

What do you think?

**Comment by ackernaut** [comment]
@jordanh re:Updates logic—I see the consistency there. Also, the users can use the avatar menu if they do want to jump ahead to another team member (like in Check-In). I like it, worth trying!

**Comment by ackernaut** [comment]
I’ll make the change to Updates, run an updated test cycle and merge? @jordanh

**Comment by jordanh** [comment]
Sounds good!

**Comment by ackernaut** [comment]
# Test Cycle 2

## Status: in progress

## UX Test Plan (updated)
Sign in to 2 separate windows locally (perhaps 1 Chrome Incognito) using different `@prbl.co` seed users. Start a meeting with one of the users. Join the meeting as the other user.

**As a non-Facilitator**:

- [ ] You see “Waiting for `currentMember.preferredName` to share with the team…” on all but the last team member’s Check-In.
- [ ] You see “Waiting for `facilitatorName` to advance to Updates…” on the last team member’s Check-In.
- [ ] You can go back to the Check-In once the meeting phase is Updates or Agenda and you see the Check-In controls that the Facilitator sees. This allows team members to go back and check somebody in (late-comer).
- [ ] You can tap on a top-right avatar menu and advance to others’ Check-In, but you still see a facilitation hint at the bottom (during Check-In, unless the meeting has advanced to Updates or Agenda).
- [ ] You see “Waiting for `currentMember.preferredName` to give Updates…” on all but the last team member’s Updates.
- [ ] You see “Waiting for `facilitatorName` to advance to the Agenda…” on the last team member’s Updates.
- [ ] You can go back to the Updates once the meeting phase is the Agenda and you see the button control that the Facilitator sees. This allows for easy navigation forward when behind.
- [ ] You can tap on a top-right avatar menu and advance to others’ Updates, but you still see a facilitation hint (during Updates, unless the meeting has advanced to the Agenda).
- [ ] During Agenda First Call, you see a facilitation hint “Waiting for…” the Facilitator to begin the Agenda.
- [ ] During the last Agenda Item, you see a facilitation hint “Waiting for…” the Facilitator to wrap up the Agenda (only if the meeting hasn’t made it to Last Call yet).
- [ ] During the last Agenda Item, you see the same button the Facilitator sees “Wrap up the Meeting” (if the meeting has already made it to Last Call and you or the team navigated back to an item).
- [ ] During Agenda Last Call, you see a facilitation hint “Waiting for…” the Facilitator to end the meeting.

**As the Facilitator**:

- [ ] You see controls to mark “Here/Not Here” during the Check-In phase.
- [ ] You can advance to Updates from Check-In.
- [ ] You can advance to Agenda from Updates.
- [ ] You can begin the Agenda item processing.
- [ ] You can advance to Last Call after the last Agenda Item.
- [ ] You can end the meeting.

**Comment by ackernaut** [comment]
Thanks for the test cycle @jordanh !

**Pull request merged**
