### PR TITLE
Add timer notifications

### PR DESCRIPTION
**Pull request by mattkrick**
TEST (needs migration)

TEAM INTEGRATIONS
- [ ] a stage time limit started team notification exists
- [ ] a stage time limit ended user notification exists
- [ ] adding a brand new slack integration sets all the notification types on by default
- [ ] teams with existing integrations get both new notifications turned on automatically
- [ ] turn off all team notifications & hit refresh & then turn 1 on, it works (bugfix)

REFLECT, GROUP, VOTE, DISCUSS PHASE
- [ ] clicking the timer > timebox tab shows a send-to-slack checkbox
- [ ] cannot set the timebox to a time that's before right now
- [ ] as a user without slack set up, click the checkbox. it opens the slack oauth & then sets the checkbox after it completes
- [ ] after setting the timebox for a time that is more than 10 minutes in the future, a scheduled job is created. can verify with `r.db('actionDevelopment').table('ScheduledJob')`
- [ ] update the job to run in the next 2 minutes with `r.db('actionDevelopment').table('ScheduledJob').update({runAt: new Date(Date.now() + 1000 * 60 * 2)})`
- [ ] in graphiql on the private schema, run `mutation { runScheduledJobs(seconds: 120) }`, which is what action-chronos would call
- [ ] receive a slack notification in < 2 minutes
- [ ] clear the timebox, set a new one without the slack checkbox set. repeat steps above, receive an in-app notification in 2 minutes
- [ ] navigating the meeting forward removes the scheduled job (and any in-app notifications)
- [ ] does not show up on completed stages
- [ ] starting a timebox sends a slack message to the team
- [ ] updating the timebox updates the slack message iff it was the last message on the channel, otherwise, it creates a new message

NOTIFICATIONS
Either i created a new notification using old non-modular patterns, or i refactored all the previous notifications. i did the latter, so we need to test each.
- [ ] each type of notification displays correctly

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review & style tweaks!

**Comment by ackernaut** [comment]
Looking at this now…I’ll review before any code changes on my part, and write a checklist for styles. Then I’ll address styles for a final review.

**Comment by mattkrick** [comment]
forgot about the demo... guess we should build this into it, too.

**Comment by ackernaut** [comment]
### Test Cycle No. 1
**Note**: running a test cycle before any code changes for styles etc.

TEAM INTEGRATIONS
- [ ] a next stage ready team notification exists
- [ ] a stage time limit reached user notification exists
- [ ] adding a brand new slack integration sets all the notification types on by default
- [ ] teams with existing integrations get both new notifications turned on automatically
- [ ] turn off all team notifications & hit refresh & then turn 1 on, it works (bugfix)

REFLECT, GROUP, VOTE, DISCUSS PHASE
- [ ] clicking the timer > timebox tab shows a send-to-slack checkbox
- [ ] cannot set the timebox to a time that's before right now
- [ ] as a user without slack set up, click the checkbox. it opens the slack oauth & then sets the checkbox after it completes
- [ ] after setting the timebox for a time that is more than 10 minutes in the future, a scheduled job is created. can verify with `r.db('actionDevelopment').table('ScheduledJob')`
- [ ] update the job to run in the next 2 minutes with `r.db('actionDevelopment').table('ScheduledJob').update({runAt: new Date(Date.now() + 1000 * 60 * 2)})`
- [ ] in graphiql on the private schema, run `mutation { runScheduledJobs(seconds: 120) }`, which is what action-chronos would call
- [ ] receive a slack notification in < 2 minutes
- [ ] clear the timebox, set a new one without the slack checkbox set. repeat steps above, receive an in-app notification in 2 minutes
- [ ] navigating the meeting forward removes the scheduled job (and any in-app notifications)
- [ ] does not show up on completed stages
- [ ] navigating the meeting forward sends a slack message to the team channel iff timebox was used in the previous stage

NOTIFICATIONS
Either i created a new notification using old non-modular patterns, or i refactored all the previous notifications. i did the latter, so we need to test each.
- [ ] each type of notification displays correctly

**Comment by ackernaut** [comment]
Documenting a few local errors:
- `TeamSubscription case fail AddSlackAuthPayload` **seen** by another user when adding Slack
- `Atmosphere.ts:31 Captured error: ReferenceError: ConnectionHandler is not defined
    at handleAddNotification (handleAddNotifications.ts:18)` **for any notif event**, have to refresh other user to see notif

**Comment by ackernaut** [comment]
### Style Checklist (WIP)
- [ ] Resolved select dropdown toggles styles (outlined vs. flat)
- [ ] Resolved bottom bar layout when the timer control is absent (need a placeholder or controls follow space-between and primary controls are no longer centered)
- [ ] General grid alignment polished (gutters, margins/padding)

**Comment by ackernaut** [comment]
### Timer clearing UX
#### Steps
- Start a timer in a phase or stage
- Go to the next phase or stage before the timer ends
- When you go back you see that the timer starts over
- The timer control is not there
#### Suggested criteria
- End the running timer when the phase is completed, and (no change) the timer control is no longer there
- End the running timer when the stage  is completed (e.g. Discuss, could see the same for Agenda, maybe another phase), but leave the timer control in case the team wants to go back to an item

**Comment by ackernaut** [comment]
Latest:
- I started a test, but we’re going to change some UX so new tests will reflect the changes
- I captured a few errors in a comment above
- I checked off a first checklist for styles
- I think timers need to be ended when running and a phase/stage is completed (see comment above)
- Any way we could bump the menu to the right about 4 or 8 pixels? It’s either right on the the edge of the nav drawer or right on the edge of the viewport. Not sure the cleanest way since that value is calculated. We probably want it 4 or 8 pixels away from the edge of the viewport minimally, globally whether left or right side. I’d be okay with that and it living on the edge of the nav drawer if it’s open.

**Comment by mattkrick** [comment]
> End the running timer when the phase is completed, and (no change) the timer control is no longer there

done

> End the running timer when the stage is completed (e.g. Discuss, could see the same for Agenda, maybe another phase), but leave the timer control in case the team wants to go back to an item

the ability to set a timer on a complete stage but not completed phase is tricky, i'd opt for just keeping the logic the same as above

> bump the menu to the right about 4 or 8 pixels
 bumped 8px

> ConnectionHandler is not defined at handleAddNotification

fixed

other warnings not at issue, they're already fixed up in a future branch

**Comment by ackernaut** [comment]
### Test Cycle No. 2

TEAM INTEGRATIONS
- [ ] a next stage ready team notification exists
- [ ] a stage time limit reached user notification exists
- [ ] adding a brand new slack integration sets all the notification types on by default
- [ ] teams with existing integrations get both new notifications turned on automatically
- [ ] turn off all team notifications & hit refresh & then turn 1 on, it works (bugfix)

REFLECT, GROUP, VOTE, DISCUSS PHASE
- [ ] clicking the timer > timebox tab shows a send-to-slack checkbox
- [ ] cannot set the timebox to a time that's before right now
- [ ] as a user without slack set up, click the checkbox. it opens the slack oauth & then sets the checkbox after it completes
- [ ] after setting the timebox for a time that is more than 10 minutes in the future, a scheduled job is created. can verify with `r.db('actionDevelopment').table('ScheduledJob')`
- [ ] update the job to run in the next 2 minutes with `r.db('actionDevelopment').table('ScheduledJob').update({runAt: new Date(Date.now() + 1000 * 60 * 2)})`
- [ ] in graphiql on the private schema, run `mutation { runScheduledJobs(seconds: 120) }`, which is what action-chronos would call
- [ ] receive a slack notification in < 2 minutes
- [ ] clear the timebox, set a new one without the slack checkbox set. repeat steps above, receive an in-app notification in 2 minutes
- [ ] navigating the meeting forward removes the scheduled job (and any in-app notifications)
- [ ] does not show up on completed stages
- [ ] navigating the meeting forward sends a slack message to the team channel iff timebox was used in the previous stage

NOTIFICATIONS
Either i created a new notification using old non-modular patterns, or i refactored all the previous notifications. i did the latter, so we need to test each.
- [ ] each type of notification displays correctly

**Comment by ackernaut** [comment]
### Notes on Test Cycle No. 2 (WIP)
- This is really nice work!
- WIP Testing all notifications
- [ ] Fix Archive Team notification: the iconic check button doesn’t clear the notif, have to hit toast or Clear All
- [ ] Consider enhancing: for timebox I pick a date and time in the future say 3pm tomorrow, then I pick today and 3pm is still selected but it is actually 4pm right now. If I hit start I get an error. It would be nice if the time automatically updated to the nearest available time. Probably an edge case, can consider fixing that up later.
- [ ] Error message doesn’t expand height of tabbed content area
Screenshot 2019-06-21 16 13 47

**Comment by ackernaut** [comment]
@mattkrick this is looking really good, see the comment above:

- 2 in-app notifications had issues
- 2 in-app notifs, I wasn’t sure the best way to test, not apparent how the new one works
- Your decision on how to handle the date/time handling when picking today and the time is passed
- Can you refresh the layout of the tab content switcher?

Feel free to merge when you get those where you want it, nice work 👌

**Comment by mattkrick** [comment]
great test!

>Payment rejected

i'd just create a mock on the front end. thankfully i had one left over from the payment rejected bug, so i tested that one!

>  Meeting phase ended

I think this is MEETING_STAGE_TIME_LIMIT_END? that's the one we just added. just untick the slack box and then it should create the in-app notification

>  Team archived

fixed!

> Promoted to Billing Leader

fixed! (not sure why relay didn't fix this one. definitely a bug in there!)

> Consider enhancing: for timebox I pick a date and time in the future say 3pm tomorrow, then I pick today and 3pm is still selected but it is actually 4pm right now. If I hit start I get an error. It would be nice if the time automatically updated to the nearest available time

fixed, set to ~1 hour from now

>  Error message doesn’t expand height of tabbed content area

fixed-ish. moved to above the button & used a negative margin so nothing gets clipped. resizing would be a pain (3rd party package uses old context & i don't wanna PR it)

**Pull request merged**
