### PR TITLE
Add retro templates

### PR DESCRIPTION
**Pull request by mattkrick**
burndown
- [x] migration
- [x] backend on create team
- [x] add menu in lobby
- [x] make menu multiplayer
- [x] add modal
- [x] for every server mutation, make sure the payload returns an option item (since it could be an error).
- [x] for every payload resolver fn, make sure the source value exists before calling dataloader (dataloader throws an error, perhaps we can catch it earlier in rethinkDataloader)
- [x] DND sorting
- [x] styles
- [x] discuss reflection cards have prompt footer

TEST - TEMPLATES
- [ ] can change templates from dropdown & browser 2 sees change
- [ ] can add a new template
- [ ] cannot add more than 20 templates
- [ ] cannot add 2 templates in a row (name error)
- [ ] can rename a template
- [ ] cannot use the same name twice
- [ ] name cannot be blank
- [ ] name cannot be larger than 100 chars
- [ ] can delete a template
- [ ] cannot delete the last template
- [ ] when deleted, browser 2 sees a new selected template

TEST - PROMPTS
- [ ] can add a prompt
- [ ] each prompt added has an incrementing number suffix
- [ ] cannot add more than 5 prompts
- [ ] can rename a prompt
- [ ] cannot be blank
- [ ] cannot be larger than 100 chars
- [ ] cannot be the same name as another prompt
- [ ] when editing a new prompt, the whole field is selected when you click
- [ ] when editing an existing prompt, the caret appears at the end of the line
- [ ] can delete a prompt
- [ ] cannot delete the last prompt
- [ ] can move a prompt by drag & drop

TEST - MEETING
- [ ] can run a retro meeting with an existing team (after DB migration!)
- [ ] the reflect phase uses the correct prompts
- [ ] can create a brand new team & run a retro

### CODE REVIEW

**Comment by ackernaut** [comment]
I’m making a pass at styles now…very nice progress so far!

**Comment by mattkrick** [comment]
@ackernaut nice work! the errors were primarily caused by writing something like: `isFoo & COLOR`. that's because if `isFoo` is false, then the return value from that statement is `false` instead of `undefined`, and `false` isn't a valid value for something like `color` (although i think emotion handles them the same behind the scenes)

I think we may have to make the sidebar scrollable.
screenshot from 2018-09-11 19-08-12

**Comment by ackernaut** [comment]
@mattkrick thanks for the clarification, I should probably stick with `isFoo ? COLOR : undefined` right? I’ll make another push today. Agree we can probably use the simple `Overflow` styled component for now. And I notice the error messages need some attention.

Also, for now I’ve been setting up the editable component to inherit font size, font weight, and line height. I think the color usage should probably be normalized, but size variation may be necessary by design. If we think of a better pattern we can do so!

**Comment by ackernaut** [comment]
There’s 1 enhancement that I think we should capture for later. It would be slick to be able to use the keyboard to tab and focus on editable fields.

**Comment by ackernaut** [comment]
### Test No. 1 (TA, in progress)
#### TEST - TEMPLATES
- [ ] can change templates from dropdown & browser 2 sees change
- [ ] can add a new template
- [ ] cannot add more than 20 templates
- [ ] cannot add 2 templates in a row (name error)
- [ ] can rename a template
- [ ] cannot use the same name twice
- [ ] name cannot be blank
- [ ] name cannot be larger than 100 chars
- [ ] can delete a template
- [ ] cannot delete the last template
- [ ] when deleted, browser 2 sees a new selected template

#### TEST - PROMPTS
- [ ] can add a prompt
- [ ] each prompt added has an incrementing number suffix
- [ ] cannot add more than 5 prompts
- [ ] can rename a prompt
- [ ] cannot be blank
- [ ] cannot be larger than 100 chars
- [ ] cannot be the same name as another prompt
- [ ] when editing a new prompt, the whole field is selected when you click
- [ ] when editing an existing prompt, the caret appears at the end of the line
- [ ] can delete a prompt
- [ ] cannot delete the last prompt
- [ ] can move a prompt by drag & drop

#### TEST - MEETING
- [ ] can run a retro meeting with an existing team (after DB migration!)
- [ ] the reflect phase uses the correct prompts
- [ ] can create a brand new team & run a retro

**Comment by ackernaut** [comment]
@mattkrick this is very nice work 💯 and the tests reflect the attention to detail 👌

**Pull request merged**
