### PR TITLE
Team dash header (Lobby button! Team settings! and more!)

### PR DESCRIPTION
**Pull request by ackernaut**
- Adds a raised button to *Meeting Lobby*
- New *Team Settings* flat button is over by the team avatars
- Main dash header title is larger
- My Dashboard header, moved the Date and Easter Egg to the far right

[record.it](http://recordit.co/M3lXqqwOVh)
GIF

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick the header doesn’t seem to fully re-render. The button remains focused when switching to settings. Any ideas as to why?

**Comment by mattkrick** [comment]
avatars are lookin a little too stacked 
screen shot 2017-04-06 at 12 48 40 pm

**Comment by mattkrick** [comment]
i'll defer to the rest of the team, but using `//` as a delimiter feels a little dirty maybe a pipe or extra spacing or a line break?

screen shot 2017-04-06 at 12 49 29 pm

**Comment by ackernaut** [comment]
Ah, good catch @mattkrick! and the `//` was just a hipster vibe…I’ll iterate on it. :)

**Comment by ackernaut** [comment]
Thanks for catching these @mattkrick 👍 

screenshot 2017-04-06 15 09 50

screenshot 2017-04-06 15 09 53

**Comment by ackernaut** [comment]
@mattkrick ready for review 👍

**Comment by ackernaut** [comment]
@mattkrick any thoughts on the persistent focus/active state on the Team Settings link when clicking to Team Settings and back to Team Dash?

**Comment by mattkrick** [comment]
the hover highlight thing is tricky. basically, you're using CSS props, which get their marching orders from the DOM, but very little changes in the DOM, just the click handler & the text. So, the DOM thinks its the same element, heck react's vdom probably doesn't unmount `<div>foo</div>` and replace with `<div>bar</bar>` my guess is that it just replaces the content while keeping the tag in place, since that's more efficient. We can explicitly say that they're different elements by putting a key on them. hope that makes sense!

**Comment by ackernaut** [comment]
Makes perfect sense, @mattkrick thanks for clarifying!

**Comment by mattkrick** [comment]
bug on changing team name:
1. go to team settings
2. click team name
3. hit enter or click anywhere outside the name field, anything to blur the field
4. note that the pencil doesn't return

**Comment by ackernaut** [comment]
@mattkrick yeah I see that—not sure what’s up?

**Comment by ackernaut** [comment]
@mattkrick I can reproduce this on production, too—so we can try to fix here, but I don’t think it is a regression from these changes.

**Pull request merged**
