### PR TITLE
Epic 6.5 - Bugfixes

### PR DESCRIPTION
**Pull request by mattkrick**
Fixes all the bugs that can be fixed in a 2 week sprint cycle

### CODE REVIEW

**Comment by jordanh** [comment]
This is the one that's ready to go, ja? Let me run a quick cycle on it...

**Comment by mattkrick** [comment]
Yep! My personal branch has a list of tests, plus Dan's PR.

**Comment by jordanh** [comment]
# Test Cycle Template

**Status:**

## Tests

It:
- [ ] runs migration successfully

**Comment by jordanh** [comment]
# Test Cycle 1

**Status: complete**

## Tests

It:
- [ ] runs migration successfully

**Comment by jordanh** [comment]
## Integration Test Checklist

### Authentication  
- [ ] Can login
- [ ] Can logout

### Team Dashboard
- [ ] Can navigate to Team Dashboard
- [ ] Can create project on Team Dashboard
- [ ] Can create 3 additional Projects on Team Dashboard
- [ ] Can re-assign ownership of Project
- [ ] Can resort priority among 3 Project Cards
- [ ] Can assign new Project status via click
- [ ] Can assign new Project status via drag
- [ ] Can navigate to second team from Team Dashboard
- [ ] Can create Project on second team
- [ ] Can create 3 agenda items on Team Dashboard
- [ ] Can reorder agenda items on Team Dashboard

### Team Dashboard > Archive
- [ ] Can archive 1 Project Card
- [ ] Can navigate to Archive
- [ ] Can restore Project Card

### Team Dashboard > Settings
- [ ] Can navigate to Team Settings
- [ ] Can invite new user by email address
- [ ] Can add Slack integration and channel
- [ ] Can add GitHub integration and repository
  
### Accept Email Invitation
- [ ] New user can accept email invitation

### Team Meeting  
- [ ] Can navigate to Meeting Lobby
- [ ] Can see presence of second Team Member
- [ ] Can start Meeting from Meeting Lobby
- [ ] Can observe Slack meeting start notification on channel
- [ ] Facilitator can lead meeting through Check-In
- [ ] Can create Project Cards on Updates dashboard
- [ ] Participant can follow, diverge and rejoin Facilitator
- [ ] Participant can add agenda item
- [ ] Can reorder agenda items
- [ ] Facilitator can proceed to process Agenda Items
- [ ] Participant can add Project card on Agenda Item
- [ ] Participant can add second Project card on Agenda Item
- [ ] Participant can promote second Project card to GitHub issue
- [ ] Facilitator can proceed through Agenda Items to Last Call
- [ ] Facilitator can end Meeting
- [ ] All Participants can see Meeting Summary
- [ ] All Participants receive email Meeting Summary
- [ ] Can observe Slack meeting stop notification on channel

### My Dashboard
- [ ] Can navigate to My Dashboard
- [ ] Can reassign priority across teams from My Dashboard

### Team Dashboard > Settings > Manage Team
- [ ] Can remove Team Member

**Comment by jordanh** [comment]
## Integration Test Cycle 1

### Authentication  
- [ ] Can login
- [ ] Can logout

### Team Dashboard
- [ ] Can navigate to Team Dashboard
- [ ] Can create project on Team Dashboard
- [ ] Can create 3 additional Projects on Team Dashboard
- [ ] Can re-assign ownership of Project
- [ ] Can resort priority among 3 Project Cards
- [ ] Can assign new Project status via click
- [ ] Can assign new Project status via drag
- [ ] Can navigate to second team from Team Dashboard
- [ ] Can create Project on second team
- [ ] Can create 3 agenda items on Team Dashboard
- [ ] Can reorder agenda items on Team Dashboard

### Team Dashboard > Archive
- [ ] Can archive 1 Project Card
- [ ] Can navigate to Archive
- [ ] Can restore Project Card

### Team Dashboard > Settings
- [ ] Can navigate to Team Settings
- [ ] Can invite new user by email address
- [ ] Can add Slack integration and channel
- [ ] Can add GitHub integration and repository
  
### Accept Email Invitation
- [ ] New user can accept email invitation

### Team Meeting  
- [ ] Can navigate to Meeting Lobby
- [ ] Can see presence of second Team Member
- [ ] Can start Meeting from Meeting Lobby
- [ ] Can observe Slack meeting start notification on channel
- [ ] Facilitator can lead meeting through Check-In
- [ ] Can create Project Cards on Updates dashboard
- [ ] Participant can follow, diverge and rejoin Facilitator
- [ ] Participant can add agenda item
- [ ] Can reorder agenda items
- [ ] Facilitator can proceed to process Agenda Items
- [ ] Participant can add Project card on Agenda Item
- [ ] Participant can add second Project card on Agenda Item
- [ ] Participant can promote second Project card to GitHub issue
- [ ] Facilitator can proceed through Agenda Items to Last Call
- [ ] Facilitator can end Meeting
- [ ] All Participants can see Meeting Summary
- [ ] All Participants receive email Meeting Summary
- [ ] Can observe Slack meeting stop notification on channel

### My Dashboard
- [ ] Can navigate to My Dashboard
- [ ] Can reassign priority across teams from My Dashboard

### Team Dashboard > Settings > Manage Team
- [ ] Can remove Team Member

**Comment by jordanh** [comment]
I am stumped by something silly...

When I `npm run dev` I am getting:

```
1503584519949 - Origin: Worker (PID 25494)
   [Error] Error: Cannot find module '/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/analytics-node/lib/index.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/segmentIo.js:1:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/babel-register/lib/node.js:154:7)
```

I can start node and `require('analytics-node')` just fine. There is a `node_modules/analytics-node/index.js`, but not a `lib/index.js`.

Are you running into the same thing?

**Comment by jordanh** [comment]
Maybe it's this issue?

https://github.com/segmentio/analytics-node/issues/91

**Comment by jordanh** [comment]
Opened #1297

**Comment by jordanh** [comment]
Ok, all is awesome now!

**Pull request merged**
