### PR TITLE
Fix 3263 sidebar scroll

### LINKED ISSUE #3263: Meeting sidebar flex shrink hides many stage nav items
### Repro
- [ ] On a team with 5 folks using a 1280x720 browser window
- [ ] Start an Action meeting with 10 agenda items
- [ ] During the Social Check-In or Solo Updates phases some stage nav items are hidden due to the `flex-shrink` property
- [ ] This probably happens in a Retro if there are many Discuss topics and one goes back to the Social Check-In phase
### AC
- [ ] Use something like `overflow: auto` or `flex-shrink: 0` to phases with team member stage items
### EE
- 10.5 pts

### PR DESCRIPTION
**Pull request by ackernaut**
Fix #3263 

### Test
- [ ] Use a browser window sized roughly 1280x720
- [ ] Be on a team with 5-10 members
- [ ] Have an Action meeting with 10 agenda items
- [ ] Have a Retro meeting with 10 topics
- [ ] The Social Check-In and Solo Update phase stage nav items are still accessible with some scrolling
- [ ] The sidebar layout does not break
- [ ] The Team Agenda and Discuss sidebar sections are usable when the Social Check-In and Solo Update phase sections are expanded

**Note**: this is a quick fix, we should probably design some improvements to the UI behaviors. Most people use the Retro, and probably don’t go back to the Social Check-In stage once they’ve reached the Discuss phase, so they probably won’t run into too much trouble. However on a large enough team the Social Check-In nav section simply won’t be scrollable. The facilitator can advance or use the top-right avatars until #3180 is fixed which may ship when this ships.

During an Action meeting with a large team and a lot of agenda items, with this PR there will be some scrolling in any open section.

### CODE REVIEW

**Comment by mattkrick** [comment]
looks good but needs a `scrollIntoViewIfNeeded`

**Comment by ackernaut** [comment]
That’s a good point, I can look at adding that

**Comment by mattkrick** [comment]
ah no need, will push a PR real quick

**Comment by mattkrick** [comment]
@ackernaut go ahead & give er a go, `scrollIntoVIewIfNeeded` doesn't always animate, so i just used the standard call

**Comment by ackernaut** [comment]
thanks MK! taking a gander…

**Comment by ackernaut** [comment]
LGTM! 👍 thanks again for the addition

**Pull request merged**
