### PR TITLE
Fix auth0 2

### LINKED ISSUE #3024: Mass invitation to action meeting bug
### Repro steps:

User A = member of Parabol
User B = completely new user, no previous Parabol User account

User A started action meeting, and entered check-in round
User A Clicked + to add to team (https://action.parabol.co/team/ryq6Vl0CW), copied mass invite link and sent to User B out of band
User B Clicked mass invite link (x)
User B Created new account

Redirect went here, and then hung

image

Then, tried sending personal invite. Also resulted in same state.

(had to delete users both in auth0 and in DB)​

### Acceptance criteria
A user can:
   * Invite a completely new user from an action meeting, have them sign up and join the meeting

#### Estimated effort: 10.5 points

Edit 1: correct typos, clarifications

### PR DESCRIPTION
**Pull request by mattkrick**
this should fix the problem Tim encountered yesterday. fix #3024
Got rid of the auth0-js lib & wrote some code to hit the endpoints we used.

TEST
- [ ] can sign up w/ password
- [ ] can log in w/ password
- [ ] can log in w/ google
- [ ] a sign up using an existing user is a login
- [ ] a login attempt with password when the user was created with google shows an error saying use google
- [ ] can change password
- [ ] can accept team invite
- [ ] can do everything on an iphone with the safari browser (this is what sentry said was causing most of the errors. auth0 forums confirmed it)

### CODE REVIEW

**Comment by mattkrick** [comment]
@jordanh ready for review!

**Comment by jordanh** [comment]
Looking now

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- [ ] can sign up w/ password
- [ ] can log in w/ password
- [ ] can log in w/ google
- [ ] a sign up using an existing user is a login
- [ ] a login attempt with password when the user was created with google shows an error saying use google
- [ ] can change password
- [ ] can accept team invite
- [ ] can do everything on an iphone with the safari browser (this is what sentry said was causing most of the errors. auth0 forums confirmed it)

**Comment by jordanh** [comment]
@mattkrick hit a couple of snags. Did I not set something up correctly?

**Comment by mattkrick** [comment]
that's really, really weird. will dig in

**Comment by mattkrick** [comment]
ok, ready for another go

**Comment by mattkrick** [comment]
merging to master & deploying during SPA

**Pull request merged**
