### PR TITLE
fix tasks

### PR DESCRIPTION
**Pull request by mattkrick**
When fixing #3046 i noticed i couldn't delete a card all the time. the fix was pretty lengthy, but while i was at it i learned that it was the root cause of a sentry bug that i didn't know how to reproduce, so thought it was worthwhile to fix up since it requires a refresh to get back to a usable state.

TEST
- [ ] cannot repro #3046 masonry bug
- [ ] during a discuss phase, create a card, then highlight the text, delete it & blur the card. the card is deleted for all parties
- [ ] set a due date on a task. an icon exists to move forward to next month (depended on font awesome, regression when FA was removed)
- [ ] can click around a card, jump from menu to menu, etc & the "Editing..." header is always accurate
- [ ] can add/edit a link to a card, "Editing..." is accurate

edit: TESTS for ***SAFARI*** 
- [ ] long agenda scrolls correctly in dash. DND also works without error or warning
- [ ] long agenda scrolls correctly in action meeting. DND also works without error or warning
- [ ] many discussion topics scroll correctly in discuss phase sidebar. DND also works without error or warning

### CODE REVIEW

**Comment by jordanh** [comment]
Looking at this now

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests

- [ ] cannot repro #3046 masonry bug
- [ ] during a discuss phase, create a card, then highlight the text, delete it & blur the card. the card is deleted for all parties
- [ ] set a due date on a task. an icon exists to move forward to next month (depended on font awesome, regression when FA was removed)
- [ ] can click around a card, jump from menu to menu, etc & the "Editing..." header is always accurate
- [ ] can add/edit a link to a card, "Editing..." is accurate
- [ ] can smoketest demo

**Comment by jordanh** [comment]
@mattkrick found something to dig into!

**Comment by mattkrick** [comment]
@jordanh couldn't reproduce, but I got rid of something i think might have triggered it.
ready for another pass!

**Comment by jordanh** [comment]
on it now!

**Comment by jordanh** [comment]
N.B. still saw some funkiness. Contacted @mattkrick directly. He's taking another turn.

**Comment by mattkrick** [comment]
@jordanh ready for another pass!
bit the bullet & just refactored to react-beautiful-dnd. really happy i did. kanban is lookin fresh now.

**Comment by ackernaut** [comment]
### Test Cycle No. 2
TEST
- [ ] cannot repro #3046 masonry bug
- [ ] during a discuss phase, create a card, then highlight the text, delete it & blur the card. the card is deleted for all parties
- [ ] set a due date on a task. an icon exists to move forward to next month (depended on font awesome, regression when FA was removed)
- [ ] can click around a card, jump from menu to menu, etc & the "Editing..." header is always accurate
- [ ] can add/edit a link to a card, "Editing..." is accurate


edit: TESTS for ***SAFARI*** 
- [ ] long agenda scrolls correctly in dash
- [ ] long agenda scrolls correctly in action meeting
- [ ] many discussion topics scroll correctly in discuss phase sidebar

**Comment by mattkrick** [comment]
> The new DND for task columns is slick but not sure how we want to handle layout. Currently there is a LTR scrolling container for all of the columns, and then each column scrolls. This triggers the warning.

we'll just ride dirty for the time being. seems to work OK, just an ugly warning. to fix this, we'll need to make columns swipeable or make the whole thing scroll a little nicer

still workingon the reflection animation

i can't do much on safari, but if you can get it to break in chrome or FF i can help!

**Comment by ackernaut** [comment]
@mattkrick I’m able to tap on all 3 stacks of reflection cards now in Chrome for both a real retro and the demo. As for Safari, the only thing I’m seeing consistently is that once I’ve tapped on a stack of cards to open the modal, when I close it the stack disappears. The `visibility: hidden` style remains on the `div` instead of clearing.

**Comment by ackernaut** [comment]
Concerning Safari, when I log into production today the agenda list has scrolling and the reflect phase stacks work as intended. I guess the flex bug didn’t affect Safari for scrolling the agenda and we should check for known Safari issues related to whatever changes happened in the reflect columns since last release.

**Comment by ackernaut** [comment]
On Firefox, I’m seeing that the bottom bar gets pushed down in the Discuss phase when there are enough tasks created to push it down. I’m unable to scroll the tasks container, whereas I can scroll in Chrome.

**Comment by ackernaut** [comment]
### Dragging cards but selecting text
In production when I hover over the content of a card I get the `text` cursor but now I see the `grab` cursor but it still focuses and/or selects the text. Can we get that `text` cursor back?

**Comment by ackernaut** [comment]
I noticed that the task columns have equal distance between cards on both axes. It was intentional to have less gutter between cards in a column and more gutter between columns. I haven’t poked at where those gutters are set in the new DND columns. Here’s what we had in the task card guidelines:
>Columns have a 24px gutter (horizontally) between columns and a 12px gutter (vertically) between cards in a column

**Comment by ackernaut** [comment]
### My Dashboard > Tasks
In prod these task columns scroll while the viewport height is fixed. On this branch, the entire tasks view scrolls, and the tabs scroll away. Is this intentional or a trade-off for scrolling behaviors?

**Comment by mattkrick** [comment]
ok, i think that's everything!
overall they were some pretty substantial changes.
the general strategy is this:
- the root div has a height of 100vh
- every div below that has height: 100%, 
- by having a height 100% that can climb up to a block container that has a defined height (100vh), we can use `overflow: auto` without weird `position: absolute` hacks or similar

this has a side effect of fixing the dashboard views for mobile layouts

**Comment by mattkrick** [comment]
@ackernaut ready for a review in the mornin

**Comment by ackernaut** [comment]
### Test Cycle No. 3 ✨ 
TEST
- [ ] cannot repro #3046 masonry bug
- [ ] during a discuss phase, create a card, then highlight the text, delete it & blur the card. the card is deleted for all parties
- [ ] set a due date on a task. an icon exists to move forward to next month (depended on font awesome, regression when FA was removed)
- [ ] can click around a card, jump from menu to menu, etc & the "Editing..." header is always accurate
- [ ] can add/edit a link to a card, "Editing..." is accurate

edit: TESTS for ***SAFARI*** 
- [ ] long agenda scrolls correctly in dash. DND also works without error or warning
- [ ] long agenda scrolls correctly in action meeting. DND also works without error or warning
- [ ] many discussion topics scroll correctly in discuss phase sidebar. DND also works without error or warning

plus: Tests for fixes
- [ ] mass invite link works
- [ ] overflow works on my tasks
- [ ] overflow works on discuss phase
- [ ] reflection stack works on Safari

**Comment by ackernaut** [comment]
### Missing card in reflection stack
- Add 1 card, it disappears
- Add 2nd card, it disappears, but the first card appears
- Add 3rd card, it disappears, but the first two are visible
- Remove 2 cards, and 1 card remains visible
- Note: it seems Safari is fixed, but both Safari and Chrome have this new behavior

**Comment by ackernaut** [comment]
### Team dash layout is wider
Since removing the inner scrollable container on the task columns, now the whole team dash scrolls independent of the left nav. This puts the Start Meeting button and the agenda list out of view for smaller laptop screens (screenshot below at 1366x768). It’s not immediately apparent that you need to scroll.

Screenshot 2019-08-15 11 09 45

**Comment by ackernaut** [comment]
### My tasks and team dash views in Firefox
Both of these views scroll on both axes with a small laptop viewport and many tasks in a single column. The dash header and column header components scroll out of view.

Screenshot 2019-08-15 11 26 33

**Comment by ackernaut** [comment]
### Still editing after selecting a due date
After selecting a due date the card stays at a raised elevation and has the “editing…” hint.

Screenshot 2019-08-15 11 32 38

**Comment by ackernaut** [comment]
### Demo discuss phase error creating task card
Advance to the Discuss phase and tap the Add Card control before the bot begins to add a card. You should see the fatal dev error. If you refresh you’ll probably see an empty card that won’t go away.

**Comment by ackernaut** [comment]
### Dragging cards shows over vote phase
If you advance to the Vote phase before the bots are done dragging, you may see some cards that are stuck in a dragging state. It seems this is the first phase where I see any number of instances of this warning `Encountered two children with the same key`. It looks like that warning shows up in the Discuss phase, too.

**Comment by mattkrick** [comment]
beginning fixes for test cycle 3 now

**Comment by mattkrick** [comment]
> Missing card in reflection stack
- not sure i totally understand, but i did some something funky & fixed it. @ackernaut please retest & see if it works!

> Team dash layout is wider

- great catch! scroll is now on the kanban. & min-width is now on the tasks themselves. this has the side effect of reducing the width of empty columns to just the header width when space is needed. i think this looks better, but i'll let you decide.

> My tasks and team dash views in Firefox
 silly firefox flex

> Still editing after selecting a due date

another great find. also realized there was a regression where you can't edit the due date of a card before entering text, so i fixed that, too.


 > Demo discuss phase error creating task card

whoa, how long has this been a thing?

> Dragging cards shows over vote phase

no more fast forwarding it is!

**Comment by mattkrick** [comment]
@ackernaut ready for another go. thanks for the in depth QA!

**Comment by mattkrick** [comment]
feeling good about this, gonna move it to staging & we can fix up any other bugs there. hope to get this in prod tomorrow morning

**Pull request merged**
