### PR TITLE
Refactor Action Meeting (except summary)

### PR DESCRIPTION
**Pull request by mattkrick**
NOTE: Don't use this branch for testing, just use it for code review. Run tests on `fix-summary-email`, since you can test the summary portion, too.

TEST - Dashboard
- [ ] start an action meeting, go back to Dash, the Dash Alert link goes to the Action meeting
- [ ] start an action meeting, go back to Dash, the dash modal goes to the Action meeting
- [ ] Go to Timeline, click an old action meeting, it works
- [ ] Complete an action meeting, Go to Timeline, click a new action meeting, it works

TEST - Action Meeting Lobby
- [ ] The lobby looks good
- [ ] The avatar group looks good
- [ ] Can add agenda items
- [ ] Can sort agenda items
- [ ] Cannot go to any of the phases or agenda items (disabled cursor)

TEST - Action Meeting Check In
- [ ] Can check someone in using h/n keys. Pressing the key auto-advances
- [ ] Can check someone in pressing the button
- [ ] Can navigate back by pressing using the avatar group
- [ ] Can edit the checkin question
- [ ] Can invite someone from the checkin phase
- [ ] when someone joins the team while the meeting is in progress, they get appended to the team member list in the avatar group
- [ ] Be on the checkin phase for the new person. In another tab, remove them from the org while a meeting is in progress. The meeting advances to the next person (or phase, if they were the last one)
- [ ] a user without access to the team goes to `http://localhost:3000/meeting/:teamId/checkin`. They see the invitation-required diaglog
- [ ] when a team member invites the user sitting on the invitation-required page, the page redirects to the meeting

TEST - Action Meeting Updates
- [ ] Can add a task
- [ ] Other meeting participants see the task added
- [ ] Can remove a task
- [ ] Other participants see it removed
- [ ] Can move a task
- [ ] Other participants see it moved
- [ ] Tasks for that team member are the only ones that show up

TEST - Action Meeting First Call
- [ ] Can press + to focus the agenda item input
- [ ] Can re-order the agenda items
- [ ] Stage looks good

TEST - Action Meeting Agenda Items
- [ ] Can delete the current item. The meeting url stays the same but the next agenda item is active
- [ ] Can drag an item above the current item. The url changes to match the order
- [ ] Can add an item, drag it to just below the current item, then press the next arrow 2x to advance to it

TEST - Action Meeting Last Call
- [ ] looks good

TEST - Action Meeting Summary
- OUT OF SCOPE. See next PR

TEST - Retro Meeting
- [ ] Retro meeting works as intended.

TEST - Demo
- [ ] Demo meeting works as intended

TEST - User Dash
- [ ] Can create new task
- [ ] Can assign to another team
- [ ] can drag to another column

TEST - Team Dash
- [ ] Can create new task
- [ ] Can assign to another teammember
- [ ] can drag to another column

### CODE REVIEW

**Comment by mattkrick** [comment]
Notes:
- segment event changed from "Retro Meeting Completed" to "retrospective Meeting Completed" (uses proper name)
- meeting summary doesn't snapshot tasks. Before, action meetings would clone tasks so the summary would show the state as they were created. Now, they update to the current value (same as retros)

**Comment by ackernaut** [comment]
### Test Cycle No. 1

**Note**: testing locally on branch `fix-summary-email`

TEST - Dashboard
- [ ] start an action meeting, go back to Dash, the Dash Alert link goes to the Action meeting
- [ ] start an action meeting, go back to Dash, the dash modal goes to the Action meeting
- [ ] Go to Timeline, click an old action meeting, it works
- [ ] Complete an action meeting, Go to Timeline, click a new action meeting, it works

TEST - Action Meeting Lobby
- [ ] The lobby looks good
- [ ] The avatar group looks good
- [ ] Can add agenda items
- [ ] Can sort agenda items
- [ ] Cannot go to any of the phases or agenda items (disabled cursor)

TEST - Action Meeting Check In
- [ ] Can check someone in using h/n keys. Pressing the key auto-advances
- [ ] Can check someone in pressing the button
- [ ] Can navigate back by pressing using the avatar group
- [ ] Can edit the checkin question
- [ ] Can invite someone from the checkin phase
- [ ] when someone joins the team while the meeting is in progress, they get appended to the team member list in the avatar group
- [ ] Be on the checkin phase for the new person. In another tab, remove them from the org while a meeting is in progress. The meeting advances to the next person (or phase, if they were the last one)
- [ ] a user without access to the team goes to `http://localhost:3000/meeting/:teamId/checkin`. They see the invitation-required diaglog
- [ ] when a team member invites the user sitting on the invitation-required page, the page redirects to the meeting

TEST - Action Meeting Updates
- [ ] Can add a task
- [ ] Other meeting participants see the task added
- [ ] Can remove a task
- [ ] Other participants see it removed
- [ ] Can move a task
- [ ] Other participants see it moved
- [ ] Tasks for that team member are the only ones that show up

TEST - Action Meeting First Call
- [ ] Can press + to focus the agenda item input
- [ ] Can re-order the agenda items
- [ ] Stage looks good

TEST - Action Meeting Agenda Items
- [ ] Can delete the current item. The meeting url stays the same but the next agenda item is active
- [ ] Can drag an item above the current item. The url changes to match the order
- [ ] Can add an item, drag it to just below the current item, then press the next arrow 2x to advance to it

TEST - Action Meeting Last Call
- [ ] looks good

TEST - Action Meeting Summary
- OUT OF SCOPE. See next PR

TEST - Retro Meeting
- [ ] Retro meeting works as intended.

TEST - Demo
- [ ] Demo meeting works as intended

TEST - User Dash
- [ ] Can create new task
- [ ] Can assign to another team
- [ ] can drag to another column

TEST - Team Dash
- [ ] Can create new task
- [ ] Can assign to another teammember
- [ ] can drag to another column

**Comment by ackernaut** [comment]
@mattkrick made a first cycle and left a link to the Google doc

**Comment by ackernaut** [comment]
### Test Cycle No. 2

**Note**: testing locally on branch `fix-summary-email`

TEST - Dashboard
- [ ] start an action meeting, go back to Dash, the Dash Alert link goes to the Action meeting
- [ ] start an action meeting, go back to Dash, the dash modal goes to the Action meeting
- [ ] Go to Timeline, click an old action meeting, it works
- [ ] Complete an action meeting, Go to Timeline, click a new action meeting, it works

TEST - Action Meeting Lobby
- [ ] The lobby looks good
- [ ] The avatar group looks good
- [ ] Can add agenda items
- [ ] Can sort agenda items
- [ ] Cannot go to any of the phases or agenda items (disabled cursor)

TEST - Action Meeting Check In
- [ ] Can check someone in using h/n keys. Pressing the key auto-advances
- [ ] Can check someone in pressing the button
- [ ] Can navigate back by pressing using the avatar group
- [ ] Can edit the checkin question
- [ ] Can invite someone from the checkin phase
- [ ] when someone joins the team while the meeting is in progress, they get appended to the team member list in the avatar group
- [ ] Be on the checkin phase for the new person. In another tab, remove them from the org while a meeting is in progress. The meeting advances to the next person (or phase, if they were the last one)
- [ ] a user without access to the team goes to `http://localhost:3000/meeting/:teamId/checkin`. They see the invitation-required diaglog
- [ ] when a team member invites the user sitting on the invitation-required page, the page redirects to the meeting

TEST - Action Meeting Updates
- [ ] Can add a task
- [ ] Other meeting participants see the task added
- [ ] Can remove a task
- [ ] Other participants see it removed
- [ ] Can move a task
- [ ] Other participants see it moved
- [ ] Tasks for that team member are the only ones that show up

TEST - Action Meeting First Call
- [ ] Can press + to focus the agenda item input
- [ ] Can re-order the agenda items
- [ ] Stage looks good

TEST - Action Meeting Agenda Items
- [ ] Can delete the current item. The meeting url stays the same but the next agenda item is active
- [ ] Can drag an item above the current item. The url changes to match the order
- [ ] Can add an item, drag it to just below the current item, then press the next arrow 2x to advance to it

TEST - Action Meeting Last Call
- [ ] looks good

TEST - Action Meeting Summary
- OUT OF SCOPE. See next PR

TEST - Retro Meeting
- [ ] Retro meeting works as intended.

TEST - Demo
- [ ] Demo meeting works as intended

TEST - User Dash
- [ ] Can create new task
- [ ] Can assign to another team
- [ ] can drag to another column

TEST - Team Dash
- [ ] Can create new task
- [ ] Can assign to another teammember
- [ ] can drag to another column

**Comment by ackernaut** [comment]
Ran another test cycle through to Last Call

**Comment by ackernaut** [comment]
Making a small (10.5 pts) checklist of UI details to implement after we fix bugs: https://github.com/ParabolInc/action/issues/2886

**Comment by ackernaut** [comment]
Here’s an issue for removing First/Last call, initially sticking **#design** and **#discussion** on it: https://github.com/ParabolInc/action/issues/2887

**Comment by mattkrick** [comment]
> Alert bar doesn’t show until hard refresh

fixed!

>  a participant can’t nav ahead to the last stage of the Check-In phase, this seems to be a regression

assuming this is just for participants that were added after the meeting started. fixed!

> Be on the checkin phase for the new person. In another tab, remove them from the org while a meeting is in progress. The meeting advances to the next person (or phase, if they were the last one)

can't reproduce @ackernaut  here are the steps I took: User A invites User B to team. User A starts meeting. User A advances to /checkin/2 and is looking at User B. In tab 2, User A removes User B from the org. User B gets redirected to /me, User A in tab 1 gets redirected to /updates/1. 

>Tap “End Meeting” before reaching Team Agenda with at least 1 agenda item in the list, the meeting is ended early and the agenda item is still there, hard refresh and it goes away

i think the agenda items should probably stick around if they were never processed. fixed!

**Comment by mattkrick** [comment]
closing in favor of fix-summary-email

**Pull request closed without merging**
