### PR TITLE
Draftjs

### PR DESCRIPTION
**Pull request by mattkrick**
Burndown:
- [x] migrate the new user cards
- [x] archive with button, make private with button
- [x] autofocus on new cards
- [x] add padding & styles to draft editor
- [x] unarchive project programmatically
- [x] fix isEditing
- [x] derive tags from entityState
- [x] remove card on blur
- [x] save content on drag start
- [x] scroll codeblock
- [x] pasted text
- [x] refactor renderModal to just get editorState from props
- [x] migrate entity strings into entities
- [x] check all server DB code that changes content
- [x] remove # from the tags array in migration
- [x] use ` as an escape for markdown
- [x] handle #archived correctly, remove #
- [x] normalized tags (ie do they start with # or not)
- [x] getEndMeetingSortOrder tags (search for #archived, #private)
- [x] remove entities from emojis. using unicode should suffice & if we want to move to universal emojis, then we can just regex all emojis.

Tests:
  - #1041
  - #1042
  - #1043
  - #1044
  - #1045
  - #1046

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle Template

## Title & Content (#1075)
- [ ] when making a new card, autofocuses the title
- [ ] when making a new card, adequate placeholders appear
- [ ] can `tab` and `shift + tab` between the two fields
- [ ] in title, only plaintext is allowed
- [ ] in title, has 140 character maximum
- [ ] in content, has 512 character maximum

## WYSISYG core features (#1042)

### Link formatting
- [ ] after typing a valid url, it becomes a hyperlink when you hit space
- [ ] after linkifying a typed url, hitting backspace removes the hyperlink
- [ ] after any keypress other than backspace, the hyperlink stays & hitting backspace acts normally
- [ ] when another modal is open, hitting space makes the modal go away
- [ ] if the caret is at the end of the link and you hit space, the link will not continue
- [ ] if the caret is in the middle of the link and you hit space, the link will continue

### Link Viewer
- [ ] if the cursor is inside or at the end of a hyperlink, the LinkViewer modal shows
- [ ] if you're at the end of a hyperlink and hit space, the LinkViewer goes away
- [ ] when the LinkViewer is open and you click another link, the url changes
- [ ] when the LinkVIewer is open and you click a non-link, the modal goes away
- [ ] when the LinkViewer is open and you click to the right of a trigger (`: @ #`) the suggestion modal pops up
- [ ] when the suggestion modal is active and you click inside a hyperlink, the LinkViewer shows up
- [ ] when you navigate to a hyperlink via left/right arrows, the LinkViewer pops up
- [ ] when you navigate away from a hyperlink via left/right arrows, the LinkViewer goes away
- [ ] hitting esc closes the modal
- [ ] clicking the url in the modal opens it in a new tab
- [ ] clicking remove removes the url from the highlighted area
- [ ] clicking change pops up the LinkChanger

### Link Changer
- [ ] when the selection is collapsed on a blank line, hitting ctrl+k and filling out the form creates a new link & puts the caret directly after the new word & the LinkViewer pops up.
- [ ] when the selection is collapsed at the end of the text, hitting ctrl+k and filling out the form creates a new link and the caret is placed after the last letter
- [ ] when the selection is collapsed in the middle or to the right of a word, hitting ctrl+k will autofill the text with the word and clicking Add will replace the word the text + link and the caret will be at the end of the word
- [ ] when the selection spans 2+ blocks, the LinkChanger does not have a text field, but the hyperlink is applied to each character in the selection
- [ ] when the selection is not collapsed but only spans 1 block, the entire selected area is set at the default for the text
- [ ] when the selection is within a link, the href and text is autopopulated
- [ ] when the selection includes 1 or more links, grab the right-most link as the default.
- [ ] hitting esc closes the modal
- [ ] the modal pops up at the beginning of the line if ctrl+k is hit on a blank line (addresses bug in https://github.com/facebook/draft-js/issues/45)
- [ ] when a substring of a link is highlighted & changed, only that selection is edited

## Pasted markdown (#1041)

- [ ] `_a_` is italic
- [ ] `*a*` is italic
- [ ] `__a__` is bold
- [ ] `**a**` is bold
- [ ] `__*a*__` is bold italic
- [ ] `__*~a~*__` is bolid italic strikethough
- [ ] `` `__*~a~*__` `` is bolid italic strikethough code 
- [ ] hitting backspace does the same thing as undo
- [ ] undo undoes the styling, but does not move the char back
- [ ] a split block (enter, shift+enter) or space triggers the markdown
- [ ] for split block, the style does not follow onto the next line
- [ ] `  >  ` turns it into a blockquote after space is hit
- [ ] `` ``` ``  makes code blocks (we can style these later)
- [ ] `[name](foo.co)` turns into a hyperlink

## User Mentioned (#1043)

- [ ] Pressing `@` triggers autocomplete with team members listed (showing avatar and preferredName).
- To select a team member from the list:
  - [ ] Users can tap a list item
  - [ ] Users can press `up` or `down` and `enter`
  - [ ] Users can type to autocomplete by `preferredName` and press `enter`
- [ ] Tapping the inline user mention reveals an inline menu with a flat button `Remove Mention`
- [ ] Backspacing once (after the name) shows the `Remove Mention` menu. Backspacing again removes the mention from the user, but leaves the `preferredName` as plain text

## Tags (#1044)
- [ ] hitting the trigger immediately pops up the suggestion modal
- [ ] hitting backspace to remove the trigger removes the suggestion modal
- [ ] clicking into a word that begins with the trigger pops up the suggestion modal & the suggestion query includes the whole word
- [ ] hitting tab autocompletes with the highlighted suggestion
- [ ] hitting enter is same as tab
- [ ] hitting up/down arrows move the selection
- [ ] clicking on a suggestion autocompletes
- [ ] hitting the "archive" button adds a new line that says #archive to the bottom of the card
- [ ] hitting "unarchive" removes ALL instances of the word archive & all entities.
- [ ] hitting "unarchive" removes appropriate whitespace before/after the word `#archived`
- [ ] hitting "unarchive" removes any blank lines (ie the line that used to say `#archived`)

## Emoji (#1046)
- [ ] An emoji menu triggered by pressing colon `:`
  - [ ] users can type keywords and we suggest
  - [ ] users can arrow and select emoji with enter
- [ ] Users can paste/insert emoji from standard OS keyboards (Mac OS, iOS, Android, etc.)

**Comment by jordanh** [comment]
Questions @mattkrick:
- Does the above in general look right and complete?
- What does the migration do? (what are entity strings?)
- How does the backtick ` markdown quoting work?

**Comment by mattkrick** [comment]
- yep, above looks correct
- the migration changes a plaintext string to a stringified object. So entities are a way to store data on a piece of text. for example, if i say `@jordanH`. then that string will get replaced with the text `Jordan Husney` and an entity will be assigned to each character of that string. that entity holds an object that tells you how you can modify it (if you hit backspace, does it delete `Jordan Husney` `Husney` or `y`?). It also stores any user-defined data (eg `{userId: '123'}`). That way, we can create generic rules, eg if you click a tag, filter the kanban board by `tag.data.value`. 
- the backtick regex right now turns stuff to code. i think what i need to do is treat at a higher level so if you try to `**bold**` some code, instead of making bold code, it shows stars.

**Comment by ackernaut** [comment]
Not sure where/how we want to create a list of issue. Perhaps an “Issues” heading with # mentions?

Here’s what I got so far:

- [ ] Fix #1076 
- [ ] Fix #1077

**Comment by ackernaut** [comment]
@jordanh @mattkrick shall I begin checking off things that work from the large test list?

**Comment by ackernaut** [comment]
How do we want to handle the case where users type `www.example.co` or `example.co` as the link (it doesn’t trigger a validation error)? Currently this string gets appended to the current URL (which is our app of course).

http://recordit.co/sTmV8d8LJ9

**Comment by jordanh** [comment]
@ackernaut "two things"

1. When you run a test cycle, copy the template and add a new comment. Change the title to "Test Cycle n" where `n` is the number of times we've run a test. That'll help us catch regressions

2. Google Docs seems to default to prepending `http://` which I think is safe to try

**Comment by mattkrick** [comment]
these are good! i'll fix em up. should we invest the time in writing unit tests now?

**Comment by jordanh** [comment]
# Test Cycle 1 – by @ackernaut 

## Title & Content (#1045)
- [ ] when making a new card, autofocuses the title
- [ ] when making a new card, adequate placeholders appear
- [ ] can `tab` and `shift + tab` between the two fields
- [ ] in title, only plaintext is allowed
- [ ] in title, has 140 character maximum
- [ ] in content, has 512 character maximum

## WYSISYG core features (#1042)

### Link formatting
- [x] after typing a valid url, it becomes a hyperlink when you hit space
- [x] after linkifying a typed url, hitting backspace removes the hyperlink
- [x] after any keypress other than backspace, the hyperlink stays & hitting backspace acts normally
- [ ] when another modal is open, hitting space makes the modal go away
- [x] if the caret is at the end of the link and you hit space, the link will not continue
- [x] if the caret is in the middle of the link and you hit space, the link will continue

### Link Viewer
- [x] if the cursor is inside or at the end of a hyperlink, the LinkViewer modal shows
- [x] if you're at the end of a hyperlink and hit space, the LinkViewer goes away
- [x] when the LinkViewer is open and you click another link, the url changes
- [x] when the LinkVIewer is open and you click a non-link, the modal goes away
- [x] when the LinkViewer is open and you click to the right of a trigger (`: @ #`) the suggestion modal pops up
- [x] when the suggestion modal is active and you click inside a hyperlink, the LinkViewer shows up
- [x] when you navigate to a hyperlink via left/right arrows, the LinkViewer pops up
- [x] when you navigate away from a hyperlink via left/right arrows, the LinkViewer goes away
- [x] hitting esc closes the modal
- [x] clicking the url in the modal opens it in a new tab
- [ ] clicking remove removes the url from the highlighted area
- [x] clicking change pops up the LinkChanger

### Link Changer
- [ ] when the selection is collapsed on a blank line, hitting ctrl+k and filling out the form creates a new link & puts the caret directly after the new word & the LinkViewer pops up.
- [ ] when the selection is collapsed at the end of the text, hitting ctrl+k and filling out the form creates a new link and the caret is placed after the last letter
- [ ] when the selection is collapsed in the middle or to the right of a word, hitting ctrl+k will autofill the text with the word and clicking Add will replace the word the text + link and the caret will be at the end of the word
- [ ] when the selection spans 2+ blocks, the LinkChanger does not have a text field, but the hyperlink is applied to each character in the selection
- [ ] when the selection is not collapsed but only spans 1 block, the entire selected area is set at the default for the text
- [ ] when the selection is within a link, the href and text is autopopulated
- [ ] when the selection includes 1 or more links, grab the right-most link as the default.
- [ ] hitting esc closes the modal
- [ ] the modal pops up at the beginning of the line if ctrl+k is hit on a blank line (addresses bug in https://github.com/facebook/draft-js/issues/45)
- [ ] when a substring of a link is highlighted & changed, only that selection is edited

## Pasted markdown (#1041)

- [x] `_a_` is italic
- [x] `*a*` is italic
- [x] `__a__` is bold
- [x] `**a**` is bold
- [x] `__*a*__` is bold italic
- [x] `__*~a~*__` is bolid italic strikethough
- [x] `` `__*~a~*__` `` is bolid italic strikethough code 
- [x] hitting backspace does the same thing as undo
- [x] undo undoes the styling, but does not move the char back
- [x] a split block (enter, shift+enter) or space triggers the markdown
- [x] for split block, the style does not follow onto the next line
- [x] `  >  ` turns it into a blockquote after space is hit
- [x] `` ``` ``  makes code blocks (we can style these later)
- [ ] `[name](foo.co)` turns into a hyperlink

## User Mentioned (#1043)

- [x] Pressing `@` triggers autocomplete with team members listed (showing avatar and preferredName).
- To select a team member from the list:
  - [x] Users can tap a list item
  - [x] Users can press `up` or `down` and `enter`
  - [x] Users can type to autocomplete by `preferredName` and press `enter`
- [ ] Tapping the inline user mention reveals an inline menu with a flat button `Remove Mention`
- [ ] Backspacing once (after the name) shows the `Remove Mention` menu. Backspacing again removes the mention from the user, but leaves the `preferredName` as plain text

## Tags (#1044)
- [x] hitting the trigger immediately pops up the suggestion modal
- [ ] hitting backspace to remove the trigger removes the suggestion modal
- [ ] clicking into a word that begins with the trigger pops up the suggestion modal & the suggestion query includes the whole word
- [x] hitting tab autocompletes with the highlighted suggestion
- [x] hitting enter is same as tab
- [x] hitting up/down arrows move the selection
- [x] clicking on a suggestion autocompletes
- [ ] hitting the "archive" button adds a new line that says #archive to the bottom of the card
- [ ] hitting "unarchive" removes ALL instances of the word archive & all entities.
- [ ] hitting "unarchive" removes appropriate whitespace before/after the word `#archived`
- [ ] hitting "unarchive" removes any blank lines (ie the line that used to say `#archived`)

## Emoji (#1046)
- [x] An emoji menu triggered by pressing colon `:`
  - [x] users can type keywords and we suggest
  - [x] users can arrow and select emoji with enter
- [x] Users can paste/insert emoji from standard OS keyboards (Mac OS, iOS, Android, etc.)

## Migration tests
- TBD

## Regression tests
- [ ] `#private` tags still mark projects as private actions
- [ ] `#archived` tags still send projects to that archive
- [ ] Drag-and-drop behaviors are still golden

**Comment by jordanh** [comment]
@mattkrick I think it good to add a few unit tests if only to establish the pattern. If you add a few, I'll add some more

**Comment by mattkrick** [comment]
well, testing is gonna have to wait until we build out end-to-end tests. https://github.com/facebook/draft-js/issues/743

i think the rest is good to go for another test:
- i wanna hold off on the title for the next sprint to keep this small-ish
- i think menus on tags aren't necessary (yet). you can remove the tagged entity by hitting backspace or undo & there is only 1 action available when they click on a tag/mention (filter) so there's no need for a menu

**Comment by mattkrick** [comment]
@jordanh ready for another go

**Comment by jordanh** [comment]
On it!

**Comment by jordanh** [comment]
# Test Cycle 2

## Title & Content (#1045)
- [ ] when making a new card, autofocuses the title
- [ ] when making a new card, adequate placeholders appear
- [ ] can `tab` and `shift + tab` between the two fields
- [ ] in title, only plaintext is allowed
- [ ] in title, has 140 character maximum
- [ ] in content, has 512 character maximum

## WYSISYG core features (#1042)

### Link formatting
- [ ] after typing a valid url, it becomes a hyperlink when you hit space
- [ ] after linkifying a typed url, hitting backspace removes the hyperlink
- [ ] after any keypress other than backspace, the hyperlink stays & hitting backspace acts normally
- [ ] when another modal is open, hitting space makes the modal go away
- [ ] if the caret is at the end of the link and you hit space, the link will not continue
- [ ] if the caret is in the middle of the link and you hit space, the link will continue

### Link Viewer
- [ ] if the cursor is inside or at the end of a hyperlink, the LinkViewer modal shows
- [ ] if you're at the end of a hyperlink and hit space, the LinkViewer goes away
- [ ] when the LinkViewer is open and you click another link, the url changes
- [ ] when the LinkVIewer is open and you click a non-link, the modal goes away
- [ ] when the LinkViewer is open and you click to the right of a trigger (`: @ #`) the suggestion modal pops up
- [ ] when the suggestion modal is active and you click inside a hyperlink, the LinkViewer shows up
- [ ] when you navigate to a hyperlink via left/right arrows, the LinkViewer pops up
- [ ] when you navigate away from a hyperlink via left/right arrows, the LinkViewer goes away
- [ ] hitting esc closes the modal
- [ ] clicking the url in the modal opens it in a new tab
- [ ] clicking remove removes the url from the highlighted area
- [ ] clicking change pops up the LinkChanger

### Link Changer
- [ ] when the selection is collapsed on a blank line, hitting ctrl+k and filling out the form creates a new link & puts the caret directly after the new word & the LinkViewer pops up.
- [ ] when the selection is collapsed at the end of the text, hitting ctrl+k and filling out the form creates a new link and the caret is placed after the last letter
- [ ] when the selection is collapsed in the middle or to the right of a word, hitting ctrl+k will autofill the text with the word and clicking Add will replace the word the text + link and the caret will be at the end of the word
- [ ] when the selection spans 2+ blocks, the LinkChanger does not have a text field, but the hyperlink is applied to each character in the selection
- [ ] when the selection is not collapsed but only spans 1 block, the entire selected area is set at the default for the text
- [ ] when the selection is within a link, the href and text is autopopulated
- [ ] when the selection includes 1 or more links, grab the right-most link as the default.
- [ ] hitting esc closes the modal
- [ ] the modal pops up at the beginning of the line if ctrl+k is hit on a blank line (addresses bug in https://github.com/facebook/draft-js/issues/45)
- [ ] when a substring of a link is highlighted & changed, only that selection is edited
- [ ] when a link is added without being prepended by a protocol, we add `http://` for the user

## Pasted markdown (#1041)

- [ ] `_a_` is italic
- [ ] `*a*` is italic
- [ ] `__a__` is bold
- [ ] `**a**` is bold
- [ ] `__*a*__` is bold italic
- [ ] `__*~a~*__` is bolid italic strikethough
- [ ] `` `__*~a~*__` `` is bolid italic strikethough code 
- [ ] hitting backspace does the same thing as undo
- [ ] undo undoes the styling, but does not move the char back
- [ ] a split block (enter, shift+enter) or space triggers the markdown
- [ ] for split block, the style does not follow onto the next line
- [ ] `  >  ` turns it into a blockquote after space is hit
- [ ] `` ``` ``  makes code blocks (we can style these later)
- [ ] `[name](foo.co)` turns into a hyperlink

## User Mentioned (#1043)

- [ ] Pressing `@` triggers autocomplete with team members listed (showing avatar and preferredName).
- To select a team member from the list:
  - [ ] Users can tap a list item
    - [ ] Users can press `up` or `down` and `enter`
      - [ ] Users can type to autocomplete by `preferredName` and press `enter`
      - [ ] Tapping the inline user mention reveals an inline menu with a flat button `Remove Mention`
      - [ ] Backspacing once (after the name) shows the `Remove Mention` menu. Backspacing again removes the mention from the user, but leaves the `preferredName` as plain text

## Tags (#1044)
- [ ] hitting the trigger immediately pops up the suggestion modal
- [ ] hitting backspace to remove the trigger removes the suggestion modal
- [ ] clicking into a word that begins with the trigger pops up the suggestion modal & the suggestion query includes the whole word
- [ ] hitting tab autocompletes with the highlighted suggestion
- [ ] hitting enter is same as tab
- [ ] hitting up/down arrows move the selection
- [ ] clicking on a suggestion autocompletes
- [ ] hitting the "archive" button adds a new line that says #archive to the bottom of the card
- [ ] hitting "unarchive" removes ALL instances of the word archive & all entities.
- [ ] hitting "unarchive" removes appropriate whitespace before/after the word `#archived`
- [ ] hitting "unarchive" removes any blank lines (ie the line that used to say `#archived`)

## Emoji (#1046)
- [ ] An emoji menu triggered by pressing colon `:`
  - [ ] users can type keywords and we suggest
    - [ ] users can arrow and select emoji with enter
    - [ ] Users can paste/insert emoji from standard OS keyboards (Mac OS, iOS, Android, etc.)

## Migration tests
- TBD

## Regression tests
- [ ] `#private` tags still mark projects as private actions
- [ ] `#archived` tags still send projects to that archive
- [ ] Drag-and-drop behaviors are still golden

**Comment by jordanh** [comment]
Hey there @mattkrick 🌞,  I am getting the following on `npm run db:migrate`:

```
ReferenceError: regeneratorRuntime is not defined
```

**Comment by mattkrick** [comment]
ah, i see you already took care of it. nice!

**Comment by jordanh** [comment]
## Test Cycle 2 Results

Questions:

Is pasting a buffer of Markdown supposed to be supported?

Opened:

- #1092 accepted Project card content length is long [draftjs]
- #1093 continuing links with spaces creates two multiple elements [draftjs]
- #1094 link removal doesn't work for multi-word links [draftjs]
- #1095 pasting a block of markdown does not work as expected [draftjs]
- #1096 Markdown parser doesn't work as expected for some more complicated cases [draftjs]
- #1097 extra clicked needed to apply #private tag styling [draftjs]

Notes:

Some of the above issues are marked as low priority. I think we can leave those marked as low priority for now.

We did some real testing here tonight!

image

**Comment by jordanh** [comment]
# Test Cycle 3 (In Progress)

## Content
- [ ] in content, has 512 character maximum

## WYSISYG core features (#1042)

### Link formatting
- [ ] after typing a valid url, it becomes a hyperlink when you hit space
- [ ] after linkifying a typed url, hitting backspace removes the hyperlink
- [ ] after any keypress other than backspace, the hyperlink stays & hitting backspace acts normally
- [ ] when another modal is open, hitting space makes the modal go away
- [ ] if the caret is at the end of the link and you hit space, the link will not continue
- [ ] if the caret is in the middle of the link and you hit space, the link will continue

### Link Viewer
- [ ] if the cursor is inside or at the end of a hyperlink, the LinkViewer modal shows
- [ ] if you're at the end of a hyperlink and hit space, the LinkViewer goes away
- [ ] when the LinkViewer is open and you click another link, the url changes
- [ ] when the LinkVIewer is open and you click a non-link, the modal goes away
- [ ] when the LinkViewer is open and you click to the right of a trigger (`: @ #`) the suggestion modal pops up
- [ ] when the suggestion modal is active and you click inside a hyperlink, the LinkViewer shows up
- [ ] when you navigate to a hyperlink via left/right arrows, the LinkViewer pops up
- [ ] when you navigate away from a hyperlink via left/right arrows, the LinkViewer goes away
- [ ] hitting esc closes the modal
- [ ] clicking the url in the modal opens it in a new tab
- [ ] clicking remove removes the url from the highlighted area
- [ ] clicking change pops up the LinkChanger

### Link Changer
- [ ] when the selection is collapsed on a blank line, hitting ctrl+k and filling out the form creates a new link & puts the caret directly after the new word & the LinkViewer pops up.
- [ ] when the selection is collapsed at the end of the text, hitting ctrl+k and filling out the form creates a new link and the caret is placed after the last letter
- [ ] when the selection is collapsed in the middle or to the right of a word, hitting ctrl+k will autofill the text with the word and clicking Add will replace the word the text + link and the caret will be at the end of the word
- [ ] when the selection spans 2+ blocks, the LinkChanger does not have a text field, but the hyperlink is applied to each character in the selection
- [ ] when the selection is not collapsed but only spans 1 block, the entire selected area is set at the default for the text
- [ ] when the selection is within a link, the href and text is autopopulated
- [ ] when the selection includes 1 or more links, grab the right-most link as the default.
- [ ] hitting esc closes the modal
- [ ] the modal pops up at the beginning of the line if ctrl+k is hit on a blank line (addresses bug in https://github.com/facebook/draft-js/issues/45)
- [ ] when a substring of a link is highlighted & changed, only that selection is edited
- [ ] when a link is added without being prepended by a protocol, we add `http://` for the user

## Pasted markdown (#1041)

- [ ] `_a_` is italic
- [ ] `*a*` is italic
- [ ] `__a__` is bold
- [ ] `**a**` is bold
- [ ] `__*a*__` is bold italic
- [ ] `__*~a~*__` is bolid italic strikethough
- [ ] `` `__*~a~*__` `` is bolid italic strikethough code 
- [ ] hitting backspace does the same thing as undo
- [ ] undo undoes the styling, but does not move the char back
- [ ] a split block (enter, shift+enter) or space triggers the markdown
- [ ] for split block, the style does not follow onto the next line
- [ ] `  >  ` turns it into a blockquote after space is hit
- [ ] `` ``` ``  makes code blocks (we can style these later)
- [ ] `[name](foo.co)` turns into a hyperlink

## User Mentioned (#1043)

- [ ] Pressing `@` triggers autocomplete with team members listed (showing avatar and preferredName).
- To select a team member from the list:
  - [ ] Users can tap a list item
    - [ ] Users can press `up` or `down` and `enter`
      - [ ] Users can type to autocomplete by `preferredName` and press `enter`

## Tags (#1044)
- [ ] hitting the trigger immediately pops up the suggestion modal
- [ ] hitting backspace to remove the trigger removes the suggestion modal
- [ ] clicking into a word that begins with the trigger pops up the suggestion modal & the suggestion query includes the whole word
- [ ] hitting tab autocompletes with the highlighted suggestion
- [ ] hitting enter is same as tab
- [ ] hitting up/down arrows move the selection
- [ ] clicking on a suggestion autocompletes
- [ ] hitting the "archive" button adds a new line that says #archive to the bottom of the card
- [ ] hitting "unarchive" removes ALL instances of the word archive & all entities.
- [ ] hitting "unarchive" removes appropriate whitespace before/after the word `#archived`
- [ ] hitting "unarchive" removes any blank lines (ie the line that used to say `#archived`)

## Emoji (#1046)
- [ ] An emoji menu triggered by pressing colon `:`
  - [ ] users can type keywords and we suggest
    - [ ] users can arrow and select emoji with enter
    - [ ] Users can paste/insert emoji from standard OS keyboards (Mac OS, iOS, Android, etc.)

## Migration tests
- TBD

## Regression tests
- [ ] `#private` tags still mark projects as private actions
- [ ] `#archived` tags still send projects to that archive
- [ ] Drag-and-drop behaviors are still golden

**Comment by jordanh** [comment]
## Test Cycle 3 Results

- #1094 link removal doesn't work for multi-word links [draftjs] – _(added addn'l case for changing links)_

**Comment by jordanh** [comment]
# Test Cycle 4 (In Progress)

## WYSISYG core features (#1042)

### Link formatting
- [ ] after typing a valid url, it becomes a hyperlink when you hit space
- [ ] after linkifying a typed url, hitting backspace removes the hyperlink
- [ ] after any keypress other than backspace, the hyperlink stays & hitting backspace acts normally
- [ ] when another modal is open, hitting space makes the modal go away
- [ ] if the caret is at the end of the link and you hit space, the link will not continue
- [ ] if the caret is in the middle of the link and you hit space, the link will continue

### Link Viewer
- [ ] if the cursor is inside or at the end of a hyperlink, the LinkViewer modal shows
- [ ] if you're at the end of a hyperlink and hit space, the LinkViewer goes away
- [ ] when the LinkViewer is open and you click another link, the url changes
- [ ] when the LinkVIewer is open and you click a non-link, the modal goes away
- [ ] when the LinkViewer is open and you click to the right of a trigger (`: @ #`) the suggestion modal pops up
- [ ] when the suggestion modal is active and you click inside a hyperlink, the LinkViewer shows up
- [ ] when you navigate to a hyperlink via left/right arrows, the LinkViewer pops up
- [ ] when you navigate away from a hyperlink via left/right arrows, the LinkViewer goes away
- [ ] hitting esc closes the modal
- [ ] clicking the url in the modal opens it in a new tab
- [ ] clicking remove removes the url from the highlighted area
- [ ] clicking change pops up the LinkChanger

### Link Changer
- [ ] when the selection is collapsed on a blank line, hitting ctrl+k and filling out the form creates a new link & puts the caret directly after the new word & the LinkViewer pops up.
- [ ] when the selection is collapsed at the end of the text, hitting ctrl+k and filling out the form creates a new link and the caret is placed after the last letter
- [ ] when the selection is collapsed in the middle or to the right of a word, hitting ctrl+k will autofill the text with the word and clicking Add will replace the word the text + link and the caret will be at the end of the word
- [ ] when the selection spans 2+ blocks, the LinkChanger does not have a text field, but the hyperlink is applied to each character in the selection
- [ ] when the selection is not collapsed but only spans 1 block, the entire selected area is set at the default for the text
- [ ] when the selection is within a link, the href and text is autopopulated
- [ ] when the selection includes 1 or more links, grab the right-most link as the default.
- [ ] hitting esc closes the modal
- [ ] the modal pops up at the beginning of the line if ctrl+k is hit on a blank line (addresses bug in https://github.com/facebook/draft-js/issues/45)
- [ ] when a substring of a link is highlighted & changed, only that selection is edited
- [ ] when a link is added without being prepended by a protocol, we add `http://` for the user

## Pasted markdown (#1041)

- [ ] `_a_` is italic
- [ ] `*a*` is italic
- [ ] `__a__` is bold
- [ ] `**a**` is bold
- [ ] `__*a*__` is bold italic
- [ ] `__*~a~*__` is bolid italic strikethough
- [ ] `` `__*~a~*__` `` is bolid italic strikethough code 
- [ ] hitting backspace does the same thing as undo
- [ ] undo undoes the styling, but does not move the char back
- [ ] a split block (enter, shift+enter) or space triggers the markdown
- [ ] for split block, the style does not follow onto the next line
- [ ] `  >  ` turns it into a blockquote after space is hit
- [ ] `` ``` ``  makes code blocks (we can style these later)
- [ ] `[name](foo.co)` turns into a hyperlink

## User Mentioned (#1043)

- [ ] Pressing `@` triggers autocomplete with team members listed (showing avatar and preferredName).
- To select a team member from the list:
  - [ ] Users can tap a list item
    - [ ] Users can press `up` or `down` and `enter`
      - [ ] Users can type to autocomplete by `preferredName` and press `enter`

## Tags (#1044)
- [ ] hitting the trigger immediately pops up the suggestion modal
- [ ] hitting backspace to remove the trigger removes the suggestion modal
- [ ] clicking into a word that begins with the trigger pops up the suggestion modal & the suggestion query includes the whole word
- [ ] hitting tab autocompletes with the highlighted suggestion
- [ ] hitting enter is same as tab
- [ ] hitting up/down arrows move the selection
- [ ] clicking on a suggestion autocompletes
- [ ] hitting the "archive" button adds a new line that says #archive to the bottom of the card
- [ ] hitting "unarchive" removes ALL instances of the word archive & all entities.
- [ ] hitting "unarchive" removes appropriate whitespace before/after the word `#archived`
- [ ] hitting "unarchive" removes any blank lines (ie the line that used to say `#archived`)

## Emoji (#1046)
- [ ] An emoji menu triggered by pressing colon `:`
  - [ ] users can type keywords and we suggest
    - [ ] users can arrow and select emoji with enter
    - [ ] Users can paste/insert emoji from standard OS keyboards (Mac OS, iOS, Android, etc.)

## Migration tests
- TBD

## Regression tests
- [ ] `#private` tags still mark projects as private actions
- [ ] `#archived` tags still send projects to that archive
- [ ] Drag-and-drop behaviors are still golden

**Comment by jordanh** [comment]
## Test Cycle 4 Results

- #1109 un-archiving a project not unicode safe? [draftjs]

**Comment by jordanh** [comment]
Awesome progress. This was a fun test cycle. I really like how it all came together. I am going to merge this and push it to staging. We might have one more short clean-up PR before we close out the epic...

**Pull request merged**
