### PR TITLE
Fix agenda list

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] the agenda input behaves normally (completely refactored to get rid of warning in dev)
- [ ] the agenda list behaves normally, but looks better than before
- [ ] cannot drag current or future agenda items above items that have been completed

Also fixes a bug that plagued the template list & discussion topic list where given 4 items 1,2,3,4, if you dragged item 1 between 2 & 3 it would return 1, 3, 2, 4. No test required, but definitely worthwhile to get this into prod next week

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1
- [ ] the agenda input behaves normally (completely refactored to get rid of warning in dev)
- [ ] the agenda list behaves normally, but looks better than before
- [ ] cannot drag current or future agenda items above items that have been completed

## Test Notes

I used the integration tests to test these

**Comment by jordanh** [comment]
@mattkrick found one little buggy. See ^

**Comment by jordanh** [comment]
I completely underestimated how much better this was going to look. Wow. It's like a whole new product.

**Comment by mattkrick** [comment]
i went ahead & made the current item non-draggable (which is how it is today). that should fix the bug!

**Comment by ackernaut** [comment]
@mattkrick everything works pretty smoothly and the tests pass. I noticed one error in the browser console and then there is a weird edge case with jumping ahead:

Seems this `scrollIntoView` fires sometimes when moving to the next item:
```
Uncaught TypeError: Cannot read property 'scrollIntoView' of null
    at Object (AgendaItem.js:91)
Object @ AgendaItem.js:91
requestIdleCallback (async)
componentDidUpdate @ AgendaItem.js:90
commitLifeCycles @ react-dom.development.js:15263
commitAllLifeCycles @ react-dom.development.js:16523
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:16677
completeRoot @ react-dom.development.js:18069
performWorkOnRoot @ react-dom.development.js:17997
performWork @ react-dom.development.js:17901
performSyncWork @ react-dom.development.js:17873
interactiveUpdates$1 @ react-dom.development.js:18164
interactiveUpdates @ react-dom.development.js:2217
dispatchInteractiveEvent @ react-dom.development.js:4916
```

Also, if you skip ahead (by clicking in the left nav) to the last one of several, then drag it down (which is doable if you hadn’t progressed through many items), the penultimate one gets marked as completed. Weird, and probably an edge case.

Not sure what you want to do with those two items, up to you, otherwise LGTM! Nice work! 👏

**Comment by mattkrick** [comment]
good find! i'm OK with leaving those errors there & just using it to continue building the case to migrate the action meeting to the new meeting format

**Comment by ackernaut** [comment]
Sounds good to me!

**Pull request merged**
