### PR TITLE
Sprint3 bugfixes

### LINKED ISSUE #1665: Strange editing state when adding card for another teammate
### Steps to reproduce:

- Navigate to a Team Dashboard
- Filter the board by a teammate (“Show Projects for:”)
- Tap to add a card to a lane
- Notice the flash of editing state where it says “Teammate is adding a project”

### Acceptance Criteria
The app UI should:
  - have an editing state that is not confusing (User is adding a card for a teammate, the teammate is not adding the card.)
  - be free of any authentication bugs (I am not assuming the identity of the teammate when navigating team dash, filtering by teammate, creating cards, etc.)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #1734: on refresh agenda list doesnt scroll
when the meeting is refreshed the active agenda item should be scrolled to

Estimated effort: 11 points

# Acceptance Criteria
- when the meeting is refreshed the active agenda item should be scrolled to

### LINKED ISSUE #1791: link not going into card
## Issue - Bug
Repro:
- Create a card
- type some text
- hit ctrl+k to add a link
- call the link "foo"
- set the url to "https://github.com/ParabolInc/action/pull/1730"
- hit enter
- notice the link doesn't appear on the card!

### Acceptance Criteria (optional)
Users can:
   - add links

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #1801: meeting avatar menu doesn't close when i select something
AC: menu closes after clicking something

​effort: 11 points

### LINKED ISSUE #1802: agenda list jitters when scrolled all the way to the bottom
repro: make a long list of agenda items, scroll to the bottom, see menu jitter.

AC: no jitter when scrolled to the bottom of a long list

effort: 11 points

### LINKED ISSUE #1806: notification bell stays highlighted
going to notifications and then back i see the bell icon keep its dark background. that's no good.

### Acceptance Criteria
- notification bell is only highlighted when on notifications

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #1821: bug: live updating of updated credit card information
## Issue - Bug

This is a bit of a "bu-hancement". After applying hotfix #1817, we noted that after posting the update credit card field, a reload would be required to see the updated info. This issue captures the rest of the work.

Should also be done at the same time as #1818  and #1129.

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - When a user submits updated credit card information using the modal, the org information updates without requiring a refresh

### PR DESCRIPTION
**Pull request by mattkrick**
TESTS
- [ ] fixes tooltips broken in #1815. Merge this alongside #1815!
- [ ] fixes #1806. Click the bell to go to notifications. then go to user settings. the go to my dashboard. notification bell does not stay highlighted dark.
- [ ] fixes #1821 have 2 users in your org. Billing leader in browser 1, go pro. log in as team member in browser 2. then terminate the stripe subscription via the DB (set organization periodEnd: new Date() and stripeSubscriptionId: null) set all teams to `isPaid: false`. Refresh both browsers. Update the credit card (4242424242424242 or any valid fake card). In browser 2, notice you have access to the team again w/o a refresh.
- [ ] fixes #1791. Follow reproduction steps there to verify
- [ ] fixes #1665. Follow repro steps there to verify
- [ ] fixes #1801 start a meeting with more than 1 person. click on the 2nd user avatar. click an option in the menu. the menu closes.
- [ ] fixes #1734. create 30 agenda items. go to the agenda phase, go through items 1 - 25. hit refresh. 26 is now pink & in view. 
- [ ] fixes #1802. in above meeting, scroll down to the end of the list, there is no jitter. (to reproduce, change overflownbelow minHeight to height,  shrink your window until the overflownbelow div has a height of 0.5, watch it struggle to know if it should roundup to 1 or down to 0).

### CODE REVIEW

**Comment by mattkrick** [comment]
@dan-f or @jordanh if either of you guys wanna do some testing this weekend, this is a good one that'll clean up a bunch of little bugs around the app.
NOTE: tooltips on master is currently broken, so this needs to get pulled into master before master makes it to production.

**Comment by jordanh** [comment]
Looking now!

**Comment by jordanh** [comment]
# Test Cycle 1
## Status: In-progress
## Tests
- [ ] fixes tooltips broken in #1815. Merge this alongside #1815!
- [ ] fixes #1806. Click the bell to go to notifications. then go to user settings. the go to my dashboard. notification bell does not stay highlighted dark.
- [ ] fixes #1821 have 2 users in your org. Billing leader in browser 1, go pro. log in as team member in browser 2. then terminate the stripe subscription via the DB (set organization periodEnd: new Date() and stripeSubscriptionId: null) set all teams to `isPaid: false`. Refresh both browsers. Update the credit card (4242424242424242 or any valid fake card). In browser 2, notice you have access to the team again w/o a refresh.
- [ ] fixes #1791. Follow reproduction steps there to verify
- [ ] fixes #1665. Follow repro steps there to verify
- [ ] fixes #1801 start a meeting with more than 1 person. click on the 2nd user avatar. click an option in the menu. the menu closes.
- [ ] fixes #1734. create 30 agenda items. go to the agenda phase, go through items 1 - 25. hit refresh. 26 is now pink & in view. 
- [ ] fixes #1802. in above meeting, scroll down to the end of the list, there is no jitter. (to reproduce, change overflownbelow minHeight to height,  shrink your window until the overflownbelow div has a height of 0.5, watch it struggle to know if it should roundup to 1 or down to 0).

# Test Notes

**Comment by jordanh** [comment]
@mattkrick, test cycle 1 complete. I'm running into a strange exception when navigating to the team dash. Am I missing a migration or something?

**Comment by mattkrick** [comment]
whooops, should be better now

**Comment by jordanh** [comment]
onnit

**Comment by jordanh** [comment]
# Test Cycle 2
## Status: in progress
## Tests
- [ ] fixes tooltips broken in #1815. Merge this alongside #1815!
- [ ] fixes #1806. Click the bell to go to notifications. then go to user settings. the go to my dashboard. notification bell does not stay highlighted dark.
- [ ] fixes #1821 have 2 users in your org. Billing leader in browser 1, go pro. log in as team member in browser 2. then terminate the stripe subscription via the DB (set organization periodEnd: new Date() and stripeSubscriptionId: null) set all teams to `isPaid: false`. Refresh both browsers. Update the credit card (4242424242424242 or any valid fake card). In browser 2, notice you have access to the team again w/o a refresh.
- [ ] fixes #1791. Follow reproduction steps there to verify
- [ ] fixes #1665. Follow repro steps there to verify
- [ ] fixes #1801 start a meeting with more than 1 person. click on the 2nd user avatar. click an option in the menu. the menu closes.
- [ ] fixes #1734. create 30 agenda items. go to the agenda phase, go through items 1 - 25. hit refresh. 26 is now pink & in view. 
- [ ] fixes #1802. in above meeting, scroll down to the end of the list, there is no jitter. (to reproduce, change overflownbelow minHeight to height,  shrink your window until the overflownbelow div has a height of 0.5, watch it struggle to know if it should roundup to 1 or down to 0).

## Test Notes

**Comment by jordanh** [comment]
got one more ^

**Comment by mattkrick** [comment]
oh gosh dang it. OK tested both team dash & meeting a few times. the animated scroll is finicky, this should do it for everyone though.

**Comment by jordanh** [comment]
# Test Cycle 3
## Status: in progress

## Tests
- [ ] fixes tooltips broken in #1815. Merge this alongside #1815!
- [ ] fixes #1806. Click the bell to go to notifications. then go to user settings. the go to my dashboard. notification bell does not stay highlighted dark.
- [ ] fixes #1821 have 2 users in your org. Billing leader in browser 1, go pro. log in as team member in browser 2. then terminate the stripe subscription via the DB (set organization periodEnd: new Date() and stripeSubscriptionId: null) set all teams to `isPaid: false`. Refresh both browsers. Update the credit card (4242424242424242 or any valid fake card). In browser 2, notice you have access to the team again w/o a refresh.
- [ ] fixes #1791. Follow reproduction steps there to verify
- [ ] fixes #1665. Follow repro steps there to verify
- [ ] fixes #1801 start a meeting with more than 1 person. click on the 2nd user avatar. click an option in the menu. the menu closes.
- [ ] fixes #1734. create 30 agenda items. go to the agenda phase, go through items 1 - 25. hit refresh. 26 is now pink & in view. 
- [ ] fixes #1802. in above meeting, scroll down to the end of the list, there is no jitter. (to reproduce, change overflownbelow minHeight to height,  shrink your window until the overflownbelow div has a height of 0.5, watch it struggle to know if it should roundup to 1 or down to 0).

## Test Notes

**Comment by mattkrick** [comment]
doh! shoulda included "merge master" in the tests. here i am trying to be slick by not including a merge in the commit history...

**Comment by jordanh** [comment]
# Test Cycle 4
## Status: in progress

## Tests
- [x] ✅ fixes tooltips broken in #1815. Merge this alongside #1815!
- [x] ✅fixes #1806. Click the bell to go to notifications. then go to user settings. the go to my dashboard. notification bell does not stay highlighted dark.
- [ ] ❌ fixes #1821 have 2 users in your org. Billing leader in browser 1, go pro. log in as team member in browser 2. then terminate the stripe subscription via the DB (set organization periodEnd: new Date() and stripeSubscriptionId: null) set all teams to `isPaid: false`. Refresh both browsers. Update the credit card (4242424242424242 or any valid fake card). In browser 2, notice you have access to the team again w/o a refresh.
- [x] ✅fixes #1791. Follow reproduction steps there to verify
- [x] ✅fixes #1665. Follow repro steps there to verify
- [x] ✅fixes #1801 start a meeting with more than 1 person. click on the 2nd user avatar. click an option in the menu. the menu closes.
- [x] ✅fixes #1734. create 30 agenda items. go to the agenda phase, go through items 1 - 25. hit refresh. 26 is now pink & in view. 
- [x] ✅fixes #1802. in above meeting, scroll down to the end of the list, there is no jitter. (to reproduce, change overflownbelow minHeight to height,  shrink your window until the overflownbelow div has a height of 0.5, watch it struggle to know if it should roundup to 1 or down to 0).

## Test Notes

**Comment by ackernaut** [comment]
Hello @mattkrick I took a look at latest for #1787 and #1829:
- 😢 I can’t click the button on the link editor. Also, I think the blue outline is distracting when I click into the portal but not on the input or button.
- 😢 When I insert the cursor by the link, the editor does stay open (instead of flashing), but it animates in from the far top-left (instead of up and from the bottom relative to the card) and seems very noticeable to me.
Let me know if I can help or test again, would be glad to.

**Comment by jordanh** [comment]
@mattkrick is this ready for re-testin' or, do you need to connect with @ackernaut first?

**Comment by jordanh** [comment]
A couple of other testing notes to add. While trying to verify the existence of #1813 on this branch, I ran into a couple of strange things:

1. When creating a new team, the teams bar flashes with the new team name and then disappears
   - Reloading reveals the new team for reals
1. When I open an incognito window and try to accept an invitation to a new team, I get:

image

**Comment by mattkrick** [comment]
ok @ackernaut can you retest your issues? 
@jordanh your issue is a fun one, i reverted back to the old logic for now just to get this thing across the finish line, looks like i'll have to do some more thinking in a later sprint.

**Comment by ackernaut** [comment]
@mattkrick I will retest! thanks

**Comment by ackernaut** [comment]
@mattkrick tested again!
- 😃 when I tap next to an existing link, the link editor appears as expected
- 😢 I still can’t seem to tap on the button with the mouse

[http://recordit.co/2Bkht1sNH9](http://recordit.co/2Bkht1sNH9)

**Comment by jordanh** [comment]
@mattkrick if you wanted to sneak this in before tomorrow's release, happy to run another cycle on this this eve/tomorrow am

**Comment by mattkrick** [comment]
@jordanh i think i finally squashed that last bug that terry found. just changed 1 line, so here's the new test:

- [ ] create a new card, type "foo". highlight it & hit ctrl+k. in the url type 'foo.co'. CLICK (don't hit enter) "Update". Click next to the hyperlink, see the url show up correctly
- [ ] hit ctrl+k once in the hyperlink and click Change. Change foo.co to foo.com. CLICK Update. Notice the url updated successfully.

**Comment by jordanh** [comment]
# Test Cycle 5
## Status: in progress
- [ ] fixes #1821 have 2 users in your org. Billing leader in browser 1, go pro. log in as team member in browser 2. then terminate the stripe subscription via the DB (set organization periodEnd: new Date() and stripeSubscriptionId: null) set all teams to `isPaid: false`. Refresh both browsers. Update the credit card (4242424242424242 or any valid fake card). In browser 2, notice you have access to the team again w/o a refresh.
- [ ] create a new card, type "foo". highlight it & hit ctrl+k. in the url type 'foo.co'. CLICK (don't hit enter) "Update". Click next to the hyperlink, see the url show up correctly
- [ ] hit ctrl+k once in the hyperlink and click Change. Change foo.co to foo.com. CLICK Update. Notice the url updated successfully.

**Comment by jordanh** [comment]
Success! LGTM! 💯 Mergin'

**Pull request merged**
