### PR TITLE
Better project column scrolling

### LINKED ISSUE #1072: Auto-scroll project columns
## Issue - Enhancement

I often have difficulty using _My Dashboard_ to prioritize project columns because the columns don't always autoscroll neatly. For example, have a look at the following gif:

project scrolling

I want to de-prioritize buying shoes. I select the card and attempt to drag it to the bottom. I'd expect that when I do this, the column will scroll to allow me to move the project cleaning to the bottom of the list if I want to. However, the column does not scroll.

This may be a rare "b-hancement"

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by dan-f**
Alright! This one was trickier than I expected, but it fixes #1072 based on my testing.

The approach was to add the `ScrollZone` component to automatically scroll the Project Column as projects get close to the edges. Unfortunately, while this fixed the scrolling issue, it borked the drag-and-drop logic. It turned out to be easier for me to use the architecture of the ["sortable list" example in the react-dnd docs](https://react-dnd.github.io/react-dnd/examples-sortable-simple.html) rather than to make sense of the mutable drag state abstraction in the `checkDragForUpdate` module. Basically, we now have another drop target - cards themselves! Rather than the parent column keeping track of all the child card coordinates, each card computes it's own box coordinates, calls back to the parent's new `insert` method accordingly.

### CODE REVIEW

**Comment by dan-f** [comment]
Quick heads up - gonna squash my commits into one, since I had terrible commit messages.

**Comment by mattkrick** [comment]
Yeah, having cards be drop zones is _much_ easier! That's how I first built it, but a problem arose when 1 card was a lot bigger than another card they would jump back & forth. the dnd example has drag items that are all equally sized, so life is easy. Another problem is: Card A is active, Card B is stuck. Move Card A to stuck without touching card B.

i'll include those both as tests & get to this in a couple hours:

TESTS
- [ ] can drag a small card above/below a very large card
- [ ] can drag a very large card above/below a small card
- [ ] can drag 1 card into the bottom of an adjacent column that has only 1 card in it

**Comment by mattkrick** [comment]
closing in favor of #1548.

**Comment by dan-f** [comment]
@mattkrick -

Are we testing the same code?

- The custom drag image is not gone.
- It does show you where the card will go mid drag.
- You can drag any sized card above or below any other sized card.

Not sure why you closed this PR!

**Comment by mattkrick** [comment]
got it running on the dev server.
here's the 1 broken thing:
- [ ]  can drag 1 card into the bottom of an adjacent column without touching cards in that column
video is here: https://parabol.slack.com/files/U0VV6QW64/F8D7HJG4F/kazam_screencast_00001.mp4

just for fun, you'll see a lot of our competitors have this same problem, which is why i had to abandon the cards-are-drop-targets approach & manually calculate the position from the parent (although i'm SUPER open to finding a cleaner approach!!!)

reason i closed this was because i don't think you'll have fun merging this on top of projects-to-relay, so I opened #1548 which fixes scrolling while avoiding the above regression & is built off of projects-to-relay. if you like this one better though then by all means!

**Comment by dan-f** [comment]
Ah, thanks for the background!

I assume the hover states are now working for you, as it shows in the video?

Yeah, that's the one corner case - the column drop target. I've got an idea: we append an invisible element to the end of the project list with it's height set to 100% (the parent column will have to have the `flex` display property for this to work, I believe). We'll make that element a drop target, and when you hover/drop onto it, your card gets inserted into the end of the sort order. At that point, we can probably remove the drop target from the parent column.

For what it's worth, the first thing I tried was to implement this PR in exactly the same way you did in #1548. I experienced a critical bug with that approach: when you scroll the column down by dragging, you can't actually drop the card between those previously-overflowed-but-now-visible cards.

**Comment by mattkrick** [comment]
Hmmm, i didn't experience that, but i assume we will experience something similar if we move the columns to react-virtualized, so a new approach where the parent doesn't know about the child DOM nodes is a good idea. 

I remember very clearly that there was a bug with small cards & large cards. something like if you drag a small card down to 51% of the large card, it'll swap positions, but then you'll still be on the large card & it'll swap back. i first solved it with a throttle & then solved it by switching to the `dragState` approach, but left the throttle on there for good measure. i wish i could remember, but DnD was done looong ago.

**Comment by dan-f** [comment]
Hm, it's funny, I tested the small/large card scenario that I thought you described, but haven't yet been able to reproduce. How about we loop back to this after `projects-to-relay` lands. We can share screens and hopefully get to the bottom of this.

**Comment by dan-f** [comment]
I believe all the corner cases should be handled now!

Next up: I'm rebasing this on top of `epic8.5` after the `projects-to-relay` merge!

**Comment by dan-f** [comment]
The rebase turned out to be difficult, so I just ended up merging `epic8.5` into this branch.

**Comment by dan-f** [comment]
@mattkrick this is live on the dev server. As far as I can tell it's working. Let me know if you've got any requests for change before I merge.

**Pull request merged**
