### PR TITLE
handle browsers without permissions API

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] iOS safari user can start video

### CODE REVIEW

**Comment by mattkrick** [comment]
ready for review

**Comment by jordanh** [comment]
# Tests

- [ ] ❌iOS safari user can start video

## Notes

Progress! I deployed this to the dev server, added the feature flag to test users, and tested this a few ways:

### iOS / Safari

When I started video, I got a modal asking for permissions. I added them and saw video start. Video then freezes immediately. The other client (connected via OSX / Chrome) never seems to get the mesh set up.

### iOS / Chrome

I don't think WebRTC is supported. This was a no go.

### OSX / Chrome

Seems to work between 2 clients.

### OSX / Safari

Asks for permission, starts video locally, mesh never seems to get set up. Other client cannot receive video stream.

**Comment by jordanh** [comment]
There certainly appears to be no harm in merging this now. What would you like to do as the next step?

**Comment by mattkrick** [comment]
i think this is as far as we go!safari doesn't suppor transceivers, so best we can do is let other folks party & keep the safari clients from crashing

**Pull request merged**
