### PR TITLE
Team invite email updated

### PR DESCRIPTION
**Pull request by ackernaut**
- [x] implements team invite design for #2458 
- [x] cleans up some email components
- [x] added an adaptive-width `<EmailBlock />` container

### tests
- [ ] The summary emails for action and retro look good in browser and email client (this issue does not address responsive needs of those emails)
- [ ] The team invite email looks good
- [ ] The notification email looks good

### CODE REVIEW

**Comment by ackernaut** [comment]
screenshot 2018-11-07 17 47 29
screenshot_20181107-174804
screenshot_20181107-174817

**Comment by ackernaut** [comment]
@mattkrick if you come up with a solution to send a test batch of the notification email locally, that would help! I’m not sure I’d merge this until I see that the changes are okay for that email design.

**Comment by mattkrick** [comment]
it looks like `static/images/brand/mark-color@3x.png` was badly colored, i see this:
badlogo

**Comment by ackernaut** [comment]
I’ll take a look at that image, strange! Thanks for pointing it out.

**Comment by ackernaut** [comment]
@mattkrick this is ready for review when you can. As for the logo file, I can’t reproduce. I did export them again from Figma, both PNG and SVG, but that particular file had no change. This should be the file and it looks clear to me: https://github.com/ParabolInc/action/blob/4e9709d1cd74de4065204a8a3cfc9da57f852a4a/static/images/brand/mark-color%403x.png

Where did you see the file? In an actual email? I wonder if come client over optimizes images and sticks them on a CDN or something.

**Pull request merged**
