### PR TITLE
Fixes #837, enhanced facilitator avatar

### LINKED ISSUE #837: Make facilitator more obvious in meeting
Since #592 is closed, let's break this into its own thing & give the facilitator a title & maybe a bigger ring.

### PR DESCRIPTION
**Pull request by ackernaut**
Adds two things:

- Cranks up the warm circle a notch
- Adds a Tag (label) below the Facilitator that says “Facilitator”

screenshot 2017-03-22 11 50 22

### CODE REVIEW

**Comment by mattkrick** [comment]
LGTM. Only concern is whether the tag should be pink. that dark pink on light pink kinda makes me think error, maybe it's just me?

**Comment by ackernaut** [comment]
Yeah, @mattkrick I see what you’re saying —I was just thinking of making the “warm” facilitator association even stronger. I would be okay trying the gray, or light yellow variants. What say ye?

**Comment by jordanh** [comment]
@ackernaut I think it's safe to try for a week or so. Let's go with it. It may get closer to the spirit behind #715 as well...

**Comment by jordanh** [comment]
Just tested it over here for real. It does really draw the eye up and away from the main action. Perhaps it isn't safe to try.

I've been using the inspector to try some changes: 
image

Maybe yellow is the way to go?

image

**Comment by ackernaut** [comment]
@jordanh can you try just using the `gray` or `light` prop and see what you think?

**Comment by jordanh** [comment]
okey dokey

**Comment by jordanh** [comment]
This is tough choice. I also added a cool variant, for fun:

image

**Comment by jordanh** [comment]
Let's go with `gray` for now, and see where that leads...

**Pull request merged**
