### PR TITLE
Project -> Task

### LINKED ISSUE #1374: "Project" -> "Task"
## Issue - Enhancement

Repeat observation of this behavior: when a user first encounters the Process Agenda portion of the meeting, they are often confused about what level of detail to enter in the card. Query indicates that "Project" is perceived as a larger unit, comprised of smaller "Actions" (preferred naming over "Task"). They feel that a Project card should allow more back-of-card detail. It isn't organic behavior for many of our users to break a large project/topic down into discrete tasks.

project action

--
CURRENT COPY:

**[prompt]**
Derrick: "agenda item xyz"
What do you need?

**[first card]**
Add a **P**roject
(tag #private for personal projects)

--
SUGGESTED COPY REVISION:

**[prompt]**
Derrick: "agenda item xyz"
What Actions do you need to complete this Project?

**[first card]**
Add an **A**ction
(tag #private for personal reminders)

### PR DESCRIPTION
**Pull request by dan-f**
This one fixes #1374 

Since this touches so many files, I want to make sure this gets a good review & regression testing.

### CODE REVIEW

**Comment by dan-f** [comment]
[Moving `plan` file to GH comment]
- [x] Persistence layer
  - [x] Rethink: rename "Project" table to "Task"
  - [x] Rethink: rename "projectId"s to "taskID"s
  - [x] Rethink: rename any property named "project" to "task"
  - [x] rename indexes
    - [x] projectIdUpdatedAt on ProjectHistory table
- [x] API layer
  - [x] All code touching Rethink should make reference to tasks
  - [x] All constants named after projects renamed after tasks
  - [x] GraphQL: rename all "project" queries and mutations to "task"
- [x] Developer layer
  - [x] module/file names: rename all "project" to "task"
  - [x] names: rename all "project" bindings to "task"
- [x] UI layer
  - [x] User-facing views: rename all "project" copy to "task"
- Documentation layer
  - rename all marketing/website "project" references/screenshots to "task"

TEST
  - test migrations locally w/ data
  - regression test UI

**Comment by mattkrick** [comment]
merging this guy into my projects-to-relay turned out to be a little too much because in my branch I renamed some files that this one also renamed and it got confusing.
So instead, i did this following:
1. rename all folders/files: 
```
find . -depth -exec rename -v 's/project/task/g' *.js {} + // 2x, because i suck at linux & don't know how to do things from deep to shallow
rename -v 's/project/task/g' *.js // for the migrations folder to revert above actions
```
2. replace all instances of the whole word project to task
3. add in your awesome migration & hotkeys commit

one thing that neither of these do is fix the word `Outcome`, like `OutcomeCard`. In the past, an Outcome was either a Project or an Action, but since then actions have turned into private projects, so we should refactor this, too, but that can wait for another PR.

**Comment by mattkrick** [comment]
I think we may wanna do this one as the last PR for epic 8.5
things to do:
- rename Project to Task, project to task
- undo name changes in migraitons folder & the emojis.json, if applicable
- cherry-pick the commit for the hotkeys & labels
- add the new migration

**Comment by dan-f** [comment]
@mattkrick - I agree, let's do this one last. We can sync up, because I think I nailed down a reasonably deterministic way of making this work :)

**Comment by dan-f** [comment]
Yeah, shouldn't be too difficult.

**Comment by mattkrick** [comment]
since 8.5 is so freakin huge, let's deploy this after we get 8.5 pushed to prod.

**Pull request closed without merging**
