### PR TITLE
New invite flow

### PR DESCRIPTION
**Pull request by mattkrick**
TEST - Invite to team
- [x] a + avatar exists on the team dash avatar list
- [x] a + avatar exists on the action/retro meeting avatar list
- [x] clicking the + avatar pops a modal allowing you to type in a list of comma separated email addresses (better handling is OOS)
- [x] email addresses of existing team members trigger an error on the client
- [x] duplicates are silently ignored
- [x] email addresses of existing team members/duplicates are silently ignored on the server
- [x] on success, the content of the modal changes showing the email addresses that received an invite. it goes away on click out or after 5 seconds
- [x] if the recipient is a logged in parabol user, they get a toast + notification in real time

TEST - accept by notification
- [x] clicking Accept on the toast accepts & navigates to the new team dash
- [x] clicking accept on the notification accepts & navigates to the new team dash
- [x] accepting removes the notification & any other notifications that invite the user to that team
- [x] an invitation accepted by notification should NOT expire. otherwise we'd have to cron-job notifications. we know it was accepted by notification if they are a user & they provided the notification id with the token.
- [x] after accepting by notification, if the token from the email is used, it is registered as already accepted 

TEST - accept by email /team-invitation/:token
- [x] if token is invalid, go to token not found page
- [x] if token already accepted, goto already accepted page
- [x] if token already expired, goto already expired page
- [x] if logged in, auto accept & go to team dash
- [x] if existing parabol user & google, goto google sign in
- [x] if existing parabol user & !google, goto email sign in
- [x] if new user & google, goto google sign up
- [x] if google sign up & they don't want to use google, they can click to use their email/password
- [x] if new user & !google, goto email sign up
- [x] if email sign up & an existing email/password is entered, it is silently treated like a login
- [x] if user accepts invite to team while team has a retro meeting in progress, the new user avatar appears in the meeting & can navigate to their check-in phase

### CODE REVIEW

**Comment by mattkrick** [comment]
Burndown:
- [ ] style add user button
- [ ] style add user modal
- [ ] style add user success modal
- [ ] style all the child views of TeamInvitationDialog

**Comment by ackernaut** [comment]
@mattkrick is this ready for style polish? and then test?

**Comment by mattkrick** [comment]
style yes, the login mutation still needs to accept a token, but that shouldn't affect testing at all

**Comment by ackernaut** [comment]
TEST - Invite to team
- [ ] a + avatar exists on the team dash avatar list
- [ ] a + avatar exists on the action/retro meeting avatar list
- [ ] clicking the + avatar pops a modal allowing you to type in a list of comma separated email addresses (better handling is OOS)
- [ ] email addresses of existing team members trigger an error on the client
- [ ] duplicates are silently ignored
- [ ] email addresses of existing team members/duplicates are silently ignored on the server
- [ ] on success, the content of the modal changes showing the email addresses that received an invite. it goes away on click out or after 5 seconds
- [ ] if the recipient is a logged in parabol user, they get a toast + notification in real time

TEST - accept by notification
- [ ] clicking Accept on the toast accepts & navigates to the new team dash
- [ ] clicking accept on the notification accepts & navigates to the new team dash
- [ ] accepting removes the notification & any other notifications that invite the user to that team
- [ ] an invitation accepted by notification should NOT expire. otherwise we'd have to cron-job notifications. we know it was accepted by notification if they are a user & they provided the notification id with the token.
- [ ] after accepting by notification, if the token from the email is used, it is registered as already accepted 

TEST - accept by email /team-invitation/:token
- [ ] if token is invalid, go to token not found page
- [ ] if token already accepted, goto already accepted page
- [ ] if token already expired, goto already expired page
- [ ] if logged in, auto accept & go to team dash
- [ ] if existing parabol user & google, goto google sign in
- [ ] if existing parabol user & !google, goto email sign in
- [ ] if new user & google, goto google sign up
- [ ] if google sign up & they don't want to use google, they can click to use their email/password
- [ ] if new user & !google, goto email sign up

**Pull request merged**
