### PR TITLE
New team sprint

### PR DESCRIPTION
**Pull request by ackernaut**
So far…
- Updated form component styles
- Build a static New Team Form
- Set up state for New Team components in DashSidebar

### CODE REVIEW

**Comment by mattkrick** [comment]
Just have to write the toast popping logic & then this will be g2g

**Comment by ackernaut** [comment]
Ooh, so I experienced first hand a UI issue.

I entered a team name and tabbed to the `textarea` for entering multiple email addresses. I typed a first email address and a comma, and then instinctively pressed enter to the next line. The submit button would not working (nothing apparent in console)—but I guess it is treating it as an email formatting error? Is there a way that we can trim `return` characters in the value?

**Comment by mattkrick** [comment]
Nice catch! I'll dig in.

**Comment by ackernaut** [comment]
Gracias @mattkrick !

**Comment by mattkrick** [comment]
@jordanh ready for 👀

**Comment by jordanh** [comment]
Looking now!

**Pull request merged**
