### PR TITLE
attempt to backfill invoice creation

### LINKED ISSUE #914: Trial expiration date bug
## Issue - Bug

I expired 2 days ago but everything is still functional:

screenshot 2017-04-14 at 2 32 37 pm

### PR DESCRIPTION
**Pull request by mattkrick**
fixes #914 

@jordanh since we can't properly use test data, i think a safe alternative might be to add in a line to only affect your (jordan@parabol.co) invoices, although that isn't foolproof since other errors might arise that just don't pertain to your invoices. The only mutation we send to stripe is to update the invoiceitem metadata, which is idempotent, so we shouldn't have a problem running this locally first (with a stripe production key).

so, I imagine we'd do something like this:
1. copy the prod DB to local
2. add the prod stripe keys to `.env`
3. run ` node ./src/server/database/cloneProdToDev.babel.js` to move the data to development. OR ALTERNATIVELY:  set `RETHINKDB_URL=rethinkdb://localhost:28015/actionProduction`
4. `npm run db:migrate`

Then, we can check out what the invoices look like.

### CODE REVIEW

**Comment by mattkrick** [comment]
ah crap, i need to use babel-register to resolve the package paths... think i'm gonna rewrite migrate.sh in javascript

**Comment by jordanh** [comment]
Silly question, could we punt on prior invoices? Beta software and all that? Or, do you wanna go for the brass ring?

**Comment by mattkrick** [comment]
I'd like to try it if for no other reason than to see if it works. If webhooks ever fail us in the future, we'll at least have a battle tested strategy.

**Comment by jordanh** [comment]
That's a good reason!

**Pull request merged**
