### PR TITLE
Add auto group

### PR DESCRIPTION
**Pull request by mattkrick**
autogroup

a little extra tweaking will be done in #2063 (like grouping cake & cakes)

basically, the more you click the button, the more aggressive the grouping.

TEST
- [ ] try it for yourself!

### CODE REVIEW

**Comment by jordanh** [comment]
Going to stash this here from #2076 (I should have caught it before I merged, but, whoops, I didn't!):

image

**Comment by jordanh** [comment]
This is so fun. I tried it with some data from a user retro I ran today:

gif

The groups aren't super sensical, but it's completely safe to try.

I think before we ship tomorrow, we should fix that websockets error I am running into... but that's the only thing gating the release.

**Comment by mattkrick** [comment]
@jordanh i think the glaring issue is that there is an empty reflections in the grouping phase. any steps to reproduce? did you move forward while someone was typing?

**Comment by mattkrick** [comment]
#2097 captures the empty reflection, which should be the root of our problems

**Pull request merged**
