### PR TITLE
Fix #474 facilitator election

### LINKED ISSUE #474: Can steal facilitator role with refresh
@ackernaut as always, found a great bug with our facilitator election logic where hitting refresh would run the logic before the presence sub set `isConnected`, which means the person who refreshes thinks that the facilitator is disconnected & promotes themselves to facilitator.

### PR DESCRIPTION
**Pull request by mattkrick**

### CODE REVIEW

**Comment by ackernaut** [comment]
Ooh! I tried the trimmer—very nice! However, should we do it before submit? I still see an issue with return carriages...and redux is returning `submitFailed: true`

**Comment by mattkrick** [comment]
submitFailed should only be true if a field is blank (for the new team form). Are you experiencing something different?

**Comment by ackernaut** [comment]
Hey there! I will see if I can get the steps down to reproduce.

Question: do we typically pull in the form object from the store for a view like this? I will poke around.

**Comment by mattkrick** [comment]
the store doesn't easily store the form values, those usually just exist as props passed into a submit handler, unless I'm not understanding?

**Comment by mattkrick** [comment]
@ackernaut let's turn this talk into an issue & get this thing merged

**Comment by ackernaut** [comment]
@mattkrick yes, I'll make an issue—thanks!!

**Pull request merged**
