### PR TITLE
Meeting touch up

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
-  [x] run each meeting on mobile. can close the help menu by clicking the X. The open menu doesn't magically jump around on mobile when you scroll from top to bottom 
- [ ] verify that scrolling components (like big group phase, big agenda phase, discuss phase, etc) all work as expected on mobile
- [x] promote someone else, it works
- [x] cannot see option to promote offline participants

TEST for subscription price:
- [x] go pro, click the toggle to see how much it'll cost ya, it's $6.
- [x] upgrade to pro, check out the invoice estimate, it's $6

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready to test!

**Comment by ackernaut** [comment]
### Test No. 1
TEST
-  [ ] run each meeting on mobile. can close the help menu by clicking the X. The open menu doesn't magically jump around on mobile when you scroll from top to bottom 
- [ ] verify that scrolling components (like big group phase, big agenda phase, discuss phase, etc) all work as expected on mobile
- [ ] promote someone else, it works
- [ ] cannot see option to promote offline participants


TEST for subscription price:
- [ ] go pro, click the toggle to see how much it'll cost ya, it's $6.
- [ ] upgrade to pro, check out the invoice estimate, it's $6

**Comment by ackernaut** [comment]
@mattkrick with a quick test of checklist item no. 2, I didn’t see any offensive scrolling at a mobile viewport with (in Chrome tools) except on the Discuss phase…it sounds like we may be able to help that in a subsequent PR? I’m okay to merge this, I need to update the pricing page once this gets pushed to prod.

**Comment by mattkrick** [comment]
discuss phase on mobile has a regression, holding off on merging until that's fixed in the upcoming PR

**Comment by mattkrick** [comment]
closing in favor of #3087

**Pull request closed without merging**
