### PR TITLE
Meeting nav stages

### LINKED ISSUE #3179: Add meeting sidebar navigation items for user rounds
Based on design efforts from #3077 

### Acceptance Criteria
- Precedes #3180 
- Adds a sub-navigation item per user round to Social Check-In and Solo Updates
- The item probably has their avatar and preferred name with possible active/completed states, like the agenda or discussion topics
- An item shows for all team members even if not connected because of async UX or folks are in the same physical space
- Deprecates/removes the ability to go to the user in the avatar menu if needed, or wait until #3180
- Will iterate on [early designs](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=358%3A16770) to get a sub-item indention and states that feels right (here are the [latest designs](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=479%3A80963&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#11592859))

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #3179 

### Tests
- [ ] The Social Check-In for the Action Meeting has stage nav items
- [ ] The Solo Updates for the Action Meeting has stage nav items
- [ ] The Social Check-In for the Retro Meeting has stage nav items
- [ ] The stage nav items for team rounds (Social Check-In, Solo Updates) have styled states (completed, out-of-sync, etc.)
- [ ] Can start and end Action Meeting with no problem
- [ ] Can start and end Retro Meeting with no problem

### Note
This can be merged after #3244 as is based off of `meeting-sidebar-styles`

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick ready for review!

**Comment by jordanh** [comment]
# Test Cycle 1

### Tests
- [x] The Social Check-In for the Action Meeting has stage nav items
- [ ] The Solo Updates for the Action Meeting has stage nav items
- [x] The Social Check-In for the Retro Meeting has stage nav items
- [x] The stage nav items for team rounds (Social Check-In, Solo Updates) have styled states (completed, out-of-sync, etc.)
- [ ] Can start and end Action Meeting with no problem
- [x] Can start and end Retro Meeting with no problem

**Comment by jordanh** [comment]
First test cycle complete! I found a fun little buggy

**Comment by jordanh** [comment]
Opened https://github.com/ParabolInc/action/issues/3255

Merging

**Pull request merged**
