### PR TITLE
support invoices that are not upcoming or paid

### LINKED ISSUE #1389: Ghost Dates in Billing
## Issue - Bug

note year (1969)

ghost dates

### PR DESCRIPTION
**Pull request by mattkrick**
fixes #1389 

- [ ] `Paid At UNIX EPOCH` doesn't show up on a list of invoices anymore
- [ ] detailed line items show the correct pause/unpause date (this is harder than it should be to test, just trust me on this one :wink: we'll make proper tests when we can generate phony invoices)

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut can you review & adjust the styles as you see fit?
looks like we didn't support pending or failed invoices, which is why the paidAt was going back to 1970

screenshot from 2017-10-05 14-24-17

**Comment by ackernaut** [comment]
Sure thing! I’m gonna take a look at that “Payment Failed” stamp, too! I branched the billing view updates off of the pagination branch, so this should come in soon, huh?

**Comment by ackernaut** [comment]
Ah, you want me to jump on this branch for some styling? I can do that.

**Comment by mattkrick** [comment]
yeah, shouldn't be too many (any?) conflicts since this batch of PRs is pretty tiny in scope

**Comment by ackernaut** [comment]
@mattkrick gonna take a look at this now

**Pull request merged**
