### PR TITLE
Reflect late [base multi-meeting-1]

### PR DESCRIPTION
**Pull request by mattkrick**
This allows folks to revisit the reflect phase & do everything they want to until the grouping phase is complete

TEST
- [ ] start a retro, move pas the reflect phase, then go back & keep working on the reflect phase
- [ ] highlight a reflect column, it still works

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [ ] start a retro, move pas the reflect phase, then go back & keep working on the reflect phase
- [ ] highlight a reflect column, it still works

**Comment by ackernaut** [comment]
@mattkrick I wonder if we should show the `*New Reflection*` card for the viewers of the Group phase (that shows when somebody is adding from the Group phase) when somebody is untethered and adding a card from the Reflect phase? Also, I noticed the timer option goes away when navigating back to the Reflect phase, maybe that’s how it should be? I realize these are both small refinements, just mentioning.

**Comment by ackernaut** [comment]
I noticed that if a card gets grouped, it may disappear for the author who is viewing the Reflect phase.

**Comment by ackernaut** [comment]
The merge conflicts are fixed in `multi-meeting-1` branch

**Comment by ackernaut** [comment]
The merge conflicts are fixed in `multi-meeting-1` branch

**Comment by mattkrick** [comment]
> I noticed that if a card gets grouped, it may disappear for the author who is viewing the Reflect phase.

out of scope for now

>  I wonder if we should show the *New Reflection* card for the viewers of the Group phase

that'd required a lot more work, not sure if it's worth it just for this edge case

**Pull request merged**
