### PR TITLE
ease confusion around logging in with oauth vs password

### PR DESCRIPTION
**Pull request by mattkrick**
TEST

- [ ] User signed up via OAuth. User tries to log in via email/password. A warning tells the user to login via oauth
- [ ] User signed up via OAuth. User tries to sign up via email/password. A warning tells the user to login via oauth
- [ ] User signed up via Email/Password. User tries to login/signup via OAuth. A warning tells the user to login via email/pass
- [ ] User already has signed up via OAuth AND Email/Password (There are 90 of them...). Can log in both ways (no regression)

ADDITIONAL TESTS
- [ ] open login page in incognito window, the email field has focus, not the password field
- [ ] create an account with 2 google accounts via oauth. when logging in, the oauth window pops up asking which one you'd like to use

### CODE REVIEW

**Comment by mattkrick** [comment]
@jordanh ready for review

**Comment by ackernaut** [comment]
### Test No. 1

- [ ] User signed up via OAuth. User tries to log in via email/password. A warning tells the user to login via oauth
- [x] User signed up via OAuth. User tries to sign up via email/password. A warning tells the user to login via oauth
- [ ] User signed up via Email/Password. User tries to login/signup via OAuth. A warning tells the user to login via email/pass
- [ ] User already has signed up via OAuth AND Email/Password (There are 90 of them...). Can log in both ways (no regression)

**Comment by ackernaut** [comment]
Hey @mattkrick I see that when I have an email/password and try to sign in or up with OAuth an error is returned (in the URL) but it doesn’t trigger any message in the UI. I didn’t see any messages added in the commits either. I suppose it says something like “Your account was created using email/password. Sign in below”

**Comment by ackernaut** [comment]
Oops! I didn’t notice the message that says “created without Google” but I think maybe I’m requiring a hard refresh of the URL before I actually see the UI message?

**Comment by mattkrick** [comment]
trying to reproduce now...

**Comment by mattkrick** [comment]
can't seem to reproduce. what email are you testing it for? is it an email that is attached to both an oauth user & an email user?

**Comment by ackernaut** [comment]
I was using my work account, but removing from local database and auth0 as needed. I’ll try again and see if I can come up with better details.

**Comment by ackernaut** [comment]
My steps:
- Since terry@ was OAuth locally (verified in local DB only 1 instance of terry@ using OAuth), I tried tests 1 and 2 and it worked! Got the warning when trying to use username/password, woot!
- I nuked terry@ in local db and on auth0 dev instance
- I signed up using terry@ with username/password
- When I try to use the OAuth button I see the pop-up briefly, I see `user_exists_auth0` error show in the console, and the URL updates to `/?error=user_exists_auth0`
- When I hard refresh, then I get the UI message
Screenshot 2019-04-22 17 38 20
Screenshot 2019-04-22 17 38 25

**Comment by mattkrick** [comment]
fixed! @ackernaut ready for another go

**Comment by ackernaut** [comment]
Going to test this again

**Comment by ackernaut** [comment]
### Test No. 2

- [x] User signed up via OAuth. User tries to log in via email/password. A warning tells the user to login via oauth
- [x] User signed up via OAuth. User tries to sign up via email/password. A warning tells the user to login via oauth
- [x] User signed up via Email/Password. User tries to login/signup via OAuth. A warning tells the user to login via email/pass
- [ ] User already has signed up via OAuth AND Email/Password (There are 90 of them...). Can log in both ways (no regression)

**Comment by ackernaut** [comment]
@mattkrick this looks good to me! I tried to set up the prod database locally to test the last one but am getting stuck with Python (following our internal how-to) I’d be happy to just test that last item on staging if we copy prod data over.

**Pull request merged**
