### PR TITLE
Demo summary updates

### LINKED ISSUE #2561: Implement demo summary changes
### Acceptance Criteria
- Implements design from #2541 
  - Adds small logo to summary header
  - Typography changes to header
  - Updates CTA copy and button label
  - Make and use flat icon graphics for bullets
  - Update copy, in bullets and type style for sub-heading
  - Removes footer CTA for feedback in demo summary
  - Removes link to our website in footer branding in any summary

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #2561 and #2529 

### Tests
- [x] Adds small logo to summary header
- [x] Typography changes to header
- [x] Updates CTA copy and button label
- [ ] Adds flat icon graphics for bullets
- [ ] Updates copy in bullets and type style for sub-heading
- [ ] Removes footer CTA for feedback in demo summary
- [ ] Removes link to our website in footer branding in any summary
- [ ] Changes present label from blue to green when user has no new tasks from action meeting
- [ ] Smoke test demo summary
- [ ] Smoke test action summary
- [ ] Smoke test retro summary

### CODE REVIEW

**Comment by ackernaut** [comment]
Ready!

**Comment by mattkrick** [comment]
code review looks good! will test tomorrow

**Comment by mattkrick** [comment]
feels a little weird having a purple parabol logo on top & a color one on bottom, but that's just me being nit picky. merged!

**Comment by ackernaut** [comment]
@mattkrick thanks for the review. Yeah, I agree re: logo but I felt like it was the quickest, cleanest way to get brand into the summary header without greater design effort. I have some ideas on how to update the presentation of the summary, even with essentially the same content, but I think we should defer ATM per strategy etc.

**Pull request merged**
