### PR TITLE
addTeam to relay

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] open 2 tabs. In tab 1 start a meeting. the meeting shows up in a notification bar in tab 2
- [ ] in tab 1, create a new team on an existing org. in tab 2, the new team shows up the sidebar
- [ ] in tab 1, update the team name of any team. in tab 2, the team name is updated
- [ ] run through welcome wizard, step 2 works as usual
- [ ] repro the steps in #1572 to verify it is fixed
- [ ] log out, log in as someone else. see accurate teams on the sidebar (this has been present since we first added relay, but it's obvious now that teams are on relay)
- [ ] in browser 1, invite an existing parabol user. in browser 2, accept the invite. in browser 1, get a toast saying they joined the team (fix undocumented JOIN_TEAM regression)

with this PR, all subscriptions are now powered by relay!
All that remains is:
- Moving the rest of the mutations to relay
- Moving the `User` entity to relay

once that happens, we can 
- get rid of cashay
- get rid of socket cluster
- FINALLY find that gosh dang memory leak on the dang ol server

### CODE REVIEW

**Comment by mattkrick** [comment]
@dan-f  ready for your eyes!

**Comment by mattkrick** [comment]
ah cancel that, imma give it to @jordanh

**Comment by dan-f** [comment]
@dan-f's first test pass:

- [x] open 2 tabs. In tab 1 start a meeting. the meeting shows up in a notification bar in tab 2
  - Yes, I get the notification that there's a meeting. However:
  - ❌ When I end the meeting with that 1st user, with my 2nd user still on the team dashboard, they see a pretty strange failure:
screen shot 2017-12-20 at 2 58 50 pm
- ❌ in tab 1, create a new team on an existing org. in tab 2, the new team shows up the sidebar
  - For reference, the team I tried to create was called "test"
screen shot 2017-12-20 at 3 01 18 pm
- [x] in tab 1, update the team name of any team. in tab 2, the team name is updated
  - Yes, but errors:
screen shot 2017-12-20 at 3 02 45 pm
- [x] run through welcome wizard, step 2 works as usual

**Comment by mattkrick** [comment]
well son of a gun, i just fixed that up in the other PR sitting there. Lemme do a lil merge...

**Comment by mattkrick** [comment]
alrighty, PRs merged & ready for another go. sorry bout that false start!

**Pull request merged**
