### PR TITLE
add tooltips fix #272 #1354 [Epic 7 PR 1]

### LINKED ISSUE #272: Tooltips added
## Issue - Enhancement

When users need a little extra help with Action UI, they want tooltips for simple explanations, tips, definitions, etc. so that they can use Action more efficiently.

The Tooltip component:

- [ ] Uses a module pattern similar to Menus: component/container/ducks + portals-hoc
- [ ] Has options for behavior: `onHover` `onClick` or `triggerBy` another event/method
- [ ] Has options for presentation/orientation: centered `top|right|bottom|left` of the visual element that the tooltip describes.

Presentation specs:

tooltip example

```
background: ui.palette.dark,
borderRadius: ui.borderRadiusSmall,
color: 'white',
fontSize: appTheme.typography.s2,
fontWeight: 700,
padding: '1rem'
```

- [ ] Add appropriate box-shadow for correct level of depth
- [ ] Add small arrow variants, centered top | right | bottom | left

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**
tests:

Team Settings
- [ ] Next to a Pending Approval, there is a question mark icon
- [ ] mousing over the question mark icon pops up a tooltip
- [ ] mousing away from the icon removes the tooltip
- [ ] if the browser is so narrow that the tooltip cannot fit without hitting the right border, the tooltip is automatically shifted to the left
- [ ] if the tooltip covers up the icon, then the tooltip goes away when the mouse moves off the tooltip itself

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut when you get a chance can you fix the tooltip styles on this one? as soon as we merge this we can merge the undo-trials

**Comment by ackernaut** [comment]
@mattkrick picking up the tooltip task next! Thanks for the prompt.

**Comment by ackernaut** [comment]
@mattkrick any thoughts on when to stop/start the tooltip animation based on mouse events? there is a lot of flicker when the mouse passes over quickly…perhaps we throttle, or allow the animation to finish before it can be stopped, not 100% sure of a good pattern.

See (but not a high frame rate, mind you): http://recordit.co/Op7hGyd33k

**Comment by ackernaut** [comment]
@mattkrick another question: is it possible to center a tooltip above or below a trigger (such as a button or icon)? This is a common placement for tooltips so was wondering…taking a peek at the `withCoords` decorator but not 100% clear.

**Comment by mattkrick** [comment]
Yeah, it takes the same targetanchor as the other modals

**Comment by ackernaut** [comment]
@mattkrick _re:targetanchor_ I see! I guess the issue I’m seeing (when centering above the icon) is that the trigger is so small (the icon) that when the tooltip animates in it passes through where the mouse is hovering and causes the tooltip to close.

**Comment by ackernaut** [comment]
At any rate, styles are in and we can merge when ready!

**Comment by ackernaut** [comment]
## Test No. 1
### Status: In Progress
-----
Team Settings
- [ ] Next to a Pending Approval, there is a question mark icon
- [ ] mousing over the question mark icon pops up a tooltip
- [ ] mousing away from the icon removes the tooltip
- [ ] if the browser is so narrow that the tooltip cannot fit without hitting the right border, the tooltip is automatically shifted to the left
- [ ] if the tooltip covers up the icon, then the tooltip goes away when the mouse moves off the tooltip itself

**Pull request merged**
