### PR TITLE
Agenda input prompt

### LINKED ISSUE #732: Summary information at top of Last Call is confusing
## Issue - Enhancement

During a demo on-boarding session, @tayamueller asked the participant, "what do you think this screen is for?" and they responded that they thought it was a meeting summary. Later, the _actual_ meeting summary was given as a "more detailed meeting summary."

I'll offer the following: because the Last Call view shows the number of items processed it feels like the final end to a meeting. Really, we want optimize for the following:

- We want to display how long the meeting has been running, to encourage timeliness (kicking this to #887, Future Epic)

- [x] - We want to invite users to add agenda items if they need anything. Perhaps prompts like:
      * Does anybody else need anything? Anyone still stuck this week? (ships in Upcoming Epic 3 PR)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**
So far this fixes #732 #625 #631 and partially addresses #723 …

With a quick merge into master I can move on to other Epic 3 tasks, or I can add them to this PR (and re-title to Epic 3 part 2).

What say ye @mattkrick @jordanh ?

### CODE REVIEW

**Comment by ackernaut** [comment]
I need to get the new copy edits in from S.P.A.

**Comment by ackernaut** [comment]
Is this too stale or shall we revisit in [Epic 3](https://github.com/ParabolInc/action/milestone/4)?

**Comment by jordanh** [comment]
Let's definitely put this in Epic 3. It's still important!

**Comment by ackernaut** [comment]
Will revisit soon.

**Comment by ackernaut** [comment]
Latest screens:

screenshot 2017-04-06 11 24 29
screenshot 2017-04-06 11 24 37
screenshot 2017-04-06 11 24 42

**Comment by jordanh** [comment]
Small edits (I'd make 'em direct but @tayamueller and I are up against deadlines):

1) Now...what -> Now, what do you need?
2) Exnay on the Woot, woot. Let's update that voice. Could you suggest some new copy that is in voice?

**Comment by ackernaut** [comment]
@jordanh got it!! Will update soon.

**Comment by ackernaut** [comment]
@jordanh here is an empty Last Call and a Last Call with 3 items. An alternative to “That wraps up the agenda!” could be “Nice work, team!”. Also, any thoughts on copy for the Last Call empty state? I can update the copy.

screenshot 2017-04-06 13 16 00

screenshot 2017-04-06 13 17 40

**Comment by mattkrick** [comment]
Looks good! will merge as soon as Jordan's 2 small edits get added.

**Comment by ackernaut** [comment]
@mattkrick thanks! I made the changes he suggested.

**Comment by mattkrick** [comment]
did you push? 
still seeing some woot: 
https://github.com/ParabolInc/action/blob/998a207f70be2e433de94c70259a6630a7a2ef9a/src/universal/utils/makeSuccessCopy.js

**Comment by ackernaut** [comment]
Ha, forgot to push!

**Comment by ackernaut** [comment]
I’m using a specific heading (opposed to random) for both Last Call (some items) and Last Call (no items).

**Comment by mattkrick** [comment]
ah gotcha. should we address the success message voice in this PR or do it in another one?

**Comment by ackernaut** [comment]
Another PR, I’ll add it to my list!

**Pull request merged**
