### PR TITLE
swipeable reflect columns

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] the spaces of items in the facilitator bar is appropriate on desktop & mobile
  - "End meeting" has a static width of 88px
  - if a left icon is present, it is also 88px to ensure a middle icon is directly centered
  - if there are 2 center icons, the icon to move forward is always on the right (constriant: we want primary action to be in the center, we don't want the order to switch between mobile/desktop) so for checkin, it  should be "not here", "here", "end meeting"
- [ ] Can swipe between reflect columns
- [ ] can use the stepper dots to navigate between columns
- [ ] expanding the reflection stack in the reflect phase works on mobile & desktop  
- [ ] Discuss phase looks OK on mobile (i opted against the tabs, too much work for something that'll change soon)

NOTES
- Number titles felt bad since titles are user defined. image a case where folks prefix their titles with numbers: `1) 1. What went right?`

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review!

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] the spaces of items in the facilitator bar is appropriate on desktop & mobile
  - "End meeting" has a static width of 88px
  - if a left icon is present, it is also 88px to ensure a middle icon is directly centered
  - if there are 2 center icons, the icon to move forward is always on the right (constriant: we want primary action to be in the center, we don't want the order to switch between mobile/desktop) so for checkin, it  should be "not here", "here", "end meeting"
- [ ] Can swipe between reflect columns
- [ ] can use the stepper dots to navigate between columns
- [ ] expanding the reflection stack in the reflect phase works on mobile & desktop  
- [ ] Discuss phase looks OK on mobile (i opted against the tabs, too much work for something that'll change soon)

**Comment by ackernaut** [comment]
@mattkrick I wonder how much we should worry about smaller viewports:
Screenshot 2019-08-08 15 21 28
Screenshot 2019-08-08 15 21 41

**Comment by ackernaut** [comment]
Well, even iPhones at 375 (6/7/9/X) wide are a little cramped:
Screenshot 2019-08-08 15 29 38

**Comment by ackernaut** [comment]
I realize that the inputs and top cards are still fixed at 320px. If we move in [this direction](https://app.getguru.com/card/cBb5rG9i/Card-layout-specs) it might give us the room we need.

**Comment by ackernaut** [comment]
@mattkrick from what I’m seeing in analytics there’s a lot of mobile traffic down at 360 which is a typical Android width, there’s not quite as much down at 320. What I pushed looks clean at 360, still a little overlap at 320. I imagine 320 is going to be less and less in the future.

**Comment by ackernaut** [comment]
I’m doing a little style work, but so far this is looking great

**Comment by mattkrick** [comment]
@ackernaut yeah, i saw that with the iphone 5, although it looks like most devices float around the ~400+ range. 

i'm 100% for bumping it down to a max of 296, i'm just not sure it's top priority. i'll create an issue

**Pull request merged**
