### PR TITLE
Updated E4E policy

### PR DESCRIPTION
**Pull request by jordanh**
Doing this as a consent proposal.

## Background

I'd like to update this E4E policy to support the additional exposure we'll get during hiring. While I don't expect many (if any) to take us up on it, I'd rather make incremental progress here rather than nuke it all together.

### Changes

* ~Action~ --> Parabol
* The percentage of fully-diluted equity has been halved to reflect the change in risk
* It's been made clear that we need to qualify you before we can accept your bid (i.e. we'll put some legal paper between you and us)

### CODE REVIEW

**Comment by jordanh** [comment]
@mattkrick, @ackernaut  any clarifying questions?

**Comment by mattkrick** [comment]
no questions, if we're making changes, i'd _love_ to move away from the "10 + x" point system to an "x hours" point system.

**Comment by ackernaut** [comment]
No questions here @jordanh

**Comment by jordanh** [comment]
@mattkrick I'm going to handle the pointing issue as a separate issue, but I agree!

**Pull request merged**
