### PR TITLE
Enable new auth pages

### PR DESCRIPTION
**Pull request by dan-f**
This enables the new signin/signup/password recovery pages.

It also updates the end-to-end tests of those pages.

### CODE REVIEW

**Comment by mattkrick** [comment]
In the webpack build i see
```
[1] WARNING in ../node_modules/formidable/lib/incoming_form.js
[1] 1:43-50 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
[1]  @ ../node_modules/formidable/lib/incoming_form.js
[1]  @ ../node_modules/formidable/lib/index.js
[1]  @ ../node_modules/superagent/lib/node/index.js
[1]  @ ../node_modules/auth0-js/src/helper/request-builder.js
[1]  @ ../node_modules/auth0-js/src/authentication/index.js
[1]  @ ../node_modules/auth0-js/src/index.js
[1]  @ ./universal/utils/getWebAuth.js
[1]  @ ./universal/components/ResetPasswordPage/ResetPasswordPage.js
[1]  @ ./universal/components/Action/Action.js
[1]  @ ./server/webpackEntry.js
```

A client-side lib should not be requiring superagent. Could you troubleshoot this? It may be as easy as importing from the build folder.

**Comment by dan-f** [comment]
Huh, I'll take a look.

**Comment by mattkrick** [comment]
i was getting local failures running the e2e tests. fix at #1942

**Comment by mattkrick** [comment]
LGTM :+1:

**Comment by dan-f** [comment]
Thanks @mattkrick ! Good catch on that build error 🎸!

**Pull request merged**
