### PR TITLE
404 redesign

### PR DESCRIPTION
**Pull request by ajibs**
Fixes: #389
Designed and coded a playful and helpful 404 page

Screenshot of page below:

design2

### CODE REVIEW

**Comment by mattkrick** [comment]
well i absolutely love it.
i may wanna simplify a little logic in the container, but the design is on point!
@jordanh what say you?

**Comment by jordanh** [comment]
Hey! This looks like a good start. A quick note: our team is going to be offline this week for a team retreat. We'll be back at it next week, and give you some review comments.

**Comment by jordanh** [comment]
@ajibs very good start on this! We updated #389 with some acceptance criteria. Overall, the code you've started and its implementation look good.

Here's what I tally:

- [x] Implemented as a set of one or more React components
- [x] Uses Parabol style library from src/universal/styles and CSS-in-JS styling
- [ ] When user navigates to unknown route, should render 404 page
- [ ] User should not automatically be logged out when 404 page is hit
- [ ] Should provide link to previous page (or `/me` if unknown)

Once these are all ticked off, the team will give you a full review and we'll look to getting this merged!

**Comment by ajibs** [comment]
Hey @jordanh 

I have fixed the following:
- [x] When user navigates to unknown route, should render 404 page
- [x] User should not automatically be logged out when 404 page is  
- [x] Should provide link to previous page (or /me if unknown)

**Comment by jordanh** [comment]
Hi @ajibs, been busy around here. My sincerest apologies it has taken us so long to get back to looking at this. I just submitted a PR to your original branch clearing any merge conflicts.

I pulled down your branch and gave it a test. I was running into a little difficulty.

1. When I was logged out, everything worked as expected
1. When I was logged in, an unknown route redirected me to `/me` (which is _probably_ ok)
1. However, the route `/signout` no longer worked (Click on your profile image, click on "Sign Out")

I haven't dug into your code to see what made Signing Out change. Could you please look into it?

**Comment by ajibs** [comment]
@jordanh the app behaves differently in production versus the open source code.
The signout route is always hit before the not found page.

I'm not sure why. I'd be happy if @mattkrick would be able to explain how this works or how to make it behave consistently as in production.

The way my code works at the moment, the signout route is inaccessible because it is placed after the error route.

**Comment by jordanh** [comment]
I'll add it to our next meeting's agenda to discuss. We'll get back to you in a week!

**Comment by jordanh** [comment]
Or, ping us on the [developer slack](http://slackin.parabol.co/) and we'll see if we can't look at it together.

**Comment by jordanh** [comment]
Hi @ajibs we met today and discussed this PR. While we'd love to help you try and get to the bottom of why it seems to be acting differently in `production` than in `dev`, we're unable to prioritize this at the moment. If you figure it out—great! Otherwise, we'll hold onto your design and implement it when we get around to it ourselves.

Do you think you'll keep debugging this or shall we close this PR for now?

**Comment by jordanh** [comment]
This has also gotten stale, I'm going to close it.

**Pull request closed without merging**
