### PR TITLE
Make card links clickable if the card doesn't have focus

### LINKED ISSUE #1364: Ability to open a link on a card w/o editing the card
Right now, I have to click on a card to edit it, then click on the link to open it. I'd like to just be able to open the link without it appearing that I'm editing the card.

### PR DESCRIPTION
**Pull request by mattkrick**
Fixes #1364
@ackernaut can you run through the test & make sure it's working like you hope? Now that I'm playing with it, I have some reservations about a click on a link having 2 different responses depending on the current focus, but I can shut up if you like it. I do like it for read-only cards (meeting summary, archive). 

TEST

Outcome cards:
- [ ] in the standard board, add a link on a card
- [ ] click outside of the card. hover the link. it's a hand. click the link. the link opens in a new window
- [ ] click inside the card but not on the link. now hover the link. it's a caret. the link opens the linkViewerModal

CheckInQuestion
- [ ] start a meeting, edit the check in question. works as usual (we don't allow links in here yet)

Card
- [ ] During a meeting agenda phase, add a card. add a link to the card. finish the meeting. click the link on the card in the meeting summary. it works.

ProjectInvolves
- [ ] mention someone in a card and include a link. when they get the notification, they can click the link inside the card.

Archive
- [ ] The links are clickable in the archive.

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut mind taking a peek when you get a chance?

**Comment by ackernaut** [comment]
@mattkrick sure thing, diving into the codebase for the afternoon…I’ll warm up here!

**Comment by ackernaut** [comment]
Test No. 1 (TA) [in progress]

Outcome cards:
- [x] in the standard board, add a link on a card
- [x] click outside of the card. hover the link. it's a hand. click the link. the link opens in a new window
- [x] click inside the card but not on the link. now hover the link. it's a caret. the link opens the linkViewerModal

CheckInQuestion
- [ ] start a meeting, edit the check in question. works as usual (we don't allow links in here yet)

Card
- [ ] During a meeting agenda phase, add a card. add a link to the card. finish the meeting. click the link on the card in the meeting summary. it works.

ProjectInvolves
- [ ] mention someone in a card and include a link. when they get the notification, they can click the link inside the card.

**Comment by mattkrick** [comment]
@ackernaut i'll push to dev server, it's working good on mine, except for links in email. those don't work, but they have never worked. do we want them to work? we'll need to conditionally use an anchor tag instead of a span in the EditorLink.js if so.

**Comment by ackernaut** [comment]
@mattkrick hey there! I’ll try latest locally and on the dev server. I’m okay with skipping the links in email for now.

**Comment by mattkrick** [comment]
mergin this one to keep the merge train moving. i'll put 8.5 up on dev so we can test & write a fix PR if need be.

**Pull request merged**
