### PR TITLE
Meeting facilitator UI updates

### LINKED ISSUE #411: fix `isFacilitating` box shadow
the box shadow is a little too thin to see. But if i look hard, i can see white between the gravatar icon & the ring.
screen shot 2016-10-19 at 1 50 24 pm

i think the best thing to do is to give it a white border of 1px & then box shadow it with something thicker, maybe 4px. that way the anti-aliasing fuzz goes away & the white looks intentional.

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #411 #162

### CODE REVIEW

**Comment by ackernaut** [comment]
Here are some screen shots of latest:

screenshot 2016-11-01 11 13 44
screenshot 2016-11-01 11 13 57
screenshot 2016-11-01 11 16 35

**Comment by ackernaut** [comment]
Question: Are we going to continue using the `isFacilitator` flag? If so, then I need to remove the help text under the “Start Meeting” button…otherwise it should stay?

**Comment by mattkrick** [comment]
i don't have a straight answer. @jordanh wanna make the executive call? you were talking about keeping it but not using it/showing it? 

i do think that the logic is wonky right now (if i click start button i'm the facilitator _if_ `isFacilitator == true`. Otherwise, it picks the first person with `isFacilitator`). My gut tells me that we should simplify this. We got options: 
- Only `isFacilitator` people can start the meeting. But that means if no one exists, then no one can start it.
- We ditch the idea of `isFacilitator`. 
- Perhaps only use `isLeader`

**Comment by mattkrick** [comment]
WRT to the updates, IMO it'd be cleaner to only put a ring around the facilitator (or rather put a white/transparent ring around everyone else). The pink is still not too far away from the gray & at a quick glance I don't really know who's the leader.

**Pull request merged**
