### PR TITLE
Epic 7 Agenda Input, Empty State, Tooltip

### PR DESCRIPTION
**Pull request by ackernaut**
This PR address the Agenda input and list portion of #1278 :

- [x] Updates the Agenda input to have more of that good ol’ input chrome
- [x] Adds some fakey Agenda items as an empty state
- [x] Adds a tooltip when ya hover the Agenda input (over the input, as to not obscure the first few items when they are present)

## Test Plan

Run this in both a Team Dash and a Meeting:

- [x] Pressing `+` will focus on the input, making it active.
- [x] Tapping into the input is also a normal thing.
- [ ] Tapping the actual `[+]` icon also allows you to focus the input.
- [ ] Hovering displays a tooltip above the input as to not obscure any first agenda items.
- [ ] Empty state is 3 fakey items.
- [ ] Can clear agenda items that are added.
- [ ] In the meeting, you cannot interact with the Agenda input and list during the _initial_ Check-In phase (after going to Updates or Agenda, and then going back to Check-In, you _can_ interact):
  - [ ] Cannot tap into input
  - [ ] Cannot press `+` to focus the input
  - [ ] Cannot remove any existing agenda items
  - [ ] Does not show a tooltip when hovering the input
- [ ] In the meeting, you can add an agenda item from any phase except the initial Check-In phase.
- [ ] In the meeting, can click on agenda items to navigate

### CODE REVIEW

**Comment by mattkrick** [comment]
- [ ] tooltips need to take a delay prop
- [ ] i should be able to call something like `tooltip.close()` and put that in a callback like `onFocus`.

**Comment by ackernaut** [comment]
@dan-f made some great suggestions:
- [ ] Add an optional delay prop to the tooltip and apply to the agenda input
- [ ] Enable the tooltip to close when the agenda input is active and the tooltip was opened because of a delayed hover
- [ ] The tooltip will not open at all if the user quickly taps into the input

**Comment by ackernaut** [comment]
This should go in _after_ the New Team form work gets merged.

**Comment by mattkrick** [comment]
@dan-f are you tackling the tooltip mods or shall I?

**Comment by dan-f** [comment]
@mattkrick go for it - I'm on #1435, which doesn't seem to require the tooltip mods.

**Comment by mattkrick** [comment]
# TEST 1
- [x] Pressing `+` will focus on the input, making it active.
- [x] Tapping into the input is also a normal thing.
- [ ] Tapping the actual `[+]` icon also allows you to focus the input.
- [ ] Hovering displays a tooltip after 1 second above the input as to not obscure any first agenda items.
- [ ] Empty state a helpful message
- [ ] Can clear agenda items that are added.
- [ ] In the meeting, you cannot interact with the Agenda input and list during the _initial_ Check-In phase (after going to Updates or Agenda, and then going back to Check-In, you _can_ interact):
  - [ ] Cannot tap into input
  - [ ] Cannot press `+` to focus the input
  - [ ] Cannot remove any existing agenda items
  - [ ] Does not show a tooltip when hovering the input
- [ ] In the meeting, you can add an agenda item from any phase except the initial Check-In phase.
- [ ] In the meeting, can click on agenda items to navigate

**Comment by ackernaut** [comment]
💥

**Pull request merged**
