### PR TITLE
dependency bumps & linting

### PR DESCRIPTION
**Pull request by mattkrick**
tests
- [ ] can change the org name & have it persist

### CODE REVIEW

**Comment by mattkrick** [comment]
this isn't broken locally, but the linting breaks in circleCI. can anyone confirm that this is working for them locally? (npm run lint)

**Comment by mattkrick** [comment]
linted all the things & fixed up some vulnerabilities from #809 & fixed the org name issue. i think we're ready!

**Comment by jordanh** [comment]
Wow! That's a lot of lint fixed :)

I'll cut a release and let's try it on staging.

**Comment by mattkrick** [comment]
ah! i've been testing locally & found some graphql bugs (was returning something that would turn into a promise, not a promise itself).

i also found something very strange--
when i signed out, sometimes it would wipe the localStorage clean. other times, it would wipe it clean & then put the old values back! this _only_ happened when the graphql bugs were going on (coincidence? it has to be coincidence). the end result is that sometimes you click log out & you don't really log out... yikes!

**Pull request merged**
