### PR TITLE
now using WebpackShellPlugin to build theme

### PR DESCRIPTION
**Pull request by jordanh**
Hey @mattkrick. Now using a plugin! 😁

We could integrate this more tightly via a custom plugin, but I'll take this incremental improvement.

Whachu think?

### CODE REVIEW

**Comment by mattkrick** [comment]
dang you're fast!
Does this mean we could get rid of https://github.com/ParabolInc/action/blob/master/src/universal/styles/theme/index.js?

it LGTM, one question i have for you though is about race conditions though. Currently, if i run `build:client` before `build:server` it'll barf because the theme doesn't exist yet. By editing the file above, I'm hoping we can relax that constraint?

Also, when you say `theme = require('theme.json');`, it knows to look in the build folder?? That's neat. i like that.

**Comment by mattkrick** [comment]
following up on the `theme = require('theme.json');` how'd you make that work anyways? It doesn't let me do it with `clientSchema.json` even though it's right there in the build folder next to `theme.json`

**Comment by mattkrick** [comment]
😞  This is a no-go. The build relies on a file that is being built in the build. We need to run the 2 in serial (same goes for clientSchema).

**Comment by mattkrick** [comment]
maaaybe we can listen for a specific `require` (eg `require('theme.json')`) and replace the require module with our own asset?

**Comment by jordanh** [comment]
I like you. You've got keen eyes. You caught something here. It's not a race, but a dependency issue.

The way `theme/index.js` is written, webpack will only require pre-computed `theme.json` during production. All other times, the styles are computed dynamically.

In other words, only the production client bundle depends on `theme.json`. I had stuck the WebpackShellPlugin in the wrong webpack file. I just fixed this.

So:
  * if you run `npm run dev` it'll just work, always
  * As before, if you run `npm build:server` it'll work fine, but if you want the client assets to be served you better build the client first
   * As before, `npm run bs` will work just fine as long as you wait for all builds to complete

**Comment by mattkrick** [comment]
correctly me if i'm wrong, but don't we still have a race condition with `npm run bs` because the `build:client` is racing against `build:server`?

**Comment by jordanh** [comment]
Ah damnit. You're correct.

**Comment by jordanh** [comment]
Actually, my apologies. No, not so anymore. The only build that depends on `theme.json` is the client build. `build:server` doesn't pull in those assets. So, that race doesn't exist.

However, there is another little fix I need to make...

**Comment by jordanh** [comment]
Ok, now I think it's GTG.

**Comment by mattkrick** [comment]
Ahhh, so the server gets the `theme.json` by building it, just like the dev config?

**Comment by mattkrick** [comment]
crap, i was hoping you'd solve this in a way that solves the `clientSchema` problem, too. Looks like it's back to inline-loaders 😭

**Pull request merged**
