### PR TITLE
Sprint: Reassign github projects [WIP]

### PR DESCRIPTION
**Pull request by mattkrick**
Project Card > Assign Menu
- [ ] When the assign menu toggle is clicked on a GitHub-integrated card, all the team members are shown except the current owner
- [ ] When a team member w/o push access to that repo is clicked, an error below the card is shown
- [ ] When a team member w/ push access to that repo is clicked, the owner is updated on GH & on the card
- [ ] when the assignee is changed on github & that person is integrated in parabol, the change is reflected
- [ ] when the assignee is changed on github & that person is NOT integrated in parabol, ???
- [ ] when more than 1 assignee is added on github, ???

### CODE REVIEW

**Comment by mattkrick** [comment]
did you mean to merge this?

**Comment by jordanh** [comment]
Hmm, I don't remember merging this branch. I remember manually merging `github` into master... Got to run now, will need to look at this a bit later.

**Comment by mattkrick** [comment]
maybe github looks for all PRs with the same commit hash? weird.

**Comment by jordanh** [comment]
Yes, it looks like that's what happened! Next time, if I ever merge an epic back to master that's in progress, I'll probably have to cut another branch off of the epic branch...

**Pull request merged**
