### PR TITLE
support breakpoints on safari

### PR DESCRIPTION
**Pull request by mattkrick**
Probably should be a hotfix. @ackernaut can you test with safari?

### CODE REVIEW

**Comment by ackernaut** [comment]
Will do!

**Comment by ackernaut** [comment]
@mattkrick LGTM, tested the Check-In view in Safari locally and both the bottom bar controls and the avatar change at the breakpoint!

Screenshot 2019-05-28 15 07 20
Screenshot 2019-05-28 15 07 25

**Comment by mattkrick** [comment]
sweet! merging now as mobile ios folks can't join meetings

**Comment by ackernaut** [comment]
💥 nice work!

**Pull request merged**
