### PR TITLE
Deprecate old menus

### PR DESCRIPTION
**Pull request by mattkrick**
This will take a fair amount of time, but it's worth it. here's what it fixes
- [ ] long clicks & touches don't reopen menu (really bad for mobile)
- [ ] gets us a little closer to being ready for React v17 (still so much to do...)
- [ ] can use the same loading spinner for loading code & data
- [ ] handles mouse scrolling better
- [ ] dimensions calculated automatically (with easy overrides)
- [ ] fun new animations
- [ ] standardizes all menus across the app
- [ ] removes inversion control pattern (nesting a toggle inside a possible menu)

Basically, this separates the toggle logic from the menu logic. It also provides toggle and animation state to the portal manager itself, so the portal knows what button made it open. This was all built into the new integrations menu in the task footer, but now it's spread across the whole app.

TEST
- [ ] Check out the new icon menus, such as the integration menu. it works as intended. 
- [ ] Check out a dropdown menu (eg the Start Meeting button or the Org Picker in the New Team form). they work as expected
- [ ] Check out a menu-like component like the DueDatePicker. it works
- [ ] Check out the meeting help menu in the demo, it works
- [ ] icon menu animations are appropriate (menu scales vertically & horizontally from the toggle button (150ms), then once it's almost full grown (at 115ms), the menu items animate in (~188ms total)
- [ ] dropdown menu animations are appropriate (menu starts at max width, grows vertically (~150ms), menu items begin to animate in around 80ms, finish at ~170ms.

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review! it's probably too much code to review, but if you could spot check a few menus, that should cover it (1 menu per commit, more or less)

**Comment by ackernaut** [comment]
I see! Planning to review this and Android fallback today.

**Comment by ackernaut** [comment]
### Tests (copy/paste)
- [ ] standard hub menu
- [ ] team CTA menu
- [ ] org member menu
- [ ] Jira config menu
- [ ] GitHub config menu
- [ ] emoji menu
- [ ] new team org picker
- [ ] task column add task
- [ ] add slack channel menu
- [ ] team dash team member
- [ ] user dash team menu
- [ ] team member avatar menu
- [ ] retro template picker
- [ ] new meeting avatar menu
- [ ] meeting avatar menu
- [ ] due date picker
- [ ] new meeting help menus
- [ ] old meeting help menus

**Comment by ackernaut** [comment]
### Test No. 1
- [ ] standard hub menu
- [ ] team CTA menu
- [ ] org member menu
- [ ] Jira config menu
- [ ] GitHub config menu
- [ ] emoji menu
- [ ] new team org picker
- [ ] task column add task
- [ ] add slack channel menu
- [ ] team dash team member
- [ ] user dash team menu
- [ ] team member avatar menu
- [ ] retro template picker
- [ ] new meeting avatar menu
- [ ] meeting avatar menu
- [ ] due date picker
- [ ] new meeting help menus
- [ ] old meeting help menus
- [ ] task card menus

**Comment by ackernaut** [comment]
@mattkrick all the menus seem to work, yay!

I did capture some things I saw, and some of them are not related but separate issues. We do need to fix the wrapping ticks and improve the spacing of the menu positioning.

**Comment by mattkrick** [comment]
everthing fixed up except the last 2.
the relay bug you saw is fixed on production, but not master (it was a hotfix)
i don't know about the Org not existing, i've never seen that & it shouldn't ever be possible to be on a team without an org

**Pull request merged**
