### PR TITLE
New upgrade modal

### PR DESCRIPTION
**Pull request by mattkrick**
TEST - UPDATE MODAL
- [ ] can update a CC
- [ ] update modal has correct title & buttons & closes after update

TEST - UPGRADE MODAL
- [ ] can upgrade using a valid card
- [ ] sync validation works for credit card number
- [ ] sync validation works for expiry
- [ ] sync validation works for CVC
- [ ] using a bad CVC (use card  4000000000000101) returns a useful error & makes the CVC icon red
- [ ] successful upgrade shows the success modal & confetti
- [ ] CC icon shows up 

TEST - SQUEEZE MODAL
- to test, change`actionType={'squeeze'}` in L46 of OrgBillingUpgrade
- [ ] has an upgrade later button
- [ ] clicking upgrade later shows the upgrade later modal
- [ ] modal starts off with a quote section
- [ ] looks good on mobile

TEST - ORG BILLING
- [ ] looks good on mobile
- [ ] has quote that changes on refresh
- [ ] clicking upgrade now opens the upgrade modal

### CODE REVIEW

**Comment by ackernaut** [comment]
This ready for review?

**Comment by mattkrick** [comment]
yessir!

**Comment by ackernaut** [comment]
### Test Cycle No. 1
TEST - UPDATE MODAL
- [ ] can update a CC
- [ ] update modal has correct title & buttons & closes after update

TEST - UPGRADE MODAL
- [ ] can upgrade using a valid card
- [ ] sync validation works for credit card number
- [ ] sync validation works for expiry
- [ ] sync validation works for CVC
- [ ] using a bad CVC (use card  4000000000000101) returns a useful error & makes the CVC icon red
- [ ] successful upgrade shows the success modal & confetti
- [ ] CC icon shows up 

TEST - SQUEEZE MODAL
- to test, change`actionType={'squeeze'}` in L46 of OrgBillingUpgrade
- [ ] has an upgrade later button
- [ ] clicking upgrade later shows the upgrade later modal
- [ ] modal starts off with a quote section
- [ ] looks good on mobile

TEST - ORG BILLING
- [ ] looks good on mobile
- [ ] has quote that changes on refresh
- [ ] clicking upgrade now opens the upgrade modal

**Comment by ackernaut** [comment]
This is looking great, making a few style touch-ups.

**Comment by ackernaut** [comment]
Real close here, making a responsive pass on org views…

**Pull request merged**
